### ISSUE TITLE
NullPointerException on startup

### ISSUE THREAD

**Issue by Quicksteve** [boy0001/FastAsyncWorldedit#10]
Starting the plugin on Spigot 1.8.8 with the newest code built the plugin crashes on startup.

After a small investigation this is caused by setting the static INSTANCE field to a new instance of the Fawe class, however in the Fawe constructor `IMP.getQueue()` is called, which will in the Bukkit version call `Fawe.get()`, but since the `INSTANCE` is currently being initialized (we are still in the constructor) this returns null and therefore `Fawe.get().checkVersion(getServerVersion(), 1, 9, 0)` blows up.

**Stack Trace:**
```
[17:11:06 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.2.1
[17:11:06 WARN]: java.lang.NullPointerException
[17:11:06 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.getQueue(FaweBukkit.java:137)
[17:11:06 WARN]:        at com.boydti.fawe.Fawe.<init>(Fawe.java:110)
[17:11:06 WARN]:        at com.boydti.fawe.Fawe.set(Fawe.java:76)
[17:11:06 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.onEnable(FaweBukkit.java:57)
[17:11:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[17:11:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[17:11:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:11:06 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[17:11:06 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[17:11:06 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[17:11:06 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[17:11:06 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Affected classes:**
[com.boydti.fawe.Fawe](https://github.com/boy0001/FastAsyncWorldedit/blob/master/src/main/java/com/boydti/fawe/Fawe.java)
[com.boydti.fawe.bukkit.FaweBukkit](
https://github.com/boy0001/FastAsyncWorldedit/blob/master/src/main/java/com/boydti/fawe/bukkit/FaweBukkit.java)

**Reproduction steps:**
On a spigot 1.8.8 server, install WorldEdit (either dev or normal build) and compile this project with maven, install the generated Bukkit jar, start the server.

**Suggested fix:**
Move the initialization of the `SetQueue.IMP` in the Fawe class into the delayed initialization.

**Comment by boy0001** [comment]
Fixed
