### ISSUE TITLE
Unhandledexception

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#100]
```
[09:08:37 WARN]: Exception in thread "Craft Scheduler Thread - 111"
[09:08:37 WARN]: org.apache.commons.lang.UnhandledException: Plugin FastAsyncWorldEdit v3.4.3 generated an exception while executing task 104416
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
        at java.util.LinkedList.remove(LinkedList.java:525)
        at java.util.Collections$SynchronizedList.remove(Collections.java:2426)
        at com.sk89q.worldedit.LocalSession.remember(LocalSession.java:217)
        at com.sk89q.worldedit.LocalSession.remember(LocalSession.java:200)
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:293)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

[09:08:37 WARN]: Exception in thread "Craft Scheduler Thread - 114"
[09:08:37 WARN]: org.apache.commons.lang.UnhandledException: Plugin FastAsyncWorldEdit v3.4.3 generated an exception while executing task 104415
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
        at java.util.LinkedList.remove(LinkedList.java:525)
        at java.util.Collections$SynchronizedList.remove(Collections.java:2426)
        at com.sk89q.worldedit.LocalSession.remember(LocalSession.java:217)
        at com.sk89q.worldedit.LocalSession.remember(LocalSession.java:200)
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:293)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

```

Happend when trying to `//regen` multiple regions VERY fast after each other.

FAWE 3.4.3

**Comment by boy0001** [comment]
Probably fixed since this is handled differently now, and I can't replicate.
