### ISSUE TITLE
IllegalStateException: Asynchronous entity add!

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#1006]
Paper dev 1421 (Spigot 1.12.2)
FastAsyncWorldEdit dev 1122
WorldEdit dev 3736

```
[15:42:46] [Craft Scheduler Thread - 1002/INFO]: WorldEdit: player (in "world"): /move 1 down -a - Orientation: WEST - Region: (14647, 55, -6638) - (14727, 56, -6558)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: java.lang.IllegalStateException: Asynchronous entity add!
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1116)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1141)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.call(BukkitChunk_1_12.java:325)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.call(BukkitChunk_1_12.java:25)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1456)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
[15:42:47] [ForkJoinPool-4-worker-14/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

```
[15:42:56] [Craft Scheduler Thread - 998/INFO]: WorldEdit: player (in "world"): /move 1 down -a - Orientation: NORTH - Region: (14647, 55, -6638) - (14727, 56, -6558)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: java.lang.IllegalStateException: Asynchronous entity add!
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1116)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1141)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.call(BukkitChunk_1_12.java:325)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.call(BukkitChunk_1_12.java:25)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1456)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
[15:42:56] [ForkJoinPool-4-worker-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by N0tMyFaultOG** [comment]
^Attach a /fawe debugpaste if this is an error still
