### ISSUE TITLE
Snapshot error

### ISSUE THREAD

**Issue by LogGits** [boy0001/FastAsyncWorldedit#1018]
Receiving an error with snapshots:
https://github.com/kangarko/CoreArena/issues/83
Essentially:
```
07:32:06 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
at java.lang.Thread.run(Thread.java:748)
Suppressed: java.io.IOException: Stream Closed
at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(FileOutputStream.java:326)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
at com.boydti.fawe.object.io.PGZIPOutputStream.flush(PGZIPOutputStream.java:221)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:141)
at java.io.DataOutputStream.flush(DataOutputStream.java:123)
at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
at com.sk89q.jnbt.NBTOutputStream.close(NBTOutputStream.java:379)
at com.sk89q.worldedit.extent.clipboard.io.SchematicWriter.close(SchematicWriter.java:497)
at com.sk89q.worldedit.util.io.Closer.close(Closer.java:168)
at me.kangarko.corearena.nul. .lpT4.int(SourceFile:243)
... 22 more
Suppressed: java.io.IOException: Stream Closed
at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(FileOutputStream.java:326)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
at com.boydti.fawe.object.io.PGZIPOutputStream.flush(PGZIPOutputStream.java:221)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:141)
at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
... 26 more
Suppressed: java.io.IOException: Stream Closed
at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(FileOutputStream.java:326)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
at com.boydti.fawe.object.io.PGZIPOutputStream.flush(PGZIPOutputStream.java:221)
at com.boydti.fawe.object.io.PGZIPOutputStream.close(PGZIPOutputStream.java:229)
at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
... 27 more
```

FAWE - 18.4.27-2ec9a92-1089
Paperspigot 1.12.2 - build1416

**Comment by boy0001** [comment]
Fixed in https://github.com/kangarko/CoreArena/issues/83
