### ISSUE TITLE
Error on 1.8.9 Using Java 8 (2)

### ISSUE THREAD

**Issue by TheIntelloBox** [boy0001/FastAsyncWorldedit#103]
[10:45:31] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to FastAsyncWorldEdit v3.4.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:628) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:471) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials.jar:?]
	at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials.jar:?]
	at com.earth2me.essentials.Teleport.teleport(Teleport.java:151) [Essentials.jar:?]
	at com.earth2me.essentials.commands.Commandtp.run(Commandtp.java:41) [Essentials.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:261) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.<init>(FawePlayer.java:90) ~[?:?]
	at com.boydti.fawe.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:15) ~[?:?]
	at com.boydti.fawe.bukkit.FaweBukkit.wrap(FaweBukkit.java:113) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.wrap(FawePlayer.java:84) ~[?:?]
	at com.boydti.fawe.bukkit.FaweBukkit.onPlayerChangedWorld(FaweBukkit.java:317) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor672.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	... 28 more

**Comment by RoboMWM** [comment]
1. please keep related issues in 1 ticket
2. WorldEdit version?
3. FAWE version?

**Comment by EvilOlaf** [comment]
Also `/version` might be interesting even though it is stated as 1.8.9.

**Comment by TheIntelloBox** [comment]
1) Sorry.

2) WorldEdit Version : 6.1.1-Snapshot;3394-9a65bdb7

3) FAWE Version : 3.4.3

4) Spigot 1.8.8 sorry.

**Comment by EvilOlaf** [comment]
Your WorldEdit seems to be outdated. Grab the latest dev from EngineHub.

**Comment by TheIntelloBox** [comment]
[13:47:29] [Craft Scheduler Thread - 4/WARN]: org.apache.commons.lang.UnhandledException: Plugin FastAsyncWorldEdit v3.4.3 generated an exception while executing task 342
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AbstractMethodError: org.primesoft.asyncworldedit.worldedit.utils.command.DispatcherWrapper.call(Ljava/lang/String;Lcom/sk89q/minecraft/util/commands/CommandLocals;[Ljava/lang/String;)Ljava/lang/Object;
	at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:253)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by boy0001** [comment]
Uninstall AsyncWorldEdit. The plugins aren't compatible.
