### ISSUE TITLE
FAWE is messing with entities async

### ISSUE THREAD

**Issue by aikar** [boy0001/FastAsyncWorldedit#1041]
# Bug report
**Description of the problem:**
```
[20:09:16] [ForkJoinPool-12-worker-2/WARN]: 	at net.minecraft.server.v1_12_R1.World.b(World.java:1227)
[20:09:16] [ForkJoinPool-12-worker-2/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1189)
[20:09:16] [ForkJoinPool-12-worker-2/WARN]: 	at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1207)
[20:09:16] [ForkJoinPool-12-worker-2/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1141)
[20:09:16] [ForkJoinPool-12-worker-2/WARN]: 	at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.call(BukkitChunk_1_12.java:326)
[20:09:16] [ForkJoinPool-12-worker-2/WARN]: 	at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.call(BukkitChunk_1_12.java:25)
[20:09:16] [ForkJoinPool-12-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[20:09:16] [ForkJoinPool-12-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[20:09:16] [ForkJoinPool-12-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
```
This is not allowed. It's causing the entities to be bugged and have to reload the chunk.

I'm going to try to block this in Paper by forcing it back sync, but please fix this so this returns to main thread to do operations.

**How to replicate**:
do something then //undo in a region with an entity

Version v18.05.24-099f733-1136-20.1.6

**Comment by boy0001** [comment]
Main thread is blocked, and entity manipulation is inside a synchronized block. 

How are the entities bugged? I can't seem to reproduce. Are there any more specific steps I should follow to recreate the problem?

**Comment by aikar** [comment]
I set stone over an entity:
https://i.imgur.com/08Mut68.png
This entity is "frozen"

//undo, 
https://i.imgur.com/VlqUJyj.png
still "frozen"

but also triggered:
[22:19:08] [ForkJoinPool-26-worker-0/WARN]: [Empire] [BOSS-REMOVAL] Another Boss near MARLIX at Location{world=CraftWorld{name=wastelands},x=4228.688035815153,y=84.24299403319755,z=-3695.9725075379097,pitch=0.0,yaw=0.0} - me: 1529719942 - them: 1529719935
[22:19:08] [ForkJoinPool-26-worker-0/WARN]: [Empire] [BOSS-REMOVAL] Another Boss near MARLIX at Location{world=CraftWorld{name=wastelands},x=4228.688035815153,y=84.24299403319755,z=-3695.9725075379097,pitch=0.0,yaw=0.0} - me: 1529719943 - them: 1529719935
[22:19:08] [ForkJoinPool-26-worker-0/WARN]: [Empire] [BOSS-REMOVAL] Another Boss near MARLIX at Location{world=CraftWorld{name=wastelands},x=4228.688035815153,y=84.24299403319755,z=-3695.9725075379097,pitch=0.0,yaw=0.0} - me: 1529719924 - them: 1529719935


My code listens to entity add to world, and deletes an entity if one is already nearby.

FAWE is messing with things here, it's trying to duplicate the entity

Can we have an option so FAWE leaves the entities alone, let them suffocate.

Also, it would be better to switch it to dispatch a Sync Task next tick instead of running it async, regardless if main is paused.

I assume fawe copied the entity data when the area was set, then when I did undo its trying to put it back, however the entity was still there just in a bugged state, so we end up with dupe adds.

**Comment by boy0001** [comment]
You'll want to set the `keep-entities-in-blocks` option to true. (line `114`)
