### ISSUE TITLE
Will not edit any blocks, spits error in console instead.

### ISSUE THREAD

**Issue by DankPotion** [boy0001/FastAsyncWorldedit#1046]
https://hastebin.com/fuwodidaji
Whenever I try to //set 1 for anything it doesn't set the blocks, same goes with //paste or //cut.
Console output is read bottom to top.
```30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.lang.Thread.run(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:680)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:221)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:182)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.util.concurrent.ForkJoinPool.awaitQuiescence(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitChunk_1_8.call(BukkitChunk_1_8.java:24)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitChunk_1_8.call(BukkitChunk_1_8.java:79)
30.06 01:35:58 [Server] INFO [01:35:58 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_8_R3.Chunk.getEntitySlices()[Ljava/util/List;
```

I honestly have no clue how to replicate this. 
![image](https://user-images.githubusercontent.com/22409375/42123455-3a6a38b0-7c07-11e8-9ab1-20ed7116d627.png)

**Comment by MongolNaFita** [comment]
The same thing is happening to me

**Comment by boy0001** [comment]
Try using Spigot or Paper instead of Bukkit

**Comment by MongolNaFita** [comment]
I can not function, you can send me the download, I could not
