### ISSUE TITLE
/targetoffset cannot be alias for itself

### ISSUE THREAD

**Issue by sandor111** [boy0001/FastAsyncWorldedit#1054]
My server keeps crashing from what seems to be a faw error:
```
[17:33:11] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Command /targetoffset cannot be alias for itself
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.help.CommandAliasHelpTopic.<init>(CommandAliasHelpTopic.java:18) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:138) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:331) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[17:33:11] [Server thread/ERROR]: This crash report has been saved to: /sfaction/./crash-reports/crash-2018-07-11_17.33.11-server.txt
[17:33:11] [Server thread/INFO]: Stopping server
```

Version: Spigot 1.8.8
Description / replicate:
Issue randomly occured after restarting my server, I didn’t change anything FAW related. My server kept booting up and crashing with that error, I removed FAW which temporary fixed the problem.

Server:
https://factionservers.net

**Comment by N0tMyFaultOG** [comment]
Update fawe, if the error occurs still, get a /fawe debugpaste and comment below
