### ISSUE TITLE
Undo'ing after WE outside region error

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#106]
When running //undo after a failed FAWE command due to "Outside allowed region",

`java.lang.reflect.InvocationTargetException: null` error is recieved

Console log (hastebin: http://hastebin.com/ajumamozub.avrasm: 

`[15:08:14] [Server thread/INFO]: dordsor21 issued server command: //undo
[15:08:14] [Craft Scheduler Thread - 7/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:252) [FastAsyncWorldEdit.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
	at com.sk89q.worldedit.function.operation.ChangeSetExecutor.<init>(ChangeSetExecutor.java:51) ~[?:?]
	at com.sk89q.worldedit.function.operation.ChangeSetExecutor.createUndo(ChangeSetExecutor.java:93) ~[?:?]
	at com.sk89q.worldedit.EditSession.undo(EditSession.java:878) ~[?:?]
	at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:296) ~[?:?]
	at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:61) ~[?:?]
	... 12 more`

**Comment by boy0001** [comment]
Possibly fixed

**Comment by dordsor21** [comment]
Is fixed

**Comment by Someone-NEW** [comment]
Hi i have latest version on my Spigot 1.10.2 but i can use any command on server with FAWE igame message i see is this one: 

Please report this error: [see console]
java.lang.reflect.InvocationTargetException: null

http://i.imgur.com/lLVnlq1.jpg

**Comment by boy0001** [comment]
@Someone-NEW 
Create a new ticket with the required information.
