### ISSUE TITLE
FAWE errors after rejoining a world

### ISSUE THREAD

**Issue by ThePoptartCrpr** [boy0001/FastAsyncWorldedit#1068]
# Bug report

**Debug paste link**:

/fawe debugpaste, like all other FAWE features in this issue, produces no output when the issue is present.

The error in the logs:

```
com.google.common.util.concurrent.UncheckedExecutionException: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
	at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1329) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1314) ~[guava-21.0.jar:?]
	at net.minecraft.network.NetHandlerPlayServer.func_194028_b(NetHandlerPlayServer.java:277) ~[oy.class:?]
	at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:1070) ~[pj.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:430) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:463) ~[chb.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:576) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
	at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:190) ~[PlatformManager.class:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.getConfiguration(PlatformManager.java:305) ~[PlatformManager.class:?]
	at com.sk89q.worldedit.WorldEdit.getConfiguration(WorldEdit.java:801) ~[WorldEdit.class:?]
	at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:172) ~[SessionManager.class:?]
	at com.sk89q.worldedit.WorldEdit.getSession(WorldEdit.java:210) ~[WorldEdit.class:?]
	at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:513) ~[FawePlayer.class:?]
	at com.boydti.fawe.object.FawePlayer.cancel(FawePlayer.java:146) ~[FawePlayer.class:?]
	at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:613) ~[FawePlayer.class:?]
	at com.boydti.fawe.forge.ForgeMain.handleQuit(ForgeMain.java:66) ~[ForgeMain.class:?]
	at com.boydti.fawe.forge.ForgeMain.onPlayerQuit(ForgeMain.java:53) ~[ForgeMain.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_ForgeMain_onPlayerQuit_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:578) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387) ~[pj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:839) ~[oy.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:456) ~[gw.class:?]
	at net.minecraft.network.NetHandlerPlayServer$2.run(NetHandlerPlayServer.java:281) ~[oy$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at net.minecraft.server.MinecraftServer.func
```

**Description of the problem:**

Upon exiting a world and rejoining, no FAWE feature works. Instead, when you attempt to use a command or whatnot, the above error is printed in the logs.

**How to replicate**:

Exit a singleplayer world, rejoin and attempt to use any FAWE feature, either commands or the wand.

**Checklist**:

- [ ] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by kmecpp** [comment]
Same issue here but for me it only happens when you make a WorldEdit selection and then shutdown the server

https://hastebin.com/keyayihapi.md

**Comment by SextupleTap** [comment]
I am also having this issue of WE/FAWE completely ceasing to function after rejoining a world on the forge edition.

https://hastebin.com/ogeciyobad.makefile

**Comment by ThePoptartCrpr** [comment]
Looks like a recent commit (https://github.com/boy0001/FastAsyncWorldedit/commit/839a3151d55f79075dcbbb891f09e25e6b64a8b2) seemed to address this issue, will test.

**Comment by SextupleTap** [comment]
The newest version of FAWE
FastAsyncWorldEdit-forge112-18.08.22-839a315-1192-21.1.9

Appears to have corrected this issue.

**Comment by ThePoptartCrpr** [comment]
Confirmed working across relogs in latest build.
