### ISSUE TITLE
Updated all plugins (1.12.2) and FAWE spits out error.

### ISSUE THREAD

**Issue by FrozenBeard** [boy0001/FastAsyncWorldedit#1071]
I did some maintenance on my creative server today as it was very outdated and both FAWE and Plots throw errors in console.

Paper version git-Paper-1534 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Wordledit: 6.1.10-SNAPSHOT;3807-e6c6a2c
FastAsyncWorldEdit version 18.08.03-e6128ec-1169-20.7.3
FastAsyncVoxelSniper version 18.08.06-60d07b5-1170-20.7.4
PlotSquared version 18.07.27-cd9d22c-2026

FAWE Error
```
[13:06:28] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v18.08.03-e6128ec-1169-20.7.3
[13:06:28] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set int field com.boydti.fawe.config.Settings$EXPERIMENTAL.DYNAMIC_CHUNK_RENDERING to java.lang.Boolean
[13:06:28] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[13:06:28] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[13:06:28] [Server thread/WARN]: 	at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(UnsafeIntegerFieldAccessorImpl.java:98)
[13:06:28] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Field.java:764)
[13:06:28] [Server thread/WARN]: 	at com.boydti.fawe.config.Config.set(Config.java:75)
[13:06:28] [Server thread/WARN]: 	at com.boydti.fawe.config.Config.load(Config.java:95)
[13:06:28] [Server thread/WARN]: 	at com.boydti.fawe.config.Settings.reload(Settings.java:451)
[13:06:28] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.setupConfigs(Fawe.java:437)
[13:06:28] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.<init>(Fawe.java:220)
[13:06:28] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.set(Fawe.java:187)
[13:06:28] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:95)
[13:06:28] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:76)
[13:06:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:06:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[13:06:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:06:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[13:06:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[13:06:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223)
[13:06:28] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[13:06:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

Plots Error:
```
[13:06:45] [Craft Scheduler Thread - 14/INFO]: [P2] Starting player data caching for: Hub
[13:06:45] [Craft Scheduler Thread - 14/INFO]: Fast mode UUID caching enabled!
[13:06:45] [Craft Scheduler Thread - 25/WARN]: java.lang.NullPointerException
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.getHandle(TitleManager_1_11.java:422)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:387)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: java.lang.NullPointerException
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.getHandle(TitleManager_1_11.java:422)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:387)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: java.lang.NullPointerException
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.getHandle(TitleManager_1_11.java:422)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:387)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: java.lang.NullPointerException
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at java.lang.reflect.Field.get(Field.java:393)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:388)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:06:45] [Craft Scheduler Thread - 25/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: java.lang.NullPointerException
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at java.lang.reflect.Field.get(Field.java:393)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:388)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:06:45] [Craft Scheduler Thread - 27/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: java.lang.NullPointerException
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at java.lang.reflect.Field.get(Field.java:393)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:388)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:06:45] [Craft Scheduler Thread - 29/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:06:45] [Craft Scheduler Thread - 14/INFO]: [P2] Cached a total of: 336 UUIDs
[13:06:45] [Craft Scheduler Thread - 14/INFO]: Failed to cache: 2 uuids - slowly processing all files
[13:06:45] [Craft Scheduler Thread - 14/INFO]: [P2] Cached a total of: 1281 UUIDs
```

**Comment by Miclebrick** [comment]
dynamic chunk rendering was changed to a variable distance, change it from true/false to an Int value

**Comment by FrozenBeard** [comment]
I never set it? i just updated the plugin? what should it be? whats the variable name?

**Comment by Miclebrick** [comment]
13:06:28] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v18.08.03-e6128ec-1169-20.7.3 [13:06:28] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set int field com.boydti.fawe.config.Settings$EXPERIMENTAL.DYNAMIC_CHUNK_RENDERING to java.lang.Boolean

dynamic chunk rendering under experimental

**Comment by Miclebrick** [comment]
This isn't the Plot Squared repo, you should probably make a separate issue for that error there

**Comment by Miclebrick** [comment]
re your edit, try restarting again

**Comment by FrozenBeard** [comment]
Restart fixed it, the old config I guess had to be populated with the variable change.
I will create a new issue in the right place.
Thank you.
