### ISSUE TITLE
Incompatible with NotEnoughIDs Mod

### ISSUE THREAD

**Issue by SourcePowered** [boy0001/FastAsyncWorldedit#1073]
```
22:00:19] [Server thread/ERROR]: &8(&4&lFAWE&8)&r&7 ====== INVALID CLIPBOARD ======
[22:00:19] [Server thread/WARN]: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
[22:00:19] [Server thread/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:190)
[22:00:19] [Server thread/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformManager.getConfiguration(PlatformManager.java:305)
[22:00:19] [Server thread/WARN]: 	at com.sk89q.worldedit.WorldEdit.getConfiguration(WorldEdit.java:801)
[22:00:19] [Server thread/WARN]: 	at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:172)
[22:00:19] [Server thread/WARN]: 	at com.sk89q.worldedit.WorldEdit.getSession(WorldEdit.java:210)
[22:00:19] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:513)
[22:00:19] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer.loadClipboardFromDisk(FawePlayer.java:332)
[22:00:19] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer.<init>(FawePlayer.java:123)
[22:00:19] [Server thread/WARN]: 	at com.boydti.fawe.forge.ForgePlayer.<init>(ForgePlayer.java:19)
[22:00:19] [Server thread/WARN]: 	at com.boydti.fawe.forge.FaweForge.wrap(FaweForge.java:116)
[22:00:19] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer.wrap(FawePlayer.java:115)
[22:00:19] [Server thread/WARN]: 	at com.boydti.fawe.forge.ForgeMain.handleQuit(ForgeMain.java:62)
[22:00:19] [Server thread/WARN]: 	at com.boydti.fawe.forge.ForgeMain.onPlayerQuit(ForgeMain.java:51)
[22:00:19] [Server thread/WARN]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_153_ForgeMain_onPlayerQuit_PlayerLoggedOutEvent.invoke(.dynamic)
[22:00:19] [Server thread/WARN]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[22:00:19] [Server thread/WARN]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[22:00:19] [Server thread/WARN]: 	at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:578)
[22:00:19] [Server thread/WARN]: 	at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:439)
[22:00:19] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:851)
[22:00:19] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147360_c(NetHandlerPlayServer.java:283)
[22:00:19] [Server thread/WARN]: 	at net.minecraft.server.management.ServerConfigurationManager.func_72392_r(ServerConfigurationManager.java:1574)
[22:00:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:570)
[22:00:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:725)
[22:00:19] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:00:19] [Server thread/ERROR]: &8(&4&lFAWE&8)&r&7 ===============---=============
[22:00:19] [Server thread/ERROR]: &8(&4&lFAWE&8)&r&7 This shouldn't result in any failure
[22:00:19] [Server thread/ERROR]: &8(&4&lFAWE&8)&r&7 File: c006cbfe-bf23-3b7c-96ad-4a09a8f3fc6d.bd (len:2702)
[22:00:19] [Server thread/ERROR]: &8(&4&lFAWE&8)&r&7 ===============---=============
[22:00:19] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@39b3e6d5:
com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
	at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:190) ~[PlatformManager.class:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.getConfiguration(PlatformManager.java:305) ~[PlatformManager.class:?]
	at com.sk89q.worldedit.WorldEdit.getConfiguration(WorldEdit.java:801) ~[WorldEdit.class:?]
	at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:172) ~[SessionManager.class:?]
	at com.sk89q.worldedit.WorldEdit.getSession(WorldEdit.java:210) ~[WorldEdit.class:?]
	at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:513) ~[FawePlayer.class:?]
	at com.boydti.fawe.object.FawePlayer.cancel(FawePlayer.java:146) ~[FawePlayer.class:?]
	at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:613) ~[FawePlayer.class:?]
	at com.boydti.fawe.forge.ForgeMain.handleQuit(ForgeMain.java:64) ~[ForgeMain.class:?]
	at com.boydti.fawe.forge.ForgeMain.onPlayerQuit(ForgeMain.java:51) ~[ForgeMain.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_153_ForgeMain_onPlayerQuit_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:578) [FMLCommonHandler.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:439) [oi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:851) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147360_c(NetHandlerPlayServer.java:283) [nh.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72392_r(ServerConfigurationManager.java:1574) [oi.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:570) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:725) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[22:00:19] [Server thread/ERROR]: Index: 12 Listeners:
[22:00:19] [Server thread/ERROR]: 0: NORMAL
[22:00:19] [Server thread/ERROR]: 1: ASM: ModuleCore tick(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: 2: ASM: minetweaker.mc1710.FMLEventHandler@1cb7578f onPlayerLoggedOut(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: 3: ASM: ftb.utils.mod.handlers.FTBUPlayerEventHandler@c657efa playerLoggedOut(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: 4: ASM: train.common.core.handlers.WorldEvents@7d889fa5 playerQuitEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: 5: ASM: buildcraft.core.tablet.manager.TabletManagerClient@1f419906 playerLogout(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: 6: ASM: buildcraft.core.tablet.manager.TabletManagerServer@7fc69e40 playerLogout(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: 7: ASM: mekanism.common.CommonPlayerTracker@1a38e252 onPlayerLogoutEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: 8: ASM: li.cil.oc.common.EventHandler$@4ea9c4ad onPlayerLogout(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: 9: ASM: li.cil.oc.common.event.NanomachinesHandler$Common$@2760da05 onPlayerDisconnect(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: 10: ASM: net.quetzi.morpheus.MorpheusEventHandler@54e7fb8d loggedOutEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: 11: LOWEST
[22:00:19] [Server thread/ERROR]: 12: ASM: com.boydti.fawe.forge.ForgeMain@a8973dd onPlayerQuit(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[22:00:19] [Server thread/ERROR]: Exception stopping the server
com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
	at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:190) ~[PlatformManager.class:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.getConfiguration(PlatformManager.java:305) ~[PlatformManager.class:?]
	at com.sk89q.worldedit.WorldEdit.getConfiguration(WorldEdit.java:801) ~[WorldEdit.class:?]
	at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:172) ~[SessionManager.class:?]
	at com.sk89q.worldedit.WorldEdit.getSession(WorldEdit.java:210) ~[WorldEdit.class:?]
	at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:513) ~[FawePlayer.class:?]
	at com.boydti.fawe.object.FawePlayer.cancel(FawePlayer.java:146) ~[FawePlayer.class:?]
	at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:613) ~[FawePlayer.class:?]
	at com.boydti.fawe.forge.ForgeMain.handleQuit(ForgeMain.java:64) ~[ForgeMain.class:?]
	at com.boydti.fawe.forge.ForgeMain.onPlayerQuit(ForgeMain.java:51) ~[ForgeMain.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_153_ForgeMain_onPlayerQuit_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:578) ~[FMLCommonHandler.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:439) ~[oi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:851) ~[nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147360_c(NetHandlerPlayServer.java:283) ~[nh.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72392_r(ServerConfigurationManager.java:1574) ~[oi.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:570) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:725) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[22:00:19] [Server thread/INFO]: Applying holder lookups
[22:00:19] [Server thread/INFO]: Holder lookups applied
```

**Comment by boy0001** [comment]
Can you attach your full startup log?
