### ISSUE TITLE
Error on stack

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#108]
```
[21:24:45 INFO]: Olaf issued server command: //stack 50
[21:24:45 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-3482.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-3482.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:253) [FastAsyncWorldEdit-bukkit18.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_91]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_91]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getEntities(CraftWorld.java:626) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at com.sk89q.worldedit.bukkit.BukkitWorld.getEntities(BukkitWorld.java:90) ~[?:?]
        at com.boydti.fawe.wrappers.WorldWrapper.getEntities(WorldWrapper.java:371) ~[?:?]
        at com.boydti.fawe.wrappers.WorldWrapper.getEntities(WorldWrapper.java:371) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:94) ~[?:?]
        at com.boydti.fawe.object.extent.FastWorldEditExtent.getEntities(FastWorldEditExtent.java:79) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:94) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:94) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:94) ~[?:?]
        at com.boydti.fawe.object.HistoryExtent.getEntities(HistoryExtent.java:100) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:94) ~[?:?]
        at com.sk89q.worldedit.EditSession.getEntities(EditSession.java:919) ~[?:?]
        at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:234) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:69) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeSmart(Operations.java:77) ~[?:?]
        at com.sk89q.worldedit.EditSession.stackCuboidRegion(EditSession.java:1447) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.stack(RegionCommands.java:324) ~[?:?]
        ... 12 more

```
FAWE 3.4.3

**Comment by boy0001** [comment]
This should have been fixed.
