### ISSUE TITLE
Error 1.13

### ISSUE THREAD

**Issue by TheTopCz** [boy0001/FastAsyncWorldedit#1088]
# Bug report
`BeneG_ issued server command: //undo
[23:49:44 ERROR]: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandSuggestionEvent@64c85af7 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onTabComplete(WorldEditPlugin.java:402) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.tabComplete(DynamicPluginCommand.java:84) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at org.bukkit.command.Command.tabComplete(Command.java:90) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:217) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.tabCompleteCommand(CraftServer.java:1641) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.tabComplete(CraftServer.java:1613) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.craftbukkit.v1_13_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommaBeneG_ issued server command: //undo
[23:49:44 ERROR]: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandSuggestionEvent@64c85af7 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onTabComplete(WorldEditPlugin.java:402) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.tabComplete(DynamicPluginCommand.java:84) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at org.bukkit.command.Command.tabComplete(Command.java:90) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:217) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.tabCompleteCommand(CraftServer.java:1641) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.tabComplete(CraftServer.java:1613) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.craftbukkit.v1_13_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:68) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:372) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:503) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.PacketPlayInTabComplete.a(SourceFile:36) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.PacketPlayInTabComplete.a(SourceFile:9) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor578.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
... 23 more
Caused by: java.lang.RuntimeException: Invalid suggestion context
at com.sk89q.worldedit.util.command.parametric.AParametricCallable.getSuggestions(AParametricCallable.java:301) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.util.command.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:173) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandSuggestion(CommandManager.java:510) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at sun.reflect.GeneratedMethodAccessor578.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
... 23 morendNode.java:68) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:372) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:503) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.PacketPlayInTabComplete.a(SourceFile:36) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.PacketPlayInTabComplete.a(SourceFile:9) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor578.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
... 23 more
Caused by: java.lang.RuntimeException: Invalid suggestion context
at com.sk89q.worldedit.util.command.parametric.AParametricCallable.getSuggestions(AParametricCallable.java:301) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.util.command.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:173) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandSuggestion(CommandManager.java:510) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at sun.reflect.GeneratedMethodAccessor578.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[FastAsyncWorldEdit-bukkit-18.08.17-0cc0ee7-2005.jar:?]
... 23 more`
**Debug paste link**:
https://hastebin.com/yucikaxuto

**Description of the problem:**
After using commands //undo will be displayed error

After using worldedit it happens that he can not write in the chat and throws out a message Cannot send chat message

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Try updating FAWE
