### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by RiftBladeMc** [boy0001/FastAsyncWorldedit#1111]
whenever server is started this happens.
```
[18:07:15] [Server thread/ERROR]: Could not load 'plugins/FAWE.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:322) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:230) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:784) ~[patched_1.13.1.jar:git-Paper-214]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_181]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_181]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_181]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_181]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[patched_1.13.1.jar:git-Paper-214]
	... 5 more
```

**Comment by RiftBladeMc** [comment]
It seems that removing the plugin, and downloading it again fixed it.
