### ISSUE TITLE
Setbiome Error (1.13.1)

### ISSUE THREAD

**Issue by EazyFTW** [boy0001/FastAsyncWorldedit#1116]
# Bug report

**Debug paste link**:

Game crashed. Useless.

**Description of the problem:**

Error [Game Crashed]: https://hastebin.com/qusipiweca.md

It should tell you it's not a biome, not crash. ;)

**How to replicate**:

Type //setbiome OCEAN

**Checklist**:

- [ ] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
the hastebin is empty. Can you attach the error?

**Comment by EazyFTW** [comment]
It isn't for me but here:
```[20:35:45 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Exception ticking world
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1077) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:936) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:834) ~[patched_1.13.1.jar:git-Paper-221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_13_R2.WorldServer.n_(WorldServer.java:535) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:318) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1066) ~[patched_1.13.1.jar:git-Paper-221]
        ... 4 more
[20:35:45 ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException: null
        at net.minecraft.server.v1_13_R2.WorldServer.n_(WorldServer.java:535) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:318) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1066) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:936) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:834) ~[patched_1.13.1.jar:git-Paper-221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[20:35:45 ERROR]: This crash report has been saved to: /home/NetronixMC/Hub/./crash-reports/crash-2018-09-06_20.35.45-server.txt```
