### ISSUE TITLE
Command blocks missing defined commands on copy/stack

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#112]
When copying or stacking command blocks commands are not copied. The copied blocks are empty.

FAWE 3.5.0

**Comment by boy0001** [comment]
Can't replicate. Make sure you are not trying to open it with the axe tool.

**Comment by EvilOlaf** [comment]
Will retry later.

**Comment by EvilOlaf** [comment]
Same issue. For fun I tried within or without a WG region.
Stacked command blocks are empty. Did not use a valid command, just entered `test` in the first one.

What I noticed when I tried to copy the block I got a similar stacktrace to #108:
```
[11:35:43 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) ~[worldedit-bukkit-6.1.2.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.2.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:252) [FastAsyncWorldEdit-bukkit18-3.5.0-00c685c.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_91]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_91]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getEntities(CraftWorld.java:626) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at com.sk89q.worldedit.bukkit.BukkitWorld.getEntities(BukkitWorld.java:90) ~[?:?]
        at com.boydti.fawe.wrappers.WorldWrapper.getEntities(WorldWrapper.java:359) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:94) ~[?:?]
        at com.boydti.fawe.object.extent.FastWorldEditExtent.getEntities(FastWorldEditExtent.java:94) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:94) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:94) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:94) ~[?:?]
        at com.boydti.fawe.object.HistoryExtent.getEntities(HistoryExtent.java:100) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:94) ~[?:?]
        at com.sk89q.worldedit.EditSession.getEntities(EditSession.java:942) ~[?:?]
        at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:234) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:69) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:56) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:169) ~[?:?]
        ... 12 more
```

The 2nd attempt to copy the command block was successful. However the pasted one was also empty.

**Comment by boy0001** [comment]
I was using 1.9.4

**Comment by boy0001** [comment]
Try reconnecting (or teleporting away) to see if it's client side. It might be client side.

**Comment by boy0001** [comment]
ba2f9159b68646dd437cc62d98d76095b9868074 fixes the stacktrace (which is a different issue)

**Comment by EvilOlaf** [comment]
You were right. Was indeed a client issue.

**Comment by dordsor21** [comment]
This may have been fixed in the changes to chunk refresh after a WE is completed?
