### ISSUE TITLE
Current versions don't download WE or VS anymore (1.12.2)

### ISSUE THREAD

**Issue by BrainStone** [boy0001/FastAsyncWorldedit#1123]
# Bug report

**Debug paste link**:
FAWE not starting properly due to missing WE. So can't run `/fawe debugpaste`

**Description of the problem:**
 FAWE and FAVS used to automatically download the correct WorldEdit and VoxelSniper versions, but now it doesn't anymore, I haven't tested it for 1.13, only 1.12.2 (because my server is running 1.12.2).

Only somewhat relevant errors I could see in the log:

```
> [00:38:27 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v18.09.09-936bd6f-1210-21.4.8
> [00:38:28 WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/extent/InputExtent
> [00:38:28 WARN]: at java.lang.ClassLoader.defineClass1(Native Method)
> [00:38:28 WARN]: at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> [00:38:28 WARN]: at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148)
> [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191)
> [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
> [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
> [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [00:38:28 WARN]: at com.boydti.fawe.Fawe.debug(Fawe.java:204)
> [00:38:28 WARN]: at com.boydti.fawe.util.Jars.download(Jars.java:59)
> [00:38:28 WARN]: at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:62)
> [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
> [00:38:28 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
> [00:38:28 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
> [00:38:28 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
> [00:38:28 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
> [00:38:28 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
> [00:38:28 WARN]: at java.lang.Thread.run(Thread.java:748)
> [00:38:28 WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.extent.InputExtent
> [00:38:28 WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152)
> [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
> [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [00:38:28 WARN]: ... 20 more
> [00:38:28 ERROR]: Error occurred while enabling FastAsyncWorldEdit v18.09.09-936bd6f-1210-21.4.8 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/extent/InputExtent
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_171]
at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_171]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_171]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
at com.boydti.fawe.Fawe.debug(Fawe.java:204) ~[?:?]
at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:69) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-2cf50f0-2b93d83]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.extent.InputExtent
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
... 19 more
> [00:38:28 INFO]: [FastAsyncVoxelSniper] Enabling FastAsyncVoxelSniper v18.09.09-936bd6f-1210-21.4.8
> [00:38:28 WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/extent/InputExtent
> [00:38:28 WARN]: at java.lang.ClassLoader.defineClass1(Native Method)
> [00:38:28 WARN]: at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> [00:38:28 WARN]: at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148)
> [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191)
> [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
> [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
> [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [00:38:28 WARN]: at com.boydti.fawe.Fawe.debug(Fawe.java:204)
> [00:38:28 WARN]: at com.boydti.fawe.util.Jars.download(Jars.java:59)
> [00:38:28 WARN]: at com.boydti.fawe.bukkit.favs.Favs.onEnable(Favs.java:44)
> [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
> [00:38:28 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
> [00:38:28 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
> [00:38:28 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
> [00:38:28 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
> [00:38:28 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
> [00:38:28 WARN]: at java.lang.Thread.run(Thread.java:748)
> [00:38:28 WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.extent.InputExtent
> [00:38:28 WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152)
> [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
> [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [00:38:28 WARN]: ... 20 more
```

**How to replicate**:
Install latest FAWE and FAVS on latest Spigot for 1.12.2 and watch it not download WorldEdit and VoxelSniper,

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Fader-GumGum** [comment]
Same here:
[20:42:27] [Server thread/ERROR]: Ambiguous plugin name `FastAsyncWorldEdit' for files `plugins\FastAsyncWorldEdit-bukkit-18.09.09-936bd6f-1210-21.4.8.jar' and `plugins\DummyFawe.jar' in `plugins'

**Comment by xSamagon** [comment]
> # Bug report
> **Debug paste link**:
> FAWE not starting properly due to missing WE. So can't run `/fawe debugpaste`
> 
> **Description of the problem:**
> FAWE and FAVS used to automatically download the correct WorldEdit and VoxelSniper versions, but now it doesn't anymore, I haven't tested it for 1.13, only 1.12.2 (because my server is running 1.12.2).
> 
> Only somewhat relevant errors I could see in the log:
> 
> ```
> > [00:38:27 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v18.09.09-936bd6f-1210-21.4.8
> > [00:38:28 WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/extent/InputExtent
> > [00:38:28 WARN]: at java.lang.ClassLoader.defineClass1(Native Method)
> > [00:38:28 WARN]: at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> > [00:38:28 WARN]: at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
> > [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> > [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> > [00:38:28 WARN]: at com.boydti.fawe.Fawe.debug(Fawe.java:204)
> > [00:38:28 WARN]: at com.boydti.fawe.util.Jars.download(Jars.java:59)
> > [00:38:28 WARN]: at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:62)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
> > [00:38:28 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
> > [00:38:28 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
> > [00:38:28 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
> > [00:38:28 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
> > [00:38:28 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
> > [00:38:28 WARN]: at java.lang.Thread.run(Thread.java:748)
> > [00:38:28 WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.extent.InputExtent
> > [00:38:28 WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
> > [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> > [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> > [00:38:28 WARN]: ... 20 more
> > [00:38:28 ERROR]: Error occurred while enabling FastAsyncWorldEdit v18.09.09-936bd6f-1210-21.4.8 (Is it up to date?)
> java.lang.NoClassDefFoundError: com/sk89q/worldedit/extent/InputExtent
> at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_171]
> at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_171]
> at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_171]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
> at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
> at com.boydti.fawe.Fawe.debug(Fawe.java:204) ~[?:?]
> at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:69) ~[?:?]
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-2cf50f0-2b93d83]
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-2cf50f0-2b93d83]
> at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-2cf50f0-2b93d83]
> at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-2cf50f0-2b93d83]
> at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [server.jar:git-Spigot-2cf50f0-2b93d83]
> at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-2cf50f0-2b93d83]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
> Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.extent.InputExtent
> at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
> ... 19 more
> > [00:38:28 INFO]: [FastAsyncVoxelSniper] Enabling FastAsyncVoxelSniper v18.09.09-936bd6f-1210-21.4.8
> > [00:38:28 WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/extent/InputExtent
> > [00:38:28 WARN]: at java.lang.ClassLoader.defineClass1(Native Method)
> > [00:38:28 WARN]: at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> > [00:38:28 WARN]: at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
> > [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> > [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> > [00:38:28 WARN]: at com.boydti.fawe.Fawe.debug(Fawe.java:204)
> > [00:38:28 WARN]: at com.boydti.fawe.util.Jars.download(Jars.java:59)
> > [00:38:28 WARN]: at com.boydti.fawe.bukkit.favs.Favs.onEnable(Favs.java:44)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
> > [00:38:28 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
> > [00:38:28 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
> > [00:38:28 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
> > [00:38:28 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
> > [00:38:28 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
> > [00:38:28 WARN]: at java.lang.Thread.run(Thread.java:748)
> > [00:38:28 WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.extent.InputExtent
> > [00:38:28 WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152)
> > [00:38:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
> > [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> > [00:38:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> > [00:38:28 WARN]: ... 20 more
> ```
> **How to replicate**:
> Install latest FAWE and FAVS on latest Spigot for 1.12.2 and watch it not download WorldEdit and VoxelSniper,
> 
> **Checklist**:
> 
> * [x]  I included a `/fawe debugpaste` link
> * [x]  I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
> * [x]  I made sure I am using an up-to-date version of FAWE
> * [x]  I Made sure the bug/error is not caused by any other plugin

Had the same problem, but not while downloading WorldEdit.
It crashed while disabling AsyncWorldEdit.

This problem is not caused by the download of WorldEdit, it is caused by calling:
Fawe.debug

Since it uses "com.sk89q.worldedit.session.request.Request", which imports "com.sk89q.worldedit.EditSession", which extends "com.sk89q.worldedit.extent.InputExtent" this error is thrown.

This was btw added with the commit beb2e0e

**Comment by joritochip** [comment]
Until a proper fix, here is how to fix the issue:

1. Download this and place it in your server: 
https://ci.athion.net/job/FastAsyncWorldEdit/1185/artifact/target/FastAsyncWorldEdit-bukkit-18.09.02-0021ab0-1196-21.2.2.jar

2. Restart your server

3. Delete that file from your server and download the latest 1.12.2 download here:
https://empcraft.com/fawe/latest.php?bukkit

4. Restart your server

5. Congratulations, your server is now working once more!
