### ISSUE TITLE
 No WE or VS file created, Only DummyFAWE and WE ERROR ' vunspecified'. 1.13 #1851

### ISSUE THREAD

**Issue by JK82NL** [boy0001/FastAsyncWorldedit#1135]
**Debug paste link**:

# We will start with some informational files
links.config_yml: https://hastebin.com/nemabekude
links.messages_yml: https://hastebin.com/ajahabuhiv
links.commands_yml: https://hastebin.com/mixezoluho
links.latest_log: https://hastebin.com/ocofosimez

# Server Information
server.platform: bukkit
server.plugins: 
 - FastAsyncWorldEdit: 1.0
 - WorldEdit: unspecified
 - FastAsyncVoxelSniper: 18.09.18-5b5336c-2046
 - WorldGuard: 7.0.0-SNAPSHOT;febd212
server.version: git-Spigot-fe3ab0d-162bda9 (MC: 1.13) / 1.13-R0.1-SNAPSHOT

# YAY! Now, let's see what we can find in your JVM
memory.free: 663667600
memory.max: 4772593664
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_181'
os.arch: 'amd64'
os.name: 'Windows 7'
os.version: '6.1'

**Description of the problem:**
Can not make FAWE & FAVS run with all requirements that are on the official web page. Tried the new versions that came out every couple of days, but the same error keeps coming up.
As you can see there is only FAWE, FAVS and the necessary WG from the website. 

First Warning is
[17:07:23] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/NBTBase
[17:07:23] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[17:07:23] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[17:07:23] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.adapter.BukkitImplLoader.loadAdapter(BukkitImplLoader.java:159)
[17:07:23] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:295)
[17:07:23] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:159)
[17:07:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:07:23] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.init(WorldEditPlugin.java:135)
[17:07:23] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.<init>(WorldEditPlugin.java:119)
[17:07:23] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:07:23] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:07:23] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:07:23] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[17:07:23] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[17:07:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90)
[17:07:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[17:07:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327)
[17:07:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:273)
[17:07:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.loadPlugins(CraftServer.java:315)
[17:07:23] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:213)
[17:07:23] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
[17:07:23] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[17:07:23] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.NBTBase
[17:07:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
[17:07:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[17:07:23] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:07:23] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:07:23] [Server thread/WARN]: 	... 21 more
[17:07:23] [Server thread/WARN]: 
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and biome-related functions.
**
** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
**********************************************

[17:07:23] [Server thread/INFO]: (FAWE) Invalid block registered minecraft:__reserved__
[17:07:23] [Server thread/INFO]: (FAWE) Invalid block registered minecraft:dead_brain_coral
[17:07:23] [Server thread/INFO]: (FAWE) Invalid block registered minecraft:dead_bubble_coral
[17:07:23] [Server thread/INFO]: (FAWE) Invalid block registered minecraft:dead_fire_coral
[17:07:23] [Server thread/INFO]: (FAWE) Invalid block registered minecraft:dead_horn_coral
[17:07:23] [Server thread/INFO]: (FAWE) Invalid block registered minecraft:dead_tube_coral

FIRST ERROR is:
[17:07:30] [Server thread/ERROR]: [WorldEdit] Plugin WorldEdit vunspecified has failed to register events for class com.boydti.fawe.bukkit.listener.AsyncTabCompleteListener because com/destroystokyo/paper/event/server/AsyncTabCompleteEvent does not exist.

**How to replicate**:
Use Fresh 1.13 #1851 Spigot with only plugins; FAWE, FAVS and the FAWE WG version. 

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Use 1.13.1
