### ISSUE TITLE
World Guard doesn't work with FAWE (PaperSpigot)

### ISSUE THREAD

**Issue by Thund3rst0rm89** [boy0001/FastAsyncWorldedit#1149]
**Description of the problem:**
World Guard doesn't work. I don't no why. If i write the command "/plugins", WorldGuard is in red, so it is disable. If i delete FAWE everything is ok and World Guard work. All Version are new i downloaded it few minutes ago

**Debug paste link**:
# Server Information
server.platform: bukkit
server.plugins: 
 - LuckPerms: 4.3.7
 - WarpMeUp: 1.1.0
 - dynmap: 3.0-beta-1-129
 - PotionExtender: 1.8.0
 - TicketCounter: 1.3.0
 - FastAsyncWorldEdit: 1.0
 - Drugoye: 1.6.0
 - PlaceholderAPI: 2.9.2
 - Serverstats: 1.3.0
 - CommandConverter: 1.7.1
 - GravestoneSpawn: 1.1.0
 - WorldBorder: 1.8.7
 - GUI: 1.1.0
 - Vault: 1.7.1-b91
 - BungeeTabListPlus: 2.8.9
 - SimpleChatChannels: 2.2.0
 - WorldEdit: unspecified
 - FastAsyncVoxelSniper: 18.10.04-75c111e-2053
 - WorldGuard: 7.0.0-SNAPSHOT;1749-a6261b9
server.version: git-Paper-342 (MC: 1.13.1) / 1.13.1-R0.1-SNAPSHOT

# YAY! Now, let's see what we can find in your JVM
memory.free: 287337704
memory.max: 1864368128
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_171'
os.arch: 'amd64'
os.name: 'Linux'
os.version: '4.4.0-135-generic'

` [23:30:20 INFO]: [WorldGuard] Enabling WorldGuard v7.0.0-SNAPSHOT;1749-a6261b9
[23:30:20 ERROR]: Error occurred while enabling WorldGuard v7.0.0-SNAPSHOT;1749-a6261b9 (Is it up to date?)
java.lang.NoSuchFieldError: LEATHER
at com.sk89q.worldguard.bukkit.BukkitWorldConfiguration.loadConfiguration(BukkitWorldConfiguration.java:261) ~[?:?]
at com.sk89q.worldguard.bukkit.BukkitWorldConfiguration.<init>(BukkitWorldConfiguration.java:98) ~[?:?]
at com.sk89q.worldguard.bukkit.BukkitConfigurationManager.get(BukkitConfigurationManager.java:87) ~[?:?]
at com.sk89q.worldguard.bukkit.BukkitConfigurationManager.postLoad(BukkitConfigurationManager.java:69) ~[?:?]
at com.sk89q.worldguard.config.YamlConfigurationManager.load(YamlConfigurationManager.java:103) ~[?:?]
at com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.load(BukkitWorldGuardPlatform.java:112) ~[?:?]
at com.sk89q.worldguard.WorldGuard.setup(WorldGuard.java:90) ~[?:?]
at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:151) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Paper-342]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[server.jar:git-Paper-342]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[server.jar:git-Paper-342]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[server.jar:git-Paper-342]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[server.jar:git-Paper-342]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[server.jar:git-Paper-342]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[server.jar:git-Paper-342]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[server.jar:git-Paper-342]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311) ~[server.jar:git-Paper-342]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[server.jar:git-Paper-342]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[23:30:20 INFO]: [WorldGuard] Disabling WorldGuard v7.0.0-SNAPSHOT;1749-a6261b9
[23:30:20 INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[23:30:20 ERROR]: Error occurred while disabling WorldGuard v7.0.0-SNAPSHOT;1749-a6261b9 (Is it up to date?)
java.lang.NullPointerException: null
at com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.unload(BukkitWorldGuardPlatform.java:120) ~[?:?]
at com.sk89q.worldguard.WorldGuard.disable(WorldGuard.java:182) ~[?:?]
at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:231) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[server.jar:git-Paper-342]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[server.jar:git-Paper-342]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[server.jar:git-Paper-342]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[server.jar:git-Paper-342]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[server.jar:git-Paper-342]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[server.jar:git-Paper-342]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[server.jar:git-Paper-342]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[server.jar:git-Paper-342]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[server.jar:git-Paper-342]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311) ~[server.jar:git-Paper-342]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[server.jar:git-Paper-342]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`

**How to replicate**:

**Comment by N0tMyFaultOG** [comment]
Try updating your fawe and WorldGuard:
WorldGuard: https://ci.athion.net/job/FAWE-WorldGuard-1.13/lastSuccessfulBuild/artifact/worldguard-legacy/build/libs/worldguard-legacy-7.0.0-SNAPSHOT-dist.jar
Fawe: https://ci.athion.net/job/FAWE-1.13/lastSuccessfulBuild/artifact/target/FastAsyncWorldEdit-bukkit-18.10.04-75c111e-2053.jar
Also, if we ask for a debugpaste, it's enough if you drop the hastebin link you get while using the command, you don't have to post it in :)

**Comment by Thund3rst0rm89** [comment]
okey thank you i try it again, but i use it the first time an so i think every plugin is the newest version.
Thank you for your fast answer
