### ISSUE TITLE
`ClipboardFormat` incompatible with the WorldEdit API

### ISSUE THREAD

**Issue by NLthijs48** [boy0001/FastAsyncWorldedit#1167]
# Bug report

**Debug paste link**: https://hastebin.com/kumuvijiho

**Description of the problem:**

FAWE declares `ClipboardFormat` [as an enum](https://github.com/boy0001/FastAsyncWorldedit/blob/be9f606027f07b36b958b5e41ecfa55bcc5f549c/core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormat.java), while it is an [interface in WorldEdit  ](https://github.com/sk89q/WorldEdit/blob/9494c4445a6ba2332d41a00ddde66cec1dd93941/worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormat.java). This means that plugins that use the WorldEdit api to save/paste schematic files cannot use ClipboardFormat as intended. 

AreaShop uses `ClipboardFormats` and `ClipboardFomat` to find an available schematic format, but that fails when FAWE is installed. See [this link ](https://github.com/NLthijs48/AreaShop/blob/master/WorldEdit%207/src/main/java/me/wiefferink/areashop/handlers/WorldEditHandler7.java#L158-L168)for the code AreaShop uses, which fails with the exception below:

```
[22:54:04 WARN]: [AreaShop] org.bukkit.command.CommandException: Unhandled exception executing command 'areashop' in plugin AreaShop v2.5.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699)
	at me.wiefferink.areashop.regions.GeneralRegion.runCommands(GeneralRegion.java:1437)
	at me.wiefferink.areashop.features.signs.RegionSign.runSignCommands(RegionSign.java:231)
	at me.wiefferink.areashop.features.signs.SignsFeature.onSignClick(SignsFeature.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:240)
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:452)
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1242)
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat, but interface was expected
	at me.wiefferink.areashop.handlers.WorldEditHandler7.saveRegionBlocks(WorldEditHandler7.java:167)
	at me.wiefferink.areashop.regions.GeneralRegion.saveRegionBlocks(GeneralRegion.java:752)
	at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1404)
	at me.wiefferink.areashop.regions.RentRegion.rent(RentRegion.java:591)
	at me.wiefferink.areashop.commands.RentCommand.execute(RentCommand.java:42)
	at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:142)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	... 27 more
```

**How to replicate**:

1. Install FAWE
1. Install WorldGuard
1. Install Vault
1. Install an economy plugin
1. Install AreaShop (2.5.0 or higher)
1. In `/plugins/AreaShop/default.yml` set `enableRestore` to `true`.
1. Select an area using WorldEdit
1. Use `/rg define test`
1. Use `/as add buy test`
1. Use `/as buy test`
1. AreaShop will now try to save a schematic, which fails with the exception shown above.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

It would be great if this compatibility issue could be fixed, I know FAWE is really important for a lot of servers, and currently the combination with AreaShop does not work. If you are are open to it I could also look into creating a pull request.

I'm also open to discussing this further on Discord, I'm NLThijs48#7285 and joined your Discord.

**Comment by boy0001** [comment]
it's an enum just like in previous versions of worldedit:
https://github.com/sk89q/WorldEdit/blob/forge-archive/1.11.2/worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormat.java

If you are supporting older WE versions, the same code you have there should work.

**Comment by NLthijs48** [comment]
Aha that makes sense. I see now that in WorldEdit 7 they refactored the original `ClipboardFormat` into two classes, `ClipboardFormats` that is a registry and `ClipboardFormat` that represents a single format.

Do you intend to be api-compatible with WorldEdit? Because in that case it would make sense to migrate it in FAWE like WorldEdit did. 

Otherwise I would have to write some reflection code to test support for both options, or make a separate integration for FAWE next to the WorldEdit 5, 6 and 7 integrations. 

If I go the route of a separate FAWE integration, what is the recommended way to check if FAWE is running? Because it is using the WorldEdit name internally the usual check would not work, probably best to test if the `com.boydti.fawe.Fawe` class is available right?
```java
boolean fawe = false;
try {
	Class.forName("com.boydti.fawe.Fawe" );
	fawe = true;
} catch (ClassNotFoundException ignore) {}
```

Of course it would be the easiest for me if I could use the existing WorldEdit 7 integration that I have, but the road we take with this issue depends on what your goal is regards to api compatibility with vanilla WorldEdit.

I'm also open to discussing this on Discord a bit, let me know what you think is the best way forward.

**Comment by TheoRetisch1** [comment]
I am very interested in a solution of this problem and therefore in the creation of a compatibility. Both FAWE and AreaShop provide essential plugins and the incompatibility prevents an update to 1.13.2.  So how is it going?
