### ISSUE TITLE
A Little Error with Spigot 1.13.2 - TabCompletation

### ISSUE THREAD

**Issue by CloudeLecaw** [boy0001/FastAsyncWorldedit#1169]
```
[16:17:36] [Server thread/ERROR]: Could not pass event TabCompleteEvent to WorldEdit vunspecified
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at org.bukkit.craftbukkit.v1_13_R2.command.ConsoleCommandCompleter$1.evaluate(ConsoleCommandCompleter.java:28) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at org.bukkit.craftbukkit.v1_13_R2.command.ConsoleCommandCompleter$1.evaluate(ConsoleCommandCompleter.java:1) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at org.bukkit.craftbukkit.v1_13_R2.util.Waitable.run(Waitable.java:24) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:913) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.server.TabCompleteEvent.isCommand()Z
	at com.boydti.fawe.bukkit.listener.SyncTabCompleteListener.onTabComplete(SyncTabCompleteListener.java:16) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-b4230a9]
	... 11 more
```

**Comment by N0tMyFaultOG** [comment]
https://github.com/boy0001/WorldEdit/pull/16 will fix it

**Comment by CloudeLecaw** [comment]
Used Version: FastAsyncWorldEdit-bukkit-18.10.19-0c4adb3-2068 - that is marked on Jenkins as Build 98...

**Comment by N0tMyFaultOG** [comment]
I referred this issue to a PR that will fix it once it's merged.
