### ISSUE TITLE
/anvil deleteallunclaimed 315600000 - console error

### ISSUE THREAD

**Issue by FrozenBeard** [boy0001/FastAsyncWorldedit#1179]
We use WorldGuard and GriefPrevention as land claim management, I am testing the server upgrade to 1.13.2 and am wanting to test the deleteallunclaimed feature to re-generate all those unused chunks for the new terrain in 1.13! I think this error may be due to the new updated 1.13 version of GriefPrevention.

This server is running Paper version git-Paper-409 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Latest FAWE, some reason when I do /ver FastAsyncWorldEdit it outputs version 1.0
GriefPrevention version 16.11.4
WorldGuard version 7.0.0-SNAPSHOT;0dc5781 (the FAWE version)

```
[17:33:17 INFO]: GodsDead issued server command: //anvil deleteallunclaimed 315600000
[17:33:17 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.ClassNotFoundException: com.intellectualcrafters.plot.object.RunnableVal
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-409]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-409]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        at com.boydti.fawe.bukkit.regions.GriefPreventionFeature.getFilter(GriefPreventionFeature.java:59) ~[?:?]
        at com.boydti.fawe.jnbt.anvil.filters.DeleteUnclaimedFilter.<init>(DeleteUnclaimedFilter.java:19) ~[?:?]
        at com.boydti.fawe.command.AnvilCommands.deleteAllUnclaimed(AnvilCommands.java:225) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[?:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[?:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:328) ~[?:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by N0tMyFaultOG** [comment]
Please attach a `/fawe debugpaste`.

**Comment by ArtNRG** [comment]
@N0tMyFaultOG I have the same issue. 

Fawe debugpaste: https://hastebin.com/gazevaseve

**Comment by N0tMyFaultOG** [comment]
Ah anvil, now I got it.
See #1079 -> "Differential logging of anvil" (6th from top)
Anvil is not supported atm, at least not properly.

**Comment by FrozenBeard** [comment]
AHH noo! This is the main extra feature that will aid in the new terrain gen!
