### ISSUE TITLE
Undo not working

### ISSUE THREAD

**Issue by ChristyGrnKnght** [boy0001/FastAsyncWorldedit#1180]
# Bug report

**Debug paste link**:
https://hastebin.com/osabidutah

**Description of the problem:**
I get the following message in my console when I try to do an undo command. This happens when I am standing right next to the place where I have just used a //set white_wool command and am trying to undo it. (It happens regardless of what I'm trying to undo, but this example is from setting white_wool.) 

I had this problem when my server was running 1.13.1. I updated to 1.13.2 and had the exact same problem.

[04-11-2018 14:50:42] An unexpected error occurred while handling a FAWE command
[04-11-2018 14:50:42] java.lang.ArrayIndexOutOfBoundsException: 1023
[04-11-2018 14:50:42] at com.sk89q.worldedit.world.block.BlockTypes.getFromStateId(BlockTypes.java:1111) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.boydti.fawe.example.IntFaweChunk.setBlock(IntFaweChunk.java:205) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.boydti.fawe.example.MappedFaweQueue.setBlock(MappedFaweQueue.java:163) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.boydti.fawe.object.change.MutableBlockChange.create(MutableBlockChange.java:42) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.boydti.fawe.object.change.MutableBlockChange.undo(MutableBlockChange.java:29) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.function.operation.ChangeSetExecutor.resume(ChangeSetExecutor.java:71) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:68) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1168) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:516) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.command.HistoryCommands.lambda$undo$0(HistoryCommands.java:233) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.boydti.fawe.object.FawePlayer.checkConfirmation(FawePlayer.java:192) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:228) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
[04-11-2018 14:50:42] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
[04-11-2018 14:50:42] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
[04-11-2018 14:50:42] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
[04-11-2018 14:50:42] at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:328) ~[FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit-18.10.26-94d5028-2069.jar:?]
[04-11-2018 14:50:42] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) [custom.jar:git-Spigot-2474d93-e693496]
[04-11-2018 14:50:42] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [custom.jar:git-Spigot-2474d93-e693496]
[04-11-2018 14:50:42] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
[04-11-2018 14:50:42] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
[04-11-2018 14:50:42] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[04-11-2018 14:50:43] java.lang.ArrayIndexOutOfBoundsException: 1023
[04-11-2018 14:50:43] at com.sk89q.worldedit.world.block.BlockTypes.getFromStateId(BlockTypes.java:1111)
[04-11-2018 14:50:43] at com.boydti.fawe.bukkit.v0.BukkitChunk_All.call(BukkitChunk_All.java:280)
[04-11-2018 14:50:43] at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:138)
[04-11-2018 14:50:43] at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:211)
[04-11-2018 14:50:43] at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
[04-11-2018 14:50:43] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76)
[04-11-2018 14:50:43] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[04-11-2018 14:50:43] at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)
[04-11-2018 14:50:43] at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[04-11-2018 14:50:43] at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[04-11-2018 14:50:43] at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[04-11-2018 14:50:43] at java.lang.Thread.run(Thread.java:748)

**Checklist**:

- [y] I included a `/fawe debugpaste` link
- [y] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [y] I made sure I am using an up-to-date version of FAWE
- [y] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe, I had no issues undoing my actions.
