### ISSUE TITLE
/schematic save broken / causing errors

### ISSUE THREAD

**Issue by 0Skydive0** [boy0001/FastAsyncWorldedit#1183]
# Bug report

**Debug paste link**:
https://hastebin.com/oyusiwosug

**Description of the problem:**
Using the schematic save command causes errors in server console and in-game.

Server console output:
[20:39:06 INFO]: Sky_Live issued server command: /schematic save mcedit wood-mansion
[20:39:06 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.UnsupportedOperationException: No longer supported.
        at com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat$1.getWriter(ClipboardFormat.java:93) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.getWriter(ClipboardFormat.java:522) ~[?:?]
        at com.sk89q.worldedit.command.SchematicCommands.save(SchematicCommands.java:346) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[?:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[?:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:328) ~[?:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[paperclip.jar:git-Paper-427]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[paperclip.jar:git-Paper-427]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paperclip.jar:git-Paper-427]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**How to replicate**:
I am trying to select a building on one server and save it to a schematic file so I can put the building on a different server.  If I use the wand tool to select the region, then use the command "//copy" and then use the command "/schematic save mcedit wood-mansion" I get a java error in game and several errors shown above on the server console.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
>java.lang.UnsupportedOperationException: No longer supported.

The MCEdit format is currently unsupported, update fawe and use the normal one.

**Comment by heckapoo** [comment]
what does that mean exactly? we have the 1.13 FAWE and get this error?
