### ISSUE TITLE
Typing //stuck without even entering command spams this error

### ISSUE THREAD

**Issue by Chibby96** [boy0001/FastAsyncWorldedit#1207]
# Bug report

**Debug paste link**:

https://hastebin.com/cahabasozo
**Description of the problem:**

```java
[17:56:10 WARN]: java.lang.NullPointerException
[17:56:10 WARN]:        at com.sk89q.minecraft.util.commands.CommandContext.split(CommandContext.java:43)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.command.parametric.StringArgumentStack.<init>(StringArgumentStack.java:62)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.command.parametric.AParametricCallable.getScopedContext(AParametricCallable.java:50)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.command.parametric.AParametricCallable.getSuggestions(AParametricCallable.java:234)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.command.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:174)
[17:56:10 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandSuggestion(CommandManager.java:551)
[17:56:10 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:56:10 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:56:10 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:56:10 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
[17:56:10 WARN]:        at com.boydti.fawe.bukkit.listener.ATabCompleteListener.onTab(ATabCompleteListener.java:33)
[17:56:10 WARN]:        at com.boydti.fawe.bukkit.listener.AsyncTabCompleteListener.onTabComplete(AsyncTabCompleteListener.java:23)
[17:56:10 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor598.execute(Unknown Source)
[17:56:10 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[17:56:10 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[17:56:10 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:56:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[17:56:10 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:44)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:539)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:36)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:9)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:147)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:136)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:358)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:31)
[17:56:10 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[17:56:10 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[17:56:10 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[17:56:10 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
[17:56:10 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[17:56:10 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[17:56:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[17:56:10 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:56:10 WARN]: java.lang.NullPointerException
[17:56:10 WARN]:        at com.sk89q.minecraft.util.commands.CommandContext.split(CommandContext.java:43)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.command.parametric.StringArgumentStack.<init>(StringArgumentStack.java:62)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.command.parametric.AParametricCallable.getScopedContext(AParametricCallable.java:50)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.command.parametric.AParametricCallable.getSuggestions(AParametricCallable.java:234)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.command.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:174)
[17:56:10 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandSuggestion(CommandManager.java:551)
[17:56:10 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:56:10 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:56:10 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:56:10 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
[17:56:10 WARN]:        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
[17:56:10 WARN]:        at com.boydti.fawe.bukkit.listener.ATabCompleteListener.onTab(ATabCompleteListener.java:33)
[17:56:10 WARN]:        at com.boydti.fawe.bukkit.listener.AsyncTabCompleteListener.onTabComplete(AsyncTabCompleteListener.java:23)
[17:56:10 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor598.execute(Unknown Source)
[17:56:10 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[17:56:10 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[17:56:10 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:56:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[17:56:10 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:44)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:539)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:36)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:9)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:147)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:136)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:358)
[17:56:10 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:31)
[17:56:10 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)[17:56:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[17:56:10 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[17:56:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[17:56:10 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[17:56:10 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[17:56:10 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[17:56:10 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
[17:56:10 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[17:56:10 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[17:56:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[17:56:10 WARN]:        at java.lang.Thread.run(Unknown Source)
```
**How to replicate**:

Type //stack
**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/d4971a4e2f2f75cca89952e0e04fb0f61ae53bd0, update fawe
