### ISSUE TITLE
NBT errors spamming console

### ISSUE THREAD

**Issue by DaveDevil** [boy0001/FastAsyncWorldedit#1213]
Having this spamming every second when a player logs in. Actually my log file is about 9'309'995 rows length after 8 hours.

`[12:46:31] [Server thread/WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagInt.e()I
[12:46:31] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:422)
[12:46:31] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410)
[12:46:31] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:66)
[12:46:31] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v0.BukkitQueue_0.toNative(BukkitQueue_0.java:179)
[12:46:31] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.util.ItemUtil.getNBT(ItemUtil.java:71)
[12:46:31] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitItemStack.getNbtData(BukkitItemStack.java:63)
[12:46:31] [Server thread/WARN]: 	at com.boydti.fawe.util.BrushCache.getTool(BrushCache.java:41)
[12:46:31] [Server thread/WARN]: 	at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:961)
[12:46:31] [Server thread/WARN]: 	at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:956)
[12:46:31] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.listener.BrushListener.onPlayerMove(BrushListener.java:73)
[12:46:31] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
[12:46:31] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:46:31] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:46:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[12:46:31] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:46:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[12:46:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[12:46:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:946)
[12:46:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126)
[12:46:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[12:46:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[12:46:31] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:46:31] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:46:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[12:46:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[12:46:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[12:46:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[12:46:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[12:46:31] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
`

FAWE DEBUGPASTE:
`There was an errore handling a FAWE command: [See console]
java.io.IOException: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents`

This server is running CraftBukkit version git-Spigot-e769fe4-068dab5
Using com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2 as the Bukkit adapter

**Comment by TheCalypso** [comment]
I have same error.

**Comment by StealWonders** [comment]
Here is another error better formatted: https://hastebin.com/bodirucati.bash

**Comment by Sakanas** [comment]
same happens with me using paper 1.13.2
https://pastebin.com/eE1XbGvH

**Comment by Daphsquid** [comment]
Just came on here to report this same issue and found that it was reported here already. 

It seems to only happen when players are holding certain items in their inventory and walking around on my server. It seems to be named/lored items, however, I haven't tested this thoroughly. 

Server 1.13.2
Latest FAWE version

**Comment by N0tMyFaultOG** [comment]
Fixed in Fixed in https://github.com/boy0001/WorldEdit/commit/7eac605474a167abe8ac13c991913dff85a53fda
Get the latest builds here https://empcraft.com/fawe/download/?bukkit113
