### ISSUE TITLE
//copy bug

### ISSUE THREAD

**Issue by nepecraft** [boy0001/FastAsyncWorldedit#1256]
[WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagInt.asInt()I
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:422) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.getEntity(Spigot_v1_13_R2.java:317) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitEntity.getState(BukkitEntity.java:84) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.function.operation.ForwardExtentCopy.lambda$resume$2(ForwardExtentCopy.java:355) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_171]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_171]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_171]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_171]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_171]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_171]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_171]
        at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:357) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:68) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.command.ClipboardCommands.lambda$copy$0(ClipboardCommands.java:180) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.boydti.fawe.object.FawePlayer.checkConfirmationRegion(FawePlayer.java:237) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:162) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:328) ~[FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit-1.13.134.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) [falo.jar:git-Spigot-f6a273b-a639ae4]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [falo.jar:git-Spigot-f6a273b-a639ae4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by N0tMyFaultOG** [comment]
Update fawe and spigot.
