### ISSUE TITLE
Error whits undo

### ISSUE THREAD

**Issue by Tyberhertz** [boy0001/FastAsyncWorldedit#1270]
```
[13:12:52] [Craft Scheduler Thread - 114/INFO]: WorldEdit: Tyberherz (in "world-old"): /undo 20
[13:12:52] [Server thread/WARN]: java.lang.UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior
[13:12:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.remove(CraftPlayer.java:1944)
[13:12:52] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v0.BukkitChunk_All.call(BukkitChunk_All.java:161)
[13:12:52] [Server thread/WARN]: 	at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:138)
[13:12:52] [Server thread/WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:211)
[13:12:52] [Server thread/WARN]: 	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
[13:12:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[13:12:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[13:12:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[13:12:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[13:12:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[13:12:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[13:12:52] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:12:53] [Server thread/WARN]: java.lang.UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior
[13:12:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.remove(CraftPlayer.java:1944)
[13:12:53] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v0.BukkitChunk_All.call(BukkitChunk_All.java:161)
[13:12:53] [Server thread/WARN]: 	at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:138)
[13:12:53] [Server thread/WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:211)
[13:12:53] [Server thread/WARN]: 	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
[13:12:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[13:12:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[13:12:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[13:12:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[13:12:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[13:12:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[13:12:53] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:12:54] [Server thread/WARN]: java.lang.UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior
[13:12:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.remove(CraftPlayer.java:1944)
[13:12:54] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v0.BukkitChunk_All.call(BukkitChunk_All.java:161)
[13:12:54] [Server thread/WARN]: 	at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:138)
[13:12:54] [Server thread/WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:211)
[13:12:54] [Server thread/WARN]: 	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
[13:12:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[13:12:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[13:12:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[13:12:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[13:12:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[13:12:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[13:12:54] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:12:55] [Craft Scheduler Thread - 114/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.NullPointerException: null
	at com.sk89q.worldedit.WorldEdit.flushBlockBag(WorldEdit.java:482) ~[?:?]
	at com.sk89q.worldedit.command.HistoryCommands.lambda$undo$0(HistoryCommands.java:248) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.checkConfirmation(FawePlayer.java:192) ~[?:?]
	at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:228) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:328) ~[?:?]
	at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
	at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-521]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-521]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-521]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by N0tMyFaultOG** [comment]
Can you please follow the format given?
