### ISSUE TITLE
FAWE Schematic loading/DebugPaste Error

### ISSUE THREAD

**Issue by NikitaMitrovich** [boy0001/FastAsyncWorldedit#1293]
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**:
https://pastebin.com/8mgS8Axe

https://imgur.com/a/tTsbgIw
 
SchematicLoading:
 
[02:13:44 WARN]: [WorldEdit] Failed to load a saved clipboard
java.util.zip.ZipException: Not in GZIP format
        at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_211]
        at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_211]
        at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_211]
        at com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat$1.getReader(ClipboardFormat.java:88) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.getReader(ClipboardFormat.java:498) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.hold(ClipboardFormat.java:525) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands.load(SchematicCommands.java:266) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:413) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:436) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:417) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:535) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:345) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
 
DebugPaste Error:
 
[02:08:45 INFO]: Paprica_ issued server command: /fawe debugpaste
[02:08:45 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.IllegalStateException: Server returned status: 404 Not Found
        at com.boydti.fawe.util.IncendoPaster.upload(IncendoPaster.java:132) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.boydti.fawe.util.IncendoPaster.debugPaste(IncendoPaster.java:230) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.command.WorldEditCommands.debugpaste(WorldEditCommands.java:191) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:413) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:436) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:417) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:535) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:345) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Checklist**:

- [o] I made sure that I'm using FAWE on 1.12.2 or lower
- [o] I included a `/fawe debugpaste` link
- [o] I made sure there aren't duplicates of this report [(Use Search)]
- [o] I made sure I am using an up-to-date version of [FAWE < 1.12.2]
- [o] I made sure the bug/error is not caused by any other plugin

Description:
I am attempting to load schematics to clipboard.
Issues: When performing "/schem list mine" and files of a folder console returns 16 files available but does not list them.
When attempting to load a schematic from global it also errors out.
There was also an error during "/fawe debugpaste" 

Running on a 1.12.2 server 
Schematics i'm trying to load
[Shcematics i'm trying to load.zip](https://github.com/boy0001/FastAsyncWorldedit/files/3119989/Shcematics.i.m.trying.to.load.zip)

![javaw_2019-04-26_02-09-00](https://user-images.githubusercontent.com/47797412/56787334-2dbe1f00-67ca-11e9-9213-9df8b2204dfb.png)
![javaw_2019-04-26_02-08-08](https://user-images.githubusercontent.com/47797412/56787335-2dbe1f00-67ca-11e9-958a-bb6a766f75a4.png)

**Comment by NikitaMitrovich** [comment]
Follow up:
Tested the schematics with Forge 1.12.2 version.
The schematics load and can be //pasted, so it's not the schematic format.

Also:
I hosted the server on localhost and managed to load schematics into the clipboard. (They were showing up in chat with /schem list mine; as well as, having the [-] Unload)

Could not "// paste"

[02:58:12 INFO]: Paprica_ issued server command: //paste
[02:58:13 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.NullPointerException: null
        at com.sk89q.worldedit.command.ClipboardCommands.place(ClipboardCommands.java:524) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:462) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:413) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:436) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:417) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:535) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:345) ~[FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit-19.04.22-57c85d0-1271-22.0.6.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by NikitaMitrovich** [comment]
I re-built the Spigot server jar and the issue was fixed <3
