### ISSUE TITLE
All builds I can find for forge 1.7.10 are completely broken

### ISSUE THREAD

**Issue by kmecpp** [boy0001/FastAsyncWorldedit#1300]
Tested this on every single FAWE version I could find for Forge 1.7.10. The latest stuff on the jenkins doesn't include it in the zip anymore.

Running a Thermos server on 1.7.10 with only the world edit plugin. FAWE Forge and WEForge is installed in the mods folder and WE bukkit is in the plugins folder.

Tested on:
- FastAsyncWorldEdit-forge1710-19.01.12-dc2d277-1245-22.0.7
- FastAsyncWorldEdit-forge1710-18.11.21-1c17b10-1231-21.5.18
- FastAsyncWorldEdit-forge1710-18.10.05-f3fdef6-1218-21.5.5
- FastAsyncWorldEdit-forge1710-18.08.06-60d07b5-1170-20.7.4
...and probably more

**Debug paste link**:
https://hastebin.com/ogazeqahap

**Description of the problem:**
When I have certain mods installed FAWE just completely freaks when trying perform basic tasks. For example if I have ExtraUtilities installed and I do //cut then some of the blocks will be cut but a ton of blocks will turn into angel blocks like rubber logs from MFR or thermal evaporation blocks from Mekanism and those were just the first two that I tested.

This happens with a ton of other mods too though. If I have open computers installed then //cut will just turn all Mekanism ores and Thermal Expansion or Voltz Engine ores will turn into some random OpenComputers block

And If i have Nuclear Physics installed then doing //cut will turn its own uranium ore blocks into steam funnels.

![image](https://user-images.githubusercontent.com/6520738/57805262-92fe9380-772a-11e9-89c9-92b12d97e147.png)
![image](https://user-images.githubusercontent.com/6520738/57805375-c17c6e80-772a-11e9-93a3-34003041bb06.png)

I then did //undo it didn't change the blocks at all. Then I did //redo and they got changed to cobble stone. Then I did //undo and they disappeared.

This is just one example of how FAWE freaks out with this issue. Sometimes it turns blocks into flowers when I do //undo sometimes it doesn't work at all. The point is FAWE just completely screws up what the blocks are and then the result is repairable if it goes wrong. I tried all the other mods were the issue wasn't occurring and tall other mods and the issue still occurs 

When the issue is occurring there is absolutely nothing logged to the console besides just the normal commands and it appears to be behaving normally. Sometimes when I stop the server I notice this error which could be related.

```
[16:15:44] [Server thread/INFO] [com.sk89q.worldedit.bukkit.WorldEditPlugin/]: [WorldEdit] Disabling WorldEdit v6.1.9;caf0ad9
[16:15:44] [Server thread/ERROR] [com.boydti.fawe/]: &8(&4&lFAWE&8)&r&7 ====== INVALID CLIPBOARD ======
[16:15:44] [Server thread/WARN] [/]: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
[16:15:44] [Server thread/WARN] [/]: 	at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:190)
[16:15:44] [Server thread/WARN] [/]: 	at com.sk89q.worldedit.extension.platform.PlatformManager.getConfiguration(PlatformManager.java:305)
[16:15:44] [Server thread/WARN] [/]: 	at com.sk89q.worldedit.WorldEdit.getConfiguration(WorldEdit.java:801)
[16:15:44] [Server thread/WARN] [/]: 	at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:184)
[16:15:44] [Server thread/WARN] [/]: 	at com.sk89q.worldedit.WorldEdit.getSession(WorldEdit.java:210)
[16:15:44] [Server thread/WARN] [/]: 	at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:546)
[16:15:44] [Server thread/WARN] [/]: 	at com.boydti.fawe.object.FawePlayer.loadClipboardFromDisk(FawePlayer.java:365)
[16:15:44] [Server thread/WARN] [/]: 	at com.boydti.fawe.object.FawePlayer.<init>(FawePlayer.java:128)
[16:15:44] [Server thread/WARN] [/]: 	at com.boydti.fawe.forge.ForgePlayer.<init>(ForgePlayer.java:19)
[16:15:44] [Server thread/WARN] [/]: 	at com.boydti.fawe.forge.FaweForge.wrap(FaweForge.java:117)
[16:15:44] [Server thread/WARN] [/]: 	at com.boydti.fawe.object.FawePlayer.wrap(FawePlayer.java:120)
[16:15:44] [Server thread/WARN] [/]: 	at com.boydti.fawe.forge.ForgeMain.handleQuit(ForgeMain.java:62)
[16:15:44] [Server thread/WARN] [/]: 	at com.boydti.fawe.forge.ForgeMain.onPlayerQuit(ForgeMain.java:51)
[16:15:44] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_108_ForgeMain_onPlayerQuit_PlayerLoggedOutEvent.invoke(.dynamic)
[16:15:44] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[16:15:44] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[16:15:44] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:581)
[16:15:44] [Server thread/WARN] [/]: 	at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:445)
[16:15:44] [Server thread/WARN] [/]: 	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:953)
[16:15:44] [Server thread/WARN] [/]: 	at net.minecraft.network.NetHandlerPlayServer.func_147360_c(NetHandlerPlayServer.java:289)
[16:15:44] [Server thread/WARN] [/]: 	at net.minecraft.server.management.ServerConfigurationManager.func_72392_r(ServerConfigurationManager.java:1688)
[16:15:44] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:627)
[16:15:44] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:827)
[16:15:44] [Server thread/WARN] [/]: 	at java.lang.Thread.run(Unknown Source)
[16:15:44] [Server thread/ERROR] [com.boydti.fawe/]: &8(&4&lFAWE&8)&r&7 ===============---=============
[16:15:44] [Server thread/ERROR] [com.boydti.fawe/]: &8(&4&lFAWE&8)&r&7 This shouldn't result in any failure
[16:15:44] [Server thread/ERROR] [com.boydti.fawe/]: &8(&4&lFAWE&8)&r&7 File: c5261899-1145-4a6a-b0ad-9114c0d0a5b1.bd (len:194)
[16:15:44] [Server thread/ERROR] [com.boydti.fawe/]: &8(&4&lFAWE&8)&r&7 ===============---=============
```

I'm not sure where the .bd file can be found

**How to replicate**:
Setup a thermos server with FAWE and some of the mods that I described and then do //cut with any of the scenarios I just described. //set 0 does the same thing

I can provide a working Thermos build if needed.

**Checklist**:
- [x] I made sure that I'm using FAWE on 1.12.2 or lower
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by kmecpp** [comment]
I can put a $30 bounty on this bug for whoever fixes it

**Comment by N0tMyFaultOG** [comment]
Thermos is no longer officially supported, so it has been removed from the jenkins for newer builds. You might can find a legacy build, but support for it has ended. Since the module is open source, people who want to see support for it can raise pull requests and we will accept them.
