### ISSUE TITLE
Schem Save bug

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#133]
```
[22:41:13 INFO]: L4BORG issued server command: //schem save mcedit aispawn
[22:41:13 WARN]: java.lang.ArrayIndexOutOfBoundsException: 36864
[22:41:13 WARN]:        at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.getBlock(DiskOptimizedClipboard.java:278)
[22:41:13 WARN]:        at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.getBlock(BlockArrayClipboard.java:167)
[22:41:13 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicWriter.write(SchematicWriter.java:120)
[22:41:13 WARN]:        at com.sk89q.worldedit.command.SchematicCommands.save(SchematicCommands.java:177)
[22:41:13 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:41:13 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:41:13 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:41:13 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[22:41:13 WARN]:        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243)
[22:41:13 WARN]:        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[22:41:13 WARN]:        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[22:41:13 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:255)
[22:41:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[22:41:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:41:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:41:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:41:13 WARN]:        at java.lang.Thread.run(Thread.java:745)
[22:41:13 WARN]: java.lang.ArrayIndexOutOfBoundsException: 36864
[22:41:13 WARN]:        at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.getBlock(DiskOptimizedClipboard.java:278)
[22:41:13 WARN]:        at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.getBlock(BlockArrayClipboard.java:167)
[22:41:13 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicWriter.write(SchematicWriter.java:120)
[22:41:13 WARN]:        at com.sk89q.worldedit.command.SchematicCommands.save(SchematicCommands.java:177)
[22:41:13 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:41:13 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:41:13 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:41:13 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[22:41:13 WARN]:        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243)
[22:41:13 WARN]:        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[22:41:13 WARN]:        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[22:41:13 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:255)
[22:41:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[22:41:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:41:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:41:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:41:13 WARN]:        at java.lang.Thread.run(Thread.java:745)
[22:41:13 WARN]: java.lang.ArrayIndexOutOfBoundsException
[22:41:13 WARN]: java.lang.ArrayIndexOutOfBoundsException
[22:41:13 INFO]: [WorldEdit] L4BORG saved /home/minecraft/prison/plugins/WorldEdit/schematics/aispawn.schematic
```

Any idea what went wrong? o.0

**Comment by L4BORG** [comment]
Config:

```
DOCUMENTATION: https://github.com/boy0001/FastAsyncWorldedit/wiki/Configuration
limits:
  default:
    max-changes: 50000000
    max-checks: 50000000
    max-iterations: 1000
    max-entities: 1337
    max-fails: 50000000
    max-blockstates: 1337
region-restrictions: false
max-memory-percent: 95
history:
  use-disk: false
  compress: false
  enable-for-console: true
  chunk-wait-ms: 100
  combine-stages: false
  delete-after-days: 7
  delete-on-logout: true
queue:
  target-size: 64
  parallel-threads: 8
  progress:
    interval: 1
    display: false
  max-wait-ms: 1000
  extra-time-ms: 0
extent:
  allowed-plugins: []
  debug: false
crash-mitigation: true
tick-limiter:
  physics: 500000
  items: 50000
clipboard:
  delete-after-days: 1
  use-disk: true
lighting:
  async: true
  fix-all: true
metrics: false
```

[22:44:56 INFO]: This server is running CraftBukkit version git-TacoSpigot-"a4a61e1" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Comment by dordsor21** [comment]
#193

**Comment by boy0001** [comment]
Fixed
