### ISSUE TITLE
fawe no work

### ISSUE THREAD

**Issue by uniqueusernamelol** [boy0001/FastAsyncWorldedit#1335]
can u ghelp
[ERROR] [WorldEdit] An unexpected error occurred while handling a FAWE command

java.lang.NoSuchMethodError: com.sk89q.minecraft.util.commands.CommandContext.<init>([Ljava/lang/String;Ljava/util/Set;ZLcom/sk89q/minecraft/util/commands/CommandLocals;)V

at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:211) ~[FastAsyncWorldEdit-bukkit-19.07.25-58243b6-1278-22.3.1.jar:?]

at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-bukkit-19.07.25-58243b6-1278-22.3.1.jar:?]

at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:413) ~[FastAsyncWorldEdit-bukkit-19.07.25-58243b6-1278-22.3.1.jar:?]

at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:436) ~[FastAsyncWorldEdit-bukkit-19.07.25-58243b6-1278-22.3.1.jar:?]

at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:417) ~[FastAsyncWorldEdit-bukkit-19.07.25-58243b6-1278-22.3.1.jar:?]

at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:535) ~[FastAsyncWorldEdit-bukkit-19.07.25-58243b6-1278-22.3.1.jar:?]

at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:345) ~[FastAsyncWorldEdit-bukkit-19.07.25-58243b6-1278-22.3.1.jar:?]

at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit-19.07.25-58243b6-1278-22.3.1.jar:?]

at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit-19.07.25-58243b6-1278-22.3.1.jar:?]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by N0tMyFaultOG** [comment]
If you need support, visit our discord  https://discord.gg/ngZCzbU.
