### ISSUE TITLE
Crash when doing WE actions containing hoppers

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#151]
Over the last weeks I had crashes from time to time, always related to hopper ticks.

```
[16:59:02] [Server thread/INFO]: Olaf issued server command: //undo
[16:59:04] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Ticking block entity
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:797) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:444) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:378) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:193) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:177) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        ... 4 more
[16:59:04] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:444) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:378) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:193) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:177) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[16:59:04] [Server thread/ERROR]: This crash report has been saved to: /home/mc/ramdisk/./crash-reports/crash-2016-06-12_16.59.04-server.txt
```

The first few lines of the crash report:
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/12/16 4:59 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:444)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:378)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:193)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:177)
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488)
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:444)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:378)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:193)
        at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:177)

-- Block entity being ticked --
Details:
        Name: Hopper // net.minecraft.server.v1_8_R3.TileEntityHopper
        Block type: ID #0 (tile.air // net.minecraft.server.v1_8_R3.BlockAir)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-3473,145,5755), Chunk: (at 15,9,11 in -218,359; contains blocks -3488,0,5744 to -3473,255,5759), Region: (-7,11; contains chunks -224,352 to -193,383, blocks -3584,0,5632 to -3073,255,6143)
        Actual block type: ID #0 (tile.air // net.minecraft.server.v1_8_R3.BlockAir)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488)
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)
```
The description coordinates match the area where I did WE actions including hoppers. If you want the rest of the file including the stack trace, let me know but be warned, crash-report files have no proper formatting so reading is kind a pain in the butt.

A team mate told me at another crash the WE action included some furnaces, so they MAY be affected as well.

WE 6.1.2;b3fb38b
FAWE 3.5.1-7bc7f58
Spigot 1.8.8

**Comment by boy0001** [comment]
Fixed
