### ISSUE TITLE
error with spigot 1.9

### ISSUE THREAD

**Issue by lasercar** [boy0001/FastAsyncWorldedit#16]
![screen shot 2016-04-01 at 7 19 01 pm](https://cloud.githubusercontent.com/assets/6022168/14223040/c859e28c-f83e-11e5-8919-27a642f0c182.png)

```
[00:15:47] [Server thread/INFO]: Lasercar7 issued server command: //set glass
[00:15:47] [Server thread/INFO]: [FastAsyncWorldEdit] §cPotentially inefficient WorldEdit extent: net.coreprotect.worldedit.CoreProtectLogger
[00:15:47] [Server thread/INFO]: [FastAsyncWorldEdit] §8 - §7For area restrictions, it is recommended to use the FaweAPI
[00:15:47] [Server thread/INFO]: [FastAsyncWorldEdit] §8 - §7Ignore this if not an area restriction
[00:15:47] [Server thread/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.AbstractMethodError: com.sk89q.worldedit.function.visitor.RegionVisitor.addStatusMessages(Ljava/util/List;)V
	at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:87) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:46) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.command.composition.LegacyCommandAdapter.call(LegacyCommandAdapter.java:52) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:270) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at sun.reflect.GeneratedMethodAccessor189.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
```

The error only happens if fawe is installed.

**Comment by RoboMWM** [comment]
WorldEdit version?

**Comment by boy0001** [comment]
This should have been fixed, try updating FAWE.

**Comment by lasercar** [comment]
Yes, It's fixed. Thanks
