### ISSUE TITLE
ArrayOutOfBounds

### ISSUE THREAD

**Issue by UltraX3** [boy0001/FastAsyncWorldedit#164]
### Stacktrace:
```
java.lang.ArrayIndexOutOfBoundsException: 15
        at com.boydti.fawe.object.clipboard.MemoryOptimizedClipboard.setBlock(MemoryOptimizedClipboard.java:286) ~[FastAsyncWorldEdit-bukkit18-3.5.0-0bc703e.jar:?]
        at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.setBlock(BlockArrayClipboard.java:196) ~[FastAsyncWorldEdit-bukkit18-3.5.0-0bc703e.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:222) [FastAsyncWorldEdit-bukkit18-3.5.0-0bc703e.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:75) [FastAsyncWorldEdit-bukkit18-3.5.0-0bc703e.jar:?]
        at com.oneshotmc.schematicshop.object.handlers.SchemHandler.loadSchematic(SchemHandler.java:378) [SchematicShop.jar:?]
        at com.oneshotmc.schematicshop.object.handlers.SchemHandler.onClickEvent(SchemHandler.java:87) [SchematicShop.jar:?]
        at com.oneshotmc.schematicshop.object.SchematicGUI.onInventoryClick(SchematicGUI.java:224) [SchematicShop.jar:?]
        at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) [custom.jar:git-PaperSpigot-unknown]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [custom.jar:git-PaperSpigot-unknown]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [custom.jar:git-PaperSpigot-unknown]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [custom.jar:git-PaperSpigot-unknown]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [custom.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [custom.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [custom.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [custom.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-PaperSpigot-unknown]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [custom.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [custom.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [custom.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [custom.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [custom.jar:git-PaperSpigot-unknown]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

### Version:
I am still experiencing this issue on version 3.5.0-00c685c with WorldEdit version 6.1.3-SNAPSHOT;3563-f689d53 on 1.8.8 PaperSpigot.

### Configuration:
```
max-volume: 50000000
max-memory-percent: 95
command-blacklist:
- cs
- .s
- restore
- snapshot
- delchunks
- listchunks
command-processor: false
max-entities: 1337
max-iterations: 1000
fix-all-lighting: true
require-selection-in-mask: false
max-blockstates: 1337
crash-mitigation: true
limits:
  default:
    max-changes: 50000000
    max-checks: 50000000
    max-iterations: 1000
    max-entities: 1337
    max-fails: 50000000
    max-blockstates: 1337
region-restrictions: true
clipboard:
  delete-after-days: 1
  use-disk: false
lighting:
  async: true
  fix-all: true
history:
  use-disk: false
  chunk-wait-ms: 100
  compress: false
  delete-after-days: 7
  combine-stages: false
  delete-on-logout: true
tick-limiter:
  items: 1337
  physics: 500000
queue:
  max-wait-ms: 1000
  target-size: 64
  parallel-threads: 1
  extra-time-ms: 0
  progress:
    display: false
    interval: 1
extent:
  allowed-plugins:
  - BlockLimit
  - SchematicShop
  debug: true
metrics: true
DOCUMENTATION: https://github.com/boy0001/FastAsyncWorldedit/wiki/Configuration
```

**Comment by boy0001** [comment]
Using an old version
