### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by ajfreed00** [boy0001/FastAsyncWorldedit#176]
Every time I try to load FastAsyncWorldEdit-bukkit18-3.5.1-f202a56.jar on Spigot 1.8.8, I get this error:
'[08:37:32 WARN]: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
[08:37:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162)
[08:37:32 WARN]:        at org.inventivetalent.pluginloader.CommandHandler.onCommand(CommandHandler.java:263)
[08:37:32 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:37:32 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:37:32 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[08:37:32 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[08:37:32 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[08:37:32 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[08:37:32 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[08:37:32 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[08:37:32 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[08:37:32 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[08:37:32 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[08:37:32 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[08:37:32 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[08:37:32 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:37:32 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:37:32 WARN]:        at java.lang.Thread.run(Thread.java:745)
[08:37:32 WARN]: Caused by: java.util.zip.ZipException: error in opening zip file
[08:37:32 WARN]:        at java.util.zip.ZipFile.open(Native Method)
[08:37:32 WARN]:        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
[08:37:32 WARN]:        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
[08:37:32 WARN]:        at java.util.jar.JarFile.<init>(JarFile.java:154)
[08:37:32 WARN]:        at java.util.jar.JarFile.<init>(JarFile.java:118)
[08:37:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150)
[08:37:32 WARN]:        ... 17 more'

I've tried ALL TYPES of fixes, but I MUST be doing something wrong. Can someone please help me ASAP? It would be greatly appreciated. :)

**Comment by Janmm14** [comment]
Did you tried a redownload?
The jar file seems to be corrupt:
`java.util.zip.ZipException: error in opening zip file`

**Comment by ajfreed00** [comment]
Yes, I've tried even downloading it on a different machine and then
transferring it to the server over USB, and I've downloaded it directly on
the machine at least 7 times with different methods. I'm running Ubuntu
Server BTW.

On Fri, Jul 1, 2016 at 11:37 AM, Janmm14 <notifications@github.com> wrote:

> Did you tried a redownload?
> The jar file seems to be corrupt:
> java.util.zip.ZipException: error in opening zip file
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/boy0001/FastAsyncWorldedit/issues/176#issuecomment-229992354>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALrWQLK5jRjxG4Fc1q4SO5xcYIB_g6jlks5qRUJMgaJpZM4JDKDs>
> .
>



-- 
Thanks,
Alexander Freed
ajfreed00@gmail.com

**Comment by Janmm14** [comment]
Tried with an older/newer version (if possible)?

**Comment by ajfreed00** [comment]
I've tried it with an older version and the PLUGIN started up, but regular
worldedit crashes with the older version on it. :/

On Fri, Jul 1, 2016 at 1:35 PM, Janmm14 <notifications@github.com> wrote:

> Tried with an older/newer version (if possible)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/boy0001/FastAsyncWorldedit/issues/176#issuecomment-230018377>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALrWQPRWVfr4W2s9_zpdjgZ_E8bUtZKPks5qRV3rgaJpZM4JDKDs>
> .
>



-- 
Thanks,
Alexander Freed
ajfreed00@gmail.com

**Comment by boy0001** [comment]
Could not replicate
