### ISSUE TITLE
//hsphere broken

### ISSUE THREAD

**Issue by Quicksteve** [boy0001/FastAsyncWorldedit#18]
Hey, just letting you know. With the latest commit on github and possibly before, a few things are broken:

```
[12:58:20 INFO]: Quicksteve issued server command: //hsphere air 70
[12:58:20 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:253) [FastAsyncWorldEdit.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [server.jar:git-Spigot-5f38d38-18fbb24]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at com.boydti.fawe.bukkit.v1_8.BukkitQueue_1_8.getCombinedId4Data(BukkitQueue_1_8.java:276) ~[?:?]
        at com.boydti.fawe.object.HistoryExtent.setBlock(HistoryExtent.java:54) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.boydti.fawe.object.extent.SafeExtentWrapper.setBlock(SafeExtentWrapper.java:24) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:644) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:687) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:705) ~[?:?]
        at com.sk89q.worldedit.EditSession.makeSphere(EditSession.java:1719) ~[?:?]
        at com.sk89q.worldedit.command.GenerationCommands.sphere(GenerationCommands.java:185) ~[?:?]
        at com.sk89q.worldedit.command.GenerationCommands.hsphere(GenerationCommands.java:139) ~[?:?]
        ... 12 more
```
```
[12:58:51 INFO]: Quicksteve issued server command: //hsphere stone 70
[12:58:51 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:253) [FastAsyncWorldEdit.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [server.jar:git-Spigot-5f38d38-18fbb24]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at com.boydti.fawe.bukkit.v1_8.BukkitQueue_1_8.getCombinedId4Data(BukkitQueue_1_8.java:276) ~[?:?]
        at com.boydti.fawe.object.HistoryExtent.setBlock(HistoryExtent.java:54) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.boydti.fawe.object.extent.SafeExtentWrapper.setBlock(SafeExtentWrapper.java:24) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:644) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:687) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:705) ~[?:?]
        at com.sk89q.worldedit.EditSession.makeSphere(EditSession.java:1719) ~[?:?]
        at com.sk89q.worldedit.command.GenerationCommands.sphere(GenerationCommands.java:185) ~[?:?]
        at com.sk89q.worldedit.command.GenerationCommands.hsphere(GenerationCommands.java:139) ~[?:?]
        ... 12 more
[12:58:51 INFO]: [FastAsyncWorldEdit] [FAWE] History compressed. Saved ~ 847b (6x smaller)
```

**Comment by RoboMWM** [comment]
WorldEdit version?

**Comment by boy0001** [comment]
Yeah, I know the issue. It's trying to check a block not in the range 0-256.

**Comment by Quicksteve** [comment]
Using WorldEdit dev build ([219d2da](https://github.com/sk89q/worldedit/commit/219d2da0ff5f24d506f5fc62b6caa920fc8485df)) which is the latest one afaik.

**Comment by boy0001** [comment]
Breaking this into two issues:
https://github.com/boy0001/FastAsyncWorldedit/issues/19
