### ISSUE TITLE
/stream command not working sometimes

### ISSUE THREAD

**Issue by akihirosim** [boy0001/FastAsyncWorldedit#202]
The stream command generates an error

[19:37:01 WARN]: Exception in thread "Craft Scheduler Thread - 27"
[19:37:01 WARN]: org.apache.commons.lang.UnhandledException: Plugin FastAsyncWorldEdit v3.5.1-d562b6c generated an exception while executing task 44
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.boydti.fawe.FaweAPI.streamSchematic(FaweAPI.java:533)
        at com.boydti.fawe.FaweAPI.streamSchematic(FaweAPI.java:482)
        at com.boydti.fawe.command.Stream.execute(Stream.java:33)
        at com.boydti.fawe.object.FaweCommand$2.run(FaweCommand.java:45)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by RoboMWM** [comment]
need /version, and /version fastasyncworldedit output.

**Comment by akihirosim** [comment]
[http://imgur.com/a/gxBCl](url)

**Comment by boy0001** [comment]
Stream command has been removed.
