### ISSUE TITLE
ServerInternalException when pasting a large schematic and undoing it.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#211]
FastAsync dev 184
WorldEdit dev 3596
PaperSpigot (MC 1.10) dev 830

Pasting a large schematic into the world and then undoing it causes these errors to occur. As if corrupting the chunk. The errors still occur when removing FAWE and flying through the affcted chunk the build was pasted and undone in until no more errors occur / world re-saves once the chunks are loaded since the undo.

```
[21:53:08] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_10_R1.TileEntityChest@236c0b48) at -1394,198,8760 (AIR) where there was no entity tile!
Chunk coordinates: -1408,8752
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:782)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:755)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:427)
[21:53:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
[21:53:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
[21:53:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[21:53:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[21:53:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:807)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
[21:53:08] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
[21:53:08] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_10_R1.TileEntityChest@7b515bd3) at -1394,198,8762 (AIR) where there was no entity tile!
Chunk coordinates: -1408,8752
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:782)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:755)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:427)
[21:53:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
[21:53:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
[21:53:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[21:53:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[21:53:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:807)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
[21:53:08] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
[21:53:08] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
```

**Comment by boy0001** [comment]
Please attach the schematic.

**Comment by mibby** [comment]
https://www.dropbox.com/s/lsago4s2nsbfn7i/TestSchematics.zip?dl=0

It is the "final" schematic I used for testing, largest one of the bunch. Simply pasted then undone.

**Comment by boy0001** [comment]
Can't replicate

**Comment by mibby** [comment]
Still able to reproduce this problem as of dev 324. Pasted in a schematic with FAWE, ```/undo```'d the schematic paste, shut down the server, removed FAWE, then started up the server again. Had missing tile entity errors occur when loading the area's chunks. 

FastAsyncWorldEdit dev 324
FastAsyncVoxelSniper dev 324
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 881

Config.
http://paste.ubuntu.com/23244770/

```
[23:46:24] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_10_R1.TileEntityChest@1d89aa1e) at -14690,63,8586 (AIR) where there was no entity tile!
Chunk coordinates: -14704,8576
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:782)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:755)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:425)
[23:46:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[23:46:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[23:46:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[23:46:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[23:46:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:820)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633)
[23:46:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:46:24] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_10_R1.TileEntityChest@2a68f1a0) at -14686,63,8586 (AIR) where there was no entity tile!
Chunk coordinates: -14688,8576
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:782)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:755)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:425)
[23:46:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[23:46:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[23:46:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[23:46:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[23:46:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:820)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734)
[23:46:24] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633)
[23:46:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dordsor21** [comment]
Doesn't seem to be a problem anymore @boy0001
