### ISSUE TITLE
Async Entity track caught

### ISSUE THREAD

**Issue by loveyanbei** [boy0001/FastAsyncWorldedit#226]
3.5.1 dev build
[15:11:58 INFO]: 滴，穴深卡 issued server command: /tp 99999 100 99999
[15:11:58 INFO]: [滴，穴深卡: Teleported 滴，穴深卡 to 99999.5, 100.0, 99999.5]
[15:12:48 INFO]: 滴，穴深卡 issued server command: /GenMaze
[15:13:02 WARN]: Exception in thread "Craft Scheduler Thread - 7" 
[15:13:02 WARN]: org.apache.commons.lang.UnhandledException: Plugin FastAsyncWorldEdit v3.5.1-39acae0 generated an exception while executing task 5390
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Asynchronous entity track!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
	at net.minecraft.server.v1_9_R2.EntityTracker.addEntity(EntityTracker.java:104)
	at net.minecraft.server.v1_9_R2.EntityTracker.track(EntityTracker.java:80)
	at net.minecraft.server.v1_9_R2.WorldManager.a(WorldManager.java:19)
	at net.minecraft.server.v1_9_R2.World.b(World.java:1024)
	at net.minecraft.server.v1_9_R2.WorldServer.b(WorldServer.java:1126)
	at net.minecraft.server.v1_9_R2.WorldServer.a(WorldServer.java:1091)
	at net.minecraft.server.v1_9_R2.Chunk.addEntities(Chunk.java:757)
	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
	at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
	at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
	at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
	at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
	at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:111)
	at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:107)
	at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.getChunkAt(CraftWorld.java:129)
	at com.boydti.fawe.bukkit.v1_9.BukkitChunk_1_9.getNewChunk(BukkitChunk_1_9.java:34)
	at com.boydti.fawe.bukkit.v1_9.BukkitChunk_1_9.getNewChunk(BukkitChunk_1_9.java:17)
	at com.boydti.fawe.example.CharFaweChunk.getChunk(CharFaweChunk.java:46)
	at com.boydti.fawe.example.NMSMappedFaweQueue.sendChunk(NMSMappedFaweQueue.java:69)
	at com.boydti.fawe.example.NMSRelighter.sendChunks(NMSRelighter.java:103)
	at com.boydti.fawe.example.NMSMappedFaweQueue.runTasks(NMSMappedFaweQueue.java:63)
	at com.boydti.fawe.example.MappedFaweQueue.size(MappedFaweQueue.java:321)
	at com.boydti.fawe.object.FaweQueue.flush(FaweQueue.java:340)
	at com.boydti.fawe.object.FaweQueue.flush(FaweQueue.java:333)
	at com.boydti.fawe.bukkit.wrapper.AsyncWorld.flush(AsyncWorld.java:140)
	at com.boydti.fawe.bukkit.wrapper.AsyncWorld.commit(AsyncWorld.java:136)
	at org.dogeop.MazePlugin.Abstract3DMaze.GenBukkitWorld(Abstract3DMaze.java:224)
	at org.dogeop.MazePlugin.MazePlugin$5.run(MazePlugin.java:701)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by boy0001** [comment]
Whoops. Download an older build for the time being.

**Comment by boy0001** [comment]
Should be fixed, please test. I'll reopen if not,
