### ISSUE TITLE
cannot be cast to com.boydti.fawe.bukkit.v1_8.BukkitChunk_1_8

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#227]
```
[00:57:11] [Server thread/WARN]: java.lang.ClassCastException: com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3$2 cannot be cast to com.boydti.fawe.bukkit.v1_8.BukkitChunk_1_8
[00:57:11] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.refreshChunk(BukkitQueue18R3.java:430)
[00:57:11] [Server thread/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue.sendChunk(NMSMappedFaweQueue.java:69)
[00:57:11] [Server thread/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue.execute(NMSMappedFaweQueue.java:24)
[00:57:11] [Server thread/WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:300)
[00:57:11] [Server thread/WARN]: 	at com.boydti.fawe.regions.general.plot.FaweLocalBlockQueue.next(FaweLocalBlockQueue.java:29)
[00:57:11] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:48)
[00:57:11] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:44)
[00:57:11] [Server thread/WARN]: 	at com.intellectualcrafters.plot.object.RunnableVal2.run(RunnableVal2.java:16)
[00:57:11] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$2.run(GlobalBlockQueue.java:109)
[00:57:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[00:57:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[00:57:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[00:57:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[00:57:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[00:57:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[00:57:11] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[00:57:11] [Server thread/WARN]: java.lang.ClassCastException: com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3$2 cannot be cast to com.boydti.fawe.bukkit.v1_8.BukkitChunk_1_8
[00:57:11] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.refreshChunk(BukkitQueue18R3.java:430)
[00:57:11] [Server thread/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue.sendChunk(NMSMappedFaweQueue.java:69)
[00:57:11] [Server thread/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue.execute(NMSMappedFaweQueue.java:24)
[00:57:11] [Server thread/WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:300)
[00:57:11] [Server thread/WARN]: 	at com.boydti.fawe.regions.general.plot.FaweLocalBlockQueue.next(FaweLocalBlockQueue.java:29)
[00:57:11] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:48)
[00:57:11] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:44)
[00:57:11] [Server thread/WARN]: 	at com.intellectualcrafters.plot.object.RunnableVal2.run(RunnableVal2.java:16)
[00:57:11] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$2.run(GlobalBlockQueue.java:109)
[00:57:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[00:57:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[00:57:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[00:57:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[00:57:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[00:57:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[00:57:11] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

Running latest dev FAWE and WE with lastest dev P^2 on latest 1.8.8 TacoSpigot. 

FAWE config: http://pastebin.com/sAJ9h7Qr

**Comment by boy0001** [comment]
Fixed
