### ISSUE TITLE
IllegalStateException on //regen

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#23]
When trying to regen an area I got lots of those exceptions:

```
[21:23:10] [Craft Scheduler Thread - 73/WARN]: [WorldEdit] Chunk generation via Bukkit raised an error
java.lang.IllegalStateException: Asynchronous chunk unload!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.unloadChunk(CraftWorld.java:181) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.regenerateChunk(CraftWorld.java:205) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:176) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3463.jar:?]
        at com.sk89q.worldedit.command.RegionCommands.regenerateChunk(RegionCommands.java:350) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3463.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3463.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3463.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:253) [FastAsyncWorldEdit338.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

Even though it said `Region regenerated` and `[FAWE] Action completed in 0.33 seconds` the regen has not been performed.

Spigot 1.8.8
FAWE 3.3.8
WE build 3463

Config:
```
limits:
  default:
    max-changes: 50000000
    max-checks: 50000000
    max-iterations: 1000
    max-entities: 1337
    max-fails: 50000000
    max-blockstates: 1337
region-restrictions: true
max-memory-percent: 95
command-blacklist:
- cs
- .s
- restore
- snapshot
- delchunks
- listchunks
command-processor: true
history:
  chunk-wait-ms: 0
  compress: true
  use-disk: false
  buffer-size: 531441
crash-mitigation: true
fix-all-lighting: true
metrics: true
require-selection-in-mask: false
```

**Comment by boy0001** [comment]
Okay, I need to replace`//regen` with a custom command.

**Comment by RoboMWM** [comment]
Just an fyi, I've never had success with the //regen command and have relied on other plugins such as [Chunkfixer](http://dev.bukkit.org/bukkit-plugins/chunkfixer/) for //regen'ing chunks (albeit it doesn't do a region-specific regen, it definitely is a lot faster, more performant, and less buggy than WorldEdit's implementation, at least whenever I've tried to use it).

**Comment by boy0001** [comment]
@EvilOlaf 
Latest jar:
ci.athion.net/job/FastAsyncWorldEdit/

> it definitely is a lot faster, more performant, and less buggy than WorldEdit's implementation
@RoboMWM 
FAWE should remedy the performance issues. It's fastest if you have it aligned to the chunk, use `//expand vert`, and have fastmode enabled.

What bugs were you having with regen previously?

**Comment by RoboMWM** [comment]
Generally either hanging the server. When I use AWE it would regen the chunk, then seemingly undo it or something, and can't recall if it led to a hang or not.

But I guess if it's aligned to a chunk it would be doing the same thing chunkfixer does.

**Comment by boy0001** [comment]
@RoboMWM 
It's not exactly the same. If you don't have fastmode enabled, WorldEdit also has to remember the blocks changed for `//undo`
