### ISSUE TITLE
java.lang.reflect.InvocationTargetException on //schem load mcedit ...

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#234]
```
... issued server command: //schem load mcedit mountain
[19:23:49 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:228) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:269) [FastAsyncWorldEdit-bukkit18.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.boydti.fawe.object.clipboard.MemoryOptimizedClipboard.setId(MemoryOptimizedClipboard.java:187) ~[?:?]
        at com.boydti.fawe.jnbt.SchematicStreamer$2.run(SchematicStreamer.java:43) ~[?:?]
        at com.sk89q.jnbt.NBTInputStream.readTagPaylodLazy(NBTInputStream.java:142) ~[?:?]
        at com.sk89q.jnbt.NBTInputStream.readTagPaylodLazy(NBTInputStream.java:181) ~[?:?]
        at com.sk89q.jnbt.NBTInputStream.readNamedTagLazy(NBTInputStream.java:87) ~[?:?]
        at com.boydti.fawe.jnbt.NBTStreamer.readFully(NBTStreamer.java:18) ~[?:?]
        at com.boydti.fawe.jnbt.SchematicStreamer.getClipboard(SchematicStreamer.java:198) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:61) ~[?:?]
        at com.sk89q.worldedit.command.SchematicCommands.load(SchematicCommands.java:127) ~[?:?]
        ... 13 more
```

Using FAWE b#202 (12.8.2016 5:18:04) 

```
[19:28:39 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

[19:28:59 INFO]: WorldEdit version (unknown)
[19:28:59 INFO]: https://github.com/sk89q/worldedit/
[19:28:59 INFO]: ----------- Platforms -----------
[19:28:59 INFO]: * Bukkit-Official (6.1.4-SNAPSHOT;3609-9851099)
[19:28:59 INFO]: ----------- Capabilities -----------
[19:28:59 INFO]: GAME_HOOKS: Bukkit-Official
[19:28:59 INFO]: CONFIGURATION: Bukkit-Official
[19:28:59 INFO]: USER_COMMANDS: Bukkit-Official
[19:28:59 INFO]: PERMISSIONS: Bukkit-Official
[19:28:59 INFO]: WORLDEDIT_CUI: Bukkit-Official
[19:28:59 INFO]: WORLD_EDITING: Bukkit-Official
```

FAWE config: http://pastebin.com/JLCx0A49

**Comment by Janmm14** [comment]
Maybe invalid schematic file?

**Comment by L4BORG** [comment]
It worked before... :(

**Comment by boy0001** [comment]
Please attach the schematic.

**Comment by L4BORG** [comment]
It was thisone..

[mountain.zip](https://github.com/boy0001/FastAsyncWorldedit/files/416795/mountain.zip)

**Comment by boy0001** [comment]
Fixed
