### ISSUE TITLE
java.lang.reflect.InvocationTargetException on //fixlighting

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#235]
```
... issued server command: //fixlighting
[21:15:25 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:228) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:269) [FastAsyncWorldEdit-bukkit18.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.IllegalStateException: Asynchronous entity world add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.World.b(World.java:2737) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:904) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:139) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:121) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:144) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at com.boydti.fawe.bukkit.v1_8.BukkitChunk_1_8.getNewChunk(BukkitChunk_1_8.java:22) ~[?:?]
        at com.boydti.fawe.bukkit.v1_8.BukkitChunk_1_8.getNewChunk(BukkitChunk_1_8.java:8) ~[?:?]
        at com.boydti.fawe.example.CharFaweChunk.getChunk(CharFaweChunk.java:47) ~[?:?]
        at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.refreshChunk(BukkitQueue18R3.java:431) ~[?:?]
        at com.boydti.fawe.example.NMSMappedFaweQueue.sendChunk(NMSMappedFaweQueue.java:69) ~[?:?]
        at com.boydti.fawe.example.NMSRelighter.sendChunks(NMSRelighter.java:114) ~[?:?]
        at com.boydti.fawe.FaweAPI.fixLighting(FaweAPI.java:423) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.fixlighting(RegionCommands.java:113) ~[?:?]
        ... 12 more
```

Using FAWE b#202 (12.8.2016 5:18:04) 

```
[19:28:39 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

[19:28:59 INFO]: WorldEdit version (unknown)
[19:28:59 INFO]: https://github.com/sk89q/worldedit/
[19:28:59 INFO]: ----------- Platforms -----------
[19:28:59 INFO]: * Bukkit-Official (6.1.4-SNAPSHOT;3609-9851099)
[19:28:59 INFO]: ----------- Capabilities -----------
[19:28:59 INFO]: GAME_HOOKS: Bukkit-Official
[19:28:59 INFO]: CONFIGURATION: Bukkit-Official
[19:28:59 INFO]: USER_COMMANDS: Bukkit-Official
[19:28:59 INFO]: PERMISSIONS: Bukkit-Official
[19:28:59 INFO]: WORLDEDIT_CUI: Bukkit-Official
[19:28:59 INFO]: WORLD_EDITING: Bukkit-Official
```

FAWE config: http://pastebin.com/JLCx0A49

**Comment by boy0001** [comment]
Fixed
