### ISSUE TITLE
java.io.FileNotFoundException: plugins/FastAsyncWorldEdit/history/world

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#238]
```
>ver FastAsyncWorldEdit
[18:18:43 INFO]: FastAsyncWorldEdit version 16.08.15-ca12752-211
[18:18:43 INFO]: Fast Async WorldEdit plugin
[18:18:43 INFO]: Author: Empire92
```

```
[18:14:44 WARN]: java.io.FileNotFoundException: plugins/FastAsyncWorldEdit/history/world/595a8e71-1b09-394e-90c4-995010728d32/index (No such file or directory)
[18:14:44 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[18:14:44 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[18:14:44 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[18:14:44 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[18:14:44 WARN]:        at com.sk89q.worldedit.LocalSession.saveHistoryNegativeIndex(LocalSession.java:322)
[18:14:44 WARN]:        at com.sk89q.worldedit.LocalSession.save(LocalSession.java:363)
[18:14:44 WARN]:        at com.sk89q.worldedit.session.SessionManager.save(SessionManager.java:201)
[18:14:44 WARN]:        at com.sk89q.worldedit.session.SessionManager.remove(SessionManager.java:251)
[18:14:44 WARN]:        at com.sk89q.worldedit.WorldEdit.removeSession(WorldEdit.java:218)
[18:14:44 WARN]:        at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:368)
[18:14:44 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:289)
[18:14:44 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:14:44 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:14:44 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:14:44 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[18:14:44 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[18:14:44 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[18:14:44 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:14:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[18:14:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[18:14:44 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:364)
[18:14:44 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:880)
[18:14:44 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314)
[18:14:44 WARN]:        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145)
[18:14:44 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875)
[18:14:44 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[18:14:44 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[18:14:44 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[18:14:44 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

Config: http://pastebin.com/dxKXz4F8

**Comment by mibby** [comment]
@boy0001 Can confirm this error exists on 1.10 as well. Occurred when a player with worldedit disconnected, presumably after use that day.

FastAsyncWorldEdit v3.5.1-3ec4214
WorldEdit dev 3609

```
clipboard:
  use-disk: false
```
```
history:
  use-disk: false
  delete-on-logout: true
```
```
[23:44:05] [Server thread/INFO]: player lost connection: Disconnected
[23:44:05] [Server thread/WARN]: java.io.FileNotFoundException: plugins/FastAsyncWorldEdit/history/world/u-u-i-d/index (No such file or directory)
[23:44:05] [Server thread/WARN]: 	at java.io.FileOutputStream.open0(Native Method)
[23:44:05] [Server thread/WARN]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[23:44:05] [Server thread/WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[23:44:05] [Server thread/WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[23:44:05] [Server thread/WARN]: 	at com.sk89q.worldedit.LocalSession.saveHistoryNegativeIndex(LocalSession.java:261)
[23:44:05] [Server thread/WARN]: 	at com.sk89q.worldedit.LocalSession.save(LocalSession.java:302)
[23:44:05] [Server thread/WARN]: 	at com.sk89q.worldedit.session.SessionManager.save(SessionManager.java:201)
[23:44:05] [Server thread/WARN]: 	at com.sk89q.worldedit.session.SessionManager.remove(SessionManager.java:251)
[23:44:05] [Server thread/WARN]: 	at com.sk89q.worldedit.WorldEdit.removeSession(WorldEdit.java:218)
[23:44:05] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:368)
[23:44:05] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:314)
[23:44:05] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor766.execute(Unknown Source)
[23:44:05] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[23:44:05] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[23:44:05] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:44:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[23:44:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[23:44:05] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerList.disconnect(PlayerList.java:408)
[23:44:05] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1069)
[23:44:05] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.NetworkManager.handleDisconnection(NetworkManager.java:318)
[23:44:05] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:186)
[23:44:05] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:886)
[23:44:05] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[23:44:05] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
[23:44:05] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
[23:44:05] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:44:05] [Server thread/INFO]: [-] ~player has left the server.
```

**Comment by boy0001** [comment]
Was fixed
