### ISSUE TITLE
java.lang.IllegalArgumentException: fromIndex(512) > toIndex(511)

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#269]
**Debug paste link**:
http://hastebin.com/cofalixeto

**Description of the problem:**
```
[22:05:48 WARN]: java.lang.IllegalArgumentException: fromIndex(512) > toIndex(511)
[22:05:48 WARN]:        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1006)
[22:05:48 WARN]:        at java.util.ArrayList.subList(ArrayList.java:996)
[22:05:48 WARN]:        at com.boydti.fawe.example.NMSRelighter.fixSkyLighting(NMSRelighter.java:162)
[22:05:48 WARN]:        at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:80)
[22:05:48 WARN]:        at com.boydti.fawe.example.NMSMappedFaweQueue$1$1.run(NMSMappedFaweQueue.java:34)
[22:05:48 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[22:05:48 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:05:48 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:05:48 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:05:48 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**How to replicate**:
Not sure I think it was caused after usage of //lightning (error popped out after awhile)

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/fawe debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of FAWE
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by L4BORG** [comment]
Console log:

```
[21:59:42 INFO]: Player issued server command: //fixlighting
[21:59:53 INFO]: Player issued server command: //wand
[22:00:05 INFO]: World "world" saved!
[22:03:02 INFO]: Player issued server command: //fillr dirt 500
[22:03:47 INFO]: Player issued server command: //cancel
[22:03:52 INFO]: Player issued server command: //undo
[22:04:56 INFO]: Player issued server command: //fillr dirt 500
[22:05:06 INFO]: World "world" saved!
[22:05:48 WARN]: java.lang.IllegalArgumentException: fromIndex(512) > toIndex(511)
[22:05:48 WARN]:        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1006)
[22:05:48 WARN]:        at java.util.ArrayList.subList(ArrayList.java:996)
[22:05:48 WARN]:        at com.boydti.fawe.example.NMSRelighter.fixSkyLighting(NMSRelighter.java:162)
[22:05:48 WARN]:        at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:80)
[22:05:48 WARN]:        at com.boydti.fawe.example.NMSMappedFaweQueue$1$1.run(NMSMappedFaweQueue.java:34)
[22:05:48 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[22:05:48 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:05:48 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:05:48 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:05:48 WARN]:        at java.lang.Thread.run(Thread.java:745)
>fawe debugpaste
[22:06:52 INFO]: (FAWE) http://hastebin.com/cofalixeto
>
```
