### ISSUE TITLE
java.lang.ClassCastException: com.sk89q.jnbt.ByteArrayTag cannot be cast to com.intellectualcrafters.jnbt.Tag

### ISSUE THREAD

**Issue by MisterErwin** [boy0001/FastAsyncWorldedit#280]
[This insertion](https://github.com/boy0001/FastAsyncWorldedit/blob/c98d07039d09479aec9278c932817f551b7d5364/core/src/main/java/com/boydti/fawe/regions/general/plot/FaweSchematicHandler.java#L107
) (and maybe others) might cause the following exception when using ``:

`
[20:55:16] [Craft Scheduler Thread - 94/WARN]: java.lang.ClassCastException: com.sk89q.jnbt.ByteArrayTag cannot be cast to com.intellectualcrafters.jnbt.Tag
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at com.intellectualcrafters.jnbt.CompoundTag.toString(CompoundTag.java:382)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at java.lang.String.valueOf(Unknown Source)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at java.io.PrintStream.println(Unknown Source)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at net.askarian.mccb.plotmover.commands.ExportCommand$1.run(ExportCommand.java:68)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at net.askarian.mccb.plotmover.commands.ExportCommand$1.run(ExportCommand.java:64)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at com.intellectualcrafters.plot.util.SchematicHandler$4.run(SchematicHandler.java:614)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at com.intellectualcrafters.plot.util.SchematicHandler$4.run(SchematicHandler.java:600)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at com.boydti.fawe.regions.general.plot.FaweSchematicHandler$1.run(FaweSchematicHandler.java:108)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:55:16] [Craft Scheduler Thread - 94/WARN]: 	at java.lang.Thread.run(Unknown Source)
 `

The following snippet causes this to happen:
`
SchematicHandler.manager.getCompoundTag(plot, new RunnableVal<CompoundTag>() {
     public void run(CompoundTag value) {    
          System.out.println(value);
    }
});
`

A similar exception is thrown when using `com.intellectualcrafters.jnbt.NBTOutputStream#writeTag`

Without FAWE this works, so I blame you :)

P.S.: Somehow `/ps download` works (even the writeTag part). But adding the toString part breaks it

**Comment by boy0001** [comment]
Yeah, I'm doing some unsafe casting of the maps there since it's faster. i.e. To convert between the nbt library WorldEdit uses and PlotSquared.

To get the map, use `tag.getValue()`, if FAWE is installed it will be `Map<String, com.sk89q.jnbt.Tag>`.

**Comment by MisterErwin** [comment]
Thanks for the answer :)
I guess as this is kinda "as expected" you can close this, @boy0001
