### ISSUE TITLE
Huge Log file 200 GB

### ISSUE THREAD

**Issue by BiggDaddyy** [boy0001/FastAsyncWorldedit#288]
Hi everytime i make a command that is bigger then a 4 milions blocks its slows down and starts making error code that just go on and on i have a log file one 234 GB right now with the error that i didn't see before it went op there xD and are to big for noteblock to open

[21:33:29] [Craft Scheduler Thread - 8/WARN]: java.lang.ArrayIndexOutOfBoundsException
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.object.io.FastByteArrayOutputStream.write(FastByteArrayOutputStream.java:80)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at java.io.BufferedOutputStream.write(Unknown Source)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at net.jpountz.lz4.LZ4OutputStream.flush(LZ4OutputStream.java:67)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at net.jpountz.lz4.LZ4OutputStream.write(LZ4OutputStream.java:55)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.object.FaweOutputStream.write(FaweOutputStream.java:22)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.object.changeset.FaweStreamChangeSet.add(FaweStreamChangeSet.java:97)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.logging.LoggingChangeSet.add(LoggingChangeSet.java:67)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.object.HistoryExtent.setBlock(HistoryExtent.java:75)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.object.HistoryExtent.setBlock(HistoryExtent.java:98)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:962)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:53)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:58)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:67)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:162)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:62)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.util.command.composition.LegacyCommandAdapter.call(LegacyCommandAdapter.java:52)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:287)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at java.lang.Thread.run(Unknown Source)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: java.lang.ArrayIndexOutOfBoundsException
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.object.io.FastByteArrayOutputStream.write(FastByteArrayOutputStream.java:80)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at java.io.BufferedOutputStream.write(Unknown Source)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at net.jpountz.lz4.LZ4OutputStream.flush(LZ4OutputStream.java:67)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at net.jpountz.lz4.LZ4OutputStream.write(LZ4OutputStream.java:55)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.object.FaweOutputStream.write(FaweOutputStream.java:22)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.object.changeset.FaweStreamChangeSet.add(FaweStreamChangeSet.java:97)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.logging.LoggingChangeSet.add(LoggingChangeSet.java:67)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.object.HistoryExtent.setBlock(HistoryExtent.java:75)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.boydti.fawe.object.HistoryExtent.setBlock(HistoryExtent.java:98)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:962)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:53)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:58)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:67)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:162)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:62)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.util.command.composition.LegacyCommandAdapter.call(LegacyCommandAdapter.java:52)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:287)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:33:29] [Craft Scheduler Thread - 8/WARN]: at java.lang.Thread.run(Unknown Source)

spigot 1.10.2

running with bungecord don't know if that can do anything xD

tried placeing 445783968 if never stops 100% and the server never crashes it was just a test to see if the server would stop
![1](https://cloud.githubusercontent.com/assets/20758605/18416839/bc7fbbbe-7820-11e6-9bd4-bc9ce56c7ee4.png)
![2](https://cloud.githubusercontent.com/assets/20758605/18416840/bc932a46-7820-11e6-8693-2c3bd3b23326.png)

**Comment by boy0001** [comment]
I need a `/fawe debugpaste`

**Comment by BiggDaddyy** [comment]
when it was done http://hastebin.com/jayawihote

**Comment by boy0001** [comment]
I couldn't replicate the problem, even with 200,000,000 blocks. Anywho, replaced the affected classes with a completely different implementation which may solve it for you.
