### ISSUE TITLE
NullPointerException - getSkyLight

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#295]
FastAsyncWorldEdit dev 288
WorldEdit dev 3623
Paper dev 865

```
[13:38:01] [Server thread/INFO]: player issued server command: //replace grass snow
[13:38:01] [Craft Scheduler Thread - 119/INFO]: WorldEdit: player (in "world"): /replace grass snow - Region: (-6502.0, 0.0, 1888.0) - (-6157.0, 255.0, 2353.0)
[13:38:04] [Craft Scheduler Thread - 111/WARN]: java.lang.NullPointerException
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.getSkyLight(BukkitQueue_1_10.java:335)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.getSkyLight(BukkitQueue_1_10.java:65)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at com.boydti.fawe.example.MappedFaweQueue.getSkyLight(MappedFaweQueue.java:402)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at com.boydti.fawe.example.NMSRelighter.smoothSkyLight(NMSRelighter.java:284)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at com.boydti.fawe.example.NMSRelighter.fixSkyLighting(NMSRelighter.java:253)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at com.boydti.fawe.example.NMSRelighter.fixSkyLighting(NMSRelighter.java:169)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:83)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at com.boydti.fawe.example.NMSMappedFaweQueue$1$1.run(NMSMappedFaweQueue.java:45)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[13:38:04] [Craft Scheduler Thread - 111/WARN]:     at java.lang.Thread.run(Thread.java:745)
```

**Comment by mibby** [comment]
Still occurring as of

>FastAsyncWorldEdit dev 347
FastAsyncVoxelSniper dev 347
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 889

Config.
http://paste.ubuntu.com/23341264/

```
[15:42:21] [Server thread/INFO]: player issued server command: //replace stone,dirt,grass,gravel,sand,water,lava, df9u8ads9s0fyu
[15:42:21] [Craft Scheduler Thread - 251/INFO]: WorldEdit: player (in "world"): /replace stone,dirt,grass,gravel,sand,water,lava, df9u8ads9s0fyu - Region: (-6460.0, 64.0, 866.0) - (-6171.0, 108.0, 1221.0)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: java.lang.NullPointerException
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.getSkyLight(BukkitQueue_1_10.java:336)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.getSkyLight(BukkitQueue_1_10.java:65)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.getSkyLight(MappedFaweQueue.java:414)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at com.boydti.fawe.example.NMSRelighter.smoothSkyLight(NMSRelighter.java:285)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at com.boydti.fawe.example.NMSRelighter.fixSkyLighting(NMSRelighter.java:254)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at com.boydti.fawe.example.NMSRelighter.fixSkyLighting(NMSRelighter.java:166)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:90)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue$1$1.run(NMSMappedFaweQueue.java:53)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:42:26] [Craft Scheduler Thread - 314/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by boy0001** [comment]
Still an issue?

**Comment by dordsor21** [comment]
Haven't seen this, though using 1.11.2
