### ISSUE TITLE
Server Crash - ticking player

### ISSUE THREAD

**Issue by PhanaticD** [boy0001/FastAsyncWorldedit#304]
with build 293, occurs with parallel threads greater than 1

http://pastebin.com/raw/DZmykru5

**Comment by Sitmobedaf** [comment]
+1

**Comment by EvilOlaf** [comment]
Confirmed

**Comment by mibby** [comment]
Confirmed happening as well.
https://github.com/PaperMC/Paper/issues/425#issuecomment-247672833

**Comment by mibby** [comment]
@boy0001 Had another crash today. :(

FastAsyncWorldEdit dev 294
FastAsyncVoxelSniper dev 294
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 876

Config.
http://paste.ubuntu.com/23221330/

```
[18:12:05] [Craft Scheduler Thread - 245/INFO]: WorldEdit: player (in "world"): /fixwater 25 - Position: (-13885.0, 62.0, 6672.0)
[18:12:05] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_10_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:881) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:733) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:632) [patched_1.10.2.jar:git-Paper-876]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_102]
	at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:233) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.World.g(World.java:1713) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:666) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:643) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:870) ~[patched_1.10.2.jar:git-Paper-876]
	... 4 more
[18:12:05] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException
	at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_102]
	at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:233) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.World.g(World.java:1713) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:666) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:643) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:870) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:733) ~[patched_1.10.2.jar:git-Paper-876]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:632) [patched_1.10.2.jar:git-Paper-876]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

Crash log.
http://paste.ubuntu.com/23222703/

**Comment by boy0001** [comment]
@mibby 
You can disable parallel threads for now.

**Comment by mibby** [comment]
@boy0001 Will do. Assuming 1 = disabled. Still crashing as of dev 317 for reference. 

FastAsyncWorldEdit dev 317
FastAsyncVoxelSniper dev 317
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 878

Config.
http://paste.ubuntu.com/23231998/

Crash.
http://paste.ubuntu.com/23232000/

**Comment by boy0001** [comment]
Still set to 8 in config: `parallel-threads: 8`

**Comment by mibby** [comment]
I know. I changed it to 1 after the crash occurred. Just copied the config from when the crash happened so you know that is the config revision that has the problem. :)

**Comment by mibby** [comment]
@boy0001 Any update on a crash fix for parallel threads? Setting it to 1 seems to slow down worldedit operations dramatically.

**Comment by mibby** [comment]
Still crashing as of

FastAsyncWorldEdit dev 347
FastAsyncVoxelSniper dev 347
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 889

With ```parallel-threads: 8```.
```
java.lang.NullPointerException: Ticking player
	at java.util.LinkedList$ListItr.next(LinkedList.java:893)
	at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:233)
	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738)
	at net.minecraft.server.v1_10_R1.World.g(World.java:1713)
	at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:659)
	at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496)
	at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:636)
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:872)
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734)
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by boy0001** [comment]
Potentially fixed

**Comment by PhanaticD** [comment]
lol anyone else wana try out the fix first

**Comment by mibby** [comment]
I've been on dev build 354 (http://ci.athion.net/job/FastAsyncWorldEdit/354/) for a bit now and gone back to ```parallel-threads: 8``` with ```prevent-crashes: false``` (formerly had crash prevention enabled, changed it since default value was changed). So far I have not had any crashes from anyone using worldedit. So I'd assume the crashing problem relating to parallel threads has been fixed. Only additional time will tell though.
