### ISSUE TITLE
//sel extend bug

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#305]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
```
>fawe paste
[20:09:24 WARN]: java.io.IOException: Server returned HTTP response code: 500 for URL: http://hastebin.com/documents
[20:09:24 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
[20:09:24 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
[20:09:24 WARN]:        at com.boydti.fawe.util.HastebinUtility.upload(HastebinUtility.java:32)
[20:09:24 WARN]:        at com.boydti.fawe.util.HastebinUtility.upload(HastebinUtility.java:50)
[20:09:24 WARN]:        at com.boydti.fawe.util.HastebinUtility.upload(HastebinUtility.java:71)
[20:09:24 WARN]:        at com.boydti.fawe.command.Reload.execute(Reload.java:55)
[20:09:24 WARN]:        at com.boydti.fawe.object.FaweCommand$1.run(FaweCommand.java:33)
[20:09:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[20:09:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:09:24 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[20:09:24 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[20:09:24 WARN]:        at java.lang.Thread.run(Thread.java:745)
[20:09:24 INFO]: (FAWE) Reloaded (FastAsyncWorldEdit-16.9.21-b2ef1cb-294).
```

**Description of the problem:**
```
[19:41:23] [Server thread/INFO]: Player issued server command: //sel extend
[19:41:23] [Craft Scheduler Thread - 156/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:228) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:280) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:118) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:139) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:174) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:269) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:356) [FastAsyncWorldEdit-bukkit18.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at com.sk89q.worldedit.regions.CuboidRegion.recalculate(CuboidRegion.java:123) ~[?:?]
	at com.sk89q.worldedit.regions.CuboidRegion.setPos1(CuboidRegion.java:97) ~[?:?]
	at com.sk89q.worldedit.regions.selector.CuboidRegionSelector.<init>(CuboidRegionSelector.java:92) ~[?:?]
	at com.sk89q.worldedit.regions.selector.ExtendingCuboidRegionSelector.<init>(ExtendingCuboidRegionSelector.java:60) ~[?:?]
	at com.sk89q.worldedit.command.SelectionCommands.select(SelectionCommands.java:726) ~[?:?]
	... 17 more
```

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/fawe debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of FAWE
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
You didn't have a region set, fixed anyhow.
