### ISSUE TITLE
FaweChunkLoadException: Skipped loading chunk

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#308]
FastAsyncWorldEdit dev 294
FastAsyncVoxelSniper dev 294
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 876

Config.
http://paste.ubuntu.com/23221330/

```
[04:27:24] [Craft Scheduler Thread - 238/INFO]: WorldEdit: player (in "world"): /expand vert - Region: (-13912.0, 47.0, 6625.0) - (-13412.0, 47.0, 7125.0)
[04:27:27] [Craft Scheduler Thread - 239/INFO]: WorldEdit: player (in "world"): /replace water air - Region: (-13912.0, 0.0, 6625.0) - (-13412.0, 255.0, 7125.0)
[04:27:30] [Craft Scheduler Thread - 242/WARN]: com.boydti.fawe.object.exception.FaweException$FaweChunkLoadException: §cSkipped loading chunk: §7%s0;%s1§c. Try increasing chunk-wait.
```

```
[04:29:39] [Craft Scheduler Thread - 247/INFO]: WorldEdit: player (in "world"): /replace gravel stone - Region: (-13912.0, 0.0, 6625.0) - (-13412.0, 255.0, 7125.0)
[04:29:48] [Craft Scheduler Thread - 304/WARN]: com.boydti.fawe.object.exception.FaweException$FaweChunkLoadException: §cSkipped loading chunk: §7%s0;%s1§c. Try increasing chunk-wait.
```

**Comment by boy0001** [comment]
You could try increasing chunk-wait?

**Comment by mibby** [comment]
The default is not sufficient for a simple replace operation? TPS didn't drop below 19 and the world is saved on an SSD, so should load fast enough.

**Comment by boy0001** [comment]
Default is 1000 now.

**Comment by mibby** [comment]
@boy0001 Is it? Generated a new config with the latest dev build, still set to 100 by default.

**Comment by boy0001** [comment]
yes

**Comment by mibby** [comment]
Yes?

https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/boydti/fawe/config/Settings.java#L145

Doesn't look like default is 1,000 to me. o_O

**Comment by mibby** [comment]
Changed via https://github.com/boy0001/FastAsyncWorldedit/commit/8090bf9f1d91c31265093529726fef506ff7420a

Will let you know if I see any warnings or problems with chunk skipping.

**Comment by mibby** [comment]
@boy0001 Happened again with the new default of 1,000. Perhaps something is breaking and preventing the loading from continuing? 

It did the cut operation partially, then stopped entirely. Had to type it again to get it to continue / finish what it skipped. 

```
[18:35:14] [Server thread/INFO]: player issued server command: //cut
[18:35:14] [Craft Scheduler Thread - 91/INFO]: WorldEdit: player (in "Build2"): /cut - Region: (115.0, 66.0, 239.0) - (380.0, 84.0, 504.0)
[18:35:15] [Craft Scheduler Thread - 134/WARN]: com.boydti.fawe.object.exception.FaweException$FaweChunkLoadException: §cSkipped loading chunk: §7%s0;%s1§c. Try increasing chunk-wait.
[18:35:27] [Server thread/INFO]: player issued server command: //cut
[18:35:27] [Craft Scheduler Thread - 109/INFO]: WorldEdit: player (in "Build2"): /cut - Region: (115.0, 66.0, 239.0) - (380.0, 84.0, 504.0)
```

**Comment by mibby** [comment]
Still occurring as of

>FastAsyncWorldEdit dev 347
FastAsyncVoxelSniper dev 347
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 889

Config.
http://paste.ubuntu.com/23341264/

Chunk load skipping, which lead into a crash error.
```
[15:54:02] [Craft Scheduler Thread - 451/INFO]: WorldEdit: player (in "world"): /replace 0 stone - Region: (-6460.0, 49.0, 866.0) - (-6171.0, 64.0, 1221.0)
[15:54:06] [Craft Scheduler Thread - 486/WARN]: com.boydti.fawe.object.exception.FaweException$FaweChunkLoadException: §cSkipped loading chunk: §7%s0;%s1§c. Try increasing chunk-wait.

[15:54:06] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_10_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:883) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633) [patched_1.10.2.jar:git-Paper-889]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_102]
	at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:233) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.World.g(World.java:1713) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:659) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:636) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:872) ~[patched_1.10.2.jar:git-Paper-889]
	... 4 more
[15:54:06] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException
	at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_102]
	at net.minecraft.server.v1_10_R1.EntityPlayer.m(EntityPlayer.java:233) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.World.g(World.java:1713) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.WorldServer.l(WorldServer.java:659) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:636) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:872) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734) ~[patched_1.10.2.jar:git-Paper-889]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633) [patched_1.10.2.jar:git-Paper-889]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by boy0001** [comment]
Still an issue?

**Comment by N0tMyFaultOG** [comment]
Update Fawe
If the issue occurs still, reopen the ticket
