### ISSUE TITLE
ArithmeticException: / by zero

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#317]
FastAsyncWorldEdit dev 317
FastAsyncVoxelSniper dev 317
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 878

Config.
http://paste.ubuntu.com/23232047/

```
[18:27:16] [Server thread/INFO]: player issued server command: //set grass
[18:27:16] [Craft Scheduler Thread - 2/WARN]: java.lang.ArithmeticException: / by zero
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.boydti.fawe.util.MainUtil.stacktrace(MainUtil.java:109)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.sk89q.worldedit.LocalSession.getChangeSet(LocalSession.java:427)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.sk89q.worldedit.LocalSession.access$000(LocalSession.java:92)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.sk89q.worldedit.LocalSession$1.remove(LocalSession.java:125)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at java.util.Collections$SynchronizedList.remove(Collections.java:2426)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.sk89q.worldedit.LocalSession.remember(LocalSession.java:483)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.sk89q.worldedit.LocalSession.remember(LocalSession.java:421)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:331)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:118)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:139)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:174)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:270)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:359)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:27:16] [Craft Scheduler Thread - 2/WARN]:   at java.lang.Thread.run(Thread.java:745)
```

No global masks used by the player according to the log - so no bizarre expression used. These were the worldedit commands used leading up to the error.

http://paste.ubuntu.com/23232054/

Edit: Seems to happen quite frequently.
http://paste.ubuntu.com/23232070/

**Comment by mibby** [comment]
I also seem to be able to reproduce the problem when using voxel. It prevents the voxel change from occuring. I have to spam the brush a few times before it does the change. And when trying to undo everything, it does not undo the change made.

```
[19:33:03] [Craft Scheduler Thread - 82/WARN]: java.lang.ArithmeticException: / by zero
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.boydti.fawe.util.MainUtil.stacktrace(MainUtil.java:109)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.sk89q.worldedit.LocalSession.getChangeSet(LocalSession.java:427)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.sk89q.worldedit.LocalSession.access$000(LocalSession.java:92)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.sk89q.worldedit.LocalSession$1.remove(LocalSession.java:125)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at java.util.Collections$SynchronizedList.remove(Collections.java:2426)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.sk89q.worldedit.LocalSession.remember(LocalSession.java:483)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.sk89q.worldedit.LocalSession.remember(LocalSession.java:421)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.thevoxelbox.voxelsniper.Sniper.storeUndo(Sniper.java:96)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.thevoxelbox.voxelsniper.brush.SnipeBrush.arrow(SnipeBrush.java:26)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.thevoxelbox.voxelsniper.brush.Brush.perform(Brush.java:76)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:326)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:323)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:118)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:139)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:170)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[19:33:03] [Craft Scheduler Thread - 82/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by boy0001** [comment]
Should be fixed.
