### ISSUE TITLE
NullPointerException - VoxelSniper pMaterial.perform

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#335]
FastAsyncWorldEdit dev 347
FastAsyncVoxelSniper dev 347
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 889

Config.
http://paste.ubuntu.com/23294499/

Error occurs every time I try to use a voxelsniper arrow or powder brush.
```
[06:17:42] [Server thread/INFO]: player issued server command: /b s
[06:17:44] [Server thread/INFO]: player issued server command: /v 1
[06:17:45] [Server thread/INFO]: player issued server command: /b 1

[06:17:51] [Craft Scheduler Thread - 18/WARN]: java.lang.NullPointerException
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.thevoxelbox.voxelsniper.brush.perform.pMaterial.perform(pMaterial.java:44)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.thevoxelbox.voxelsniper.brush.SnipeBrush.powder(SnipeBrush.java:32)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.thevoxelbox.voxelsniper.brush.Brush.perform(Brush.java:79)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:327)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:324)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:119)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:140)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:171)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[06:17:51] [Craft Scheduler Thread - 18/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```
```
[06:17:55] [Craft Scheduler Thread - 18/WARN]: java.lang.NullPointerException
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.thevoxelbox.voxelsniper.brush.perform.pMaterial.perform(pMaterial.java:44)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.thevoxelbox.voxelsniper.brush.SnipeBrush.arrow(SnipeBrush.java:25)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.thevoxelbox.voxelsniper.brush.Brush.perform(Brush.java:76)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:327)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:324)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:119)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:140)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:171)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[06:17:55] [Craft Scheduler Thread - 18/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by PhanaticD** [comment]
getting this as well, and complaints of it being very slow
