### ISSUE TITLE
Cant get this to work, tried for hours...

### ISSUE THREAD

**Issue by Zilacon** [boy0001/FastAsyncWorldedit#339]
Add FAWE to bukkit with world edit, go onto server and use world edit, instantly crash with anvilchunkloader error among many others.

On a hybrid server (Thermos/Cauldron) World Edit is required to be on both FORGE and Bukkit. Bukkit syncs to all of the plugins including world guard, region market, etc. And the forge version syncs FML compatibility to the bukkit version which then hooks the permissions and ranks up of bukkit to the forge version. So this is kinda needed. FAWE does not allow this, it simply crashes the server instantly.

I have tried messing with my forge tick options, cauldron options, FAWE options, WE options, nothing worked i got the same result every time.

I wasnt even world editing anything THAT big only a 80x50 area.

I am running the latest Thermos version on MC 1.7.10 any help with getting this working would be great. Cause ive tried everything i can think of.

**Comment by boy0001** [comment]
Please post the errors.

**Comment by Zilacon** [comment]
````
[23:16:57] [Server thread/WARN]: java.lang.NullPointerException
[23:16:57] [Server thread/WARN]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:336)
[23:16:57] [Server thread/WARN]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:220)
[23:16:57] [Server thread/WARN]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:416)
[23:16:57] [Server thread/WARN]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:497)
[23:16:57] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1091)
[23:16:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:538)
[23:16:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:594)
[23:16:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:755)
[23:16:57] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
````

````
[23:16:34] [Server thread/ERROR]: ---- Minecraft Crash Report ----
// I feel sad now :(

Time: 10/20/16 11:16 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.network.play.server.S21PacketChunkData.func_149269_a(S21PacketChunkData.java:202)
	at net.minecraft.network.play.server.S26PacketMapChunkBulk.<init>(S26PacketMapChunkBulk.java:56)
	at net.minecraft.entity.player.EntityPlayerMP.localOnUpdate(EntityPlayerMP.java:374)
	at api.player.server.ServerPlayerAPI.onUpdate(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java)
	at net.minecraft.world.World.func_72866_a(World.java:2732)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877)
	at net.minecraft.world.World.func_72870_g(World.java:2675)
	at net.minecraft.world.World.func_72939_s(World.java:2477)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)
````

````
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: java.lang.NoSuchFieldException: tickingBlockCount
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitQueue17.setCount(BukkitQueue17.java:243)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitChunk_1_7.call(BukkitChunk_1_7.java:341)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitChunk_1_7.call(BukkitChunk_1_7.java:39)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1434)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[23:16:12] [ForkJoinPool-2-worker-6/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
````

````
[23:16:12] [Server thread/WARN]: Failed to handle packet for /xxx.xxx.xxx.xxx:xxxxx
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:477) ~[mw.class:?]
	at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source) ~[ServerPlayerAPI.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:488) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:101) ~[jd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(ExtendedBlockStorage.java:124) ~[apz.class:?]
	at net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:602) ~[apx.class:?]
	at net.minecraft.world.World.func_72805_g(World.java:940) ~[ahb.class:?]
	at net.minecraft.world.World.func_147447_a(World.java:1661) ~[ahb.class:?]
	at net.minecraft.world.World.func_72901_a(World.java:1475) ~[ahb.class:?]
	at chylex.hee.mechanics.compendium.events.CompendiumEvents.getObservation(CompendiumEvents.java:74) ~[CompendiumEvents.class:?]
	at chylex.hee.mechanics.compendium.events.CompendiumEvents.onPlayerTick(CompendiumEvents.java:142) ~[CompendiumEvents.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_117_CompendiumEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.56]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.56]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:350) ~[FMLCommonHandler.class:1.7.10-1614.56]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:247) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:399) ~[mw.class:?]
	... 12 more
````

````
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: java.lang.NoSuchFieldException: tickingBlockCount
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitQueue17.setCount(BukkitQueue17.java:243)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitChunk_1_7.call(BukkitChunk_1_7.java:341)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitChunk_1_7.call(BukkitChunk_1_7.java:39)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1434)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[23:16:12] [ForkJoinPool-2-worker-3/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[23:16:12] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$PlayerTickEvent@711ae086:
java.lang.NullPointerException
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(ExtendedBlockStorage.java:124) ~[apz.class:?]
	at net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:602) ~[apx.class:?]
	at net.minecraft.world.World.func_72805_g(World.java:940) ~[ahb.class:?]
	at net.minecraft.world.World.func_147447_a(World.java:1661) ~[ahb.class:?]
	at net.minecraft.world.World.func_72901_a(World.java:1475) ~[ahb.class:?]
	at chylex.hee.mechanics.compendium.events.CompendiumEvents.getObservation(CompendiumEvents.java:74) ~[CompendiumEvents.class:?]
	at chylex.hee.mechanics.compendium.events.CompendiumEvents.onPlayerTick(CompendiumEvents.java:142) ~[CompendiumEvents.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_117_CompendiumEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.56]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.56]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:350) [FMLCommonHandler.class:1.7.10-1614.56]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:247) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:399) [mw.class:?]
	at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source) [ServerPlayerAPI.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java) [mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:488) [nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:101) [jd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
````

````
[23:20:39] [Server thread/WARN]: java.lang.NoSuchFieldException: d
[23:20:39] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[23:20:39] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitQueue17.refreshChunk(BukkitQueue17.java:275)
[23:20:39] [Server thread/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue$2.run(NMSMappedFaweQueue.java:99)
[23:20:39] [Server thread/WARN]: 	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:67)
[23:20:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[23:20:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[23:20:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
[23:20:39] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[23:20:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[23:20:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[23:20:39] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:20:40] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(ExtendedBlockStorage.java:124) ~[apz.class:?]
	at net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:602) ~[apx.class:?]
	at net.minecraft.world.World.func_72805_g(World.java:940) ~[ahb.class:?]
	at mods.natura.blocks.trees.NLeaves.func_149674_a(NLeaves.java:81) ~[NLeaves.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:568) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963) ~[MinecraftServer.class:?]
	... 4 more
````

There was a lot of them >_>

**Comment by Zilacon** [comment]
Any update on this?

**Comment by boy0001** [comment]
@Zilacon 
Still an issue?

**Comment by Zilacon** [comment]
I dont know... You never replied with a fix... Has it been fixed?

**Comment by boy0001** [comment]
@Zilacon 
I made some fixed for 1.7.10 the last few days, and when I tested it seemed to work on thermos 1.7.10.

btw, sorry for taking a month to fix it.

**Comment by Zilacon** [comment]
Alright ill give it a shot tomorrow. Thanks.

**Comment by boy0001** [comment]
Assumed fixed.
