### ISSUE TITLE
VoxelSniper NullPointerException - pMaterial.perform

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#341]
FastAsyncWorldEdit dev 356 (357 on jenkins)
FastAsyncVoxelSniper dev 356 (357 on jenkins)
WorldEdit v6.1.5 dev 3623
VoxelSniper v5.171
Paper (Spigot 1.10.2) dev 898

Config.
http://paste.ubuntu.com/23379660/

Error occurs when using voxel snipe brush. Tried to undo after one voxel edit went off, didn't undo the operation. RE issue https://github.com/boy0001/FastAsyncWorldedit/issues/335 - not fixed?

```
[09:25:31] [Craft Scheduler Thread - 55/WARN]: java.lang.NullPointerException
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.thevoxelbox.voxelsniper.brush.perform.pMaterial.perform(pMaterial.java:44)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.thevoxelbox.voxelsniper.brush.SnipeBrush.arrow(SnipeBrush.java:25)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.thevoxelbox.voxelsniper.brush.Brush.perform(Brush.java:76)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:327)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:324)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:119)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:140)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:171)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at java.lang.Thread.run(Thread.java:745)
[09:25:31] [Craft Scheduler Thread - 55/WARN]: java.lang.NullPointerException
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.thevoxelbox.voxelsniper.brush.perform.pMaterial.perform(pMaterial.java:44)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.thevoxelbox.voxelsniper.brush.SnipeBrush.arrow(SnipeBrush.java:25)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.thevoxelbox.voxelsniper.brush.Brush.perform(Brush.java:76)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:327)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:324)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:119)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:131)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:140)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:171)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[09:25:31] [Craft Scheduler Thread - 55/WARN]:  at java.lang.Thread.run(Thread.java:745)
```

**Comment by boy0001** [comment]
Should be fixed.
