### ISSUE TITLE
Nukkit command //replaceall not work ,get error

### ISSUE THREAD

**Issue by NycuRO** [boy0001/FastAsyncWorldedit#349]
> /replaceAll 389 0
Nov 12, 2016 11:28:03 AM com.sk89q.worldedit.extension.platform.CommandManager$1 run
SEVERE: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:228)
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:281)
        at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:119)
        at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:140)
        at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:175)
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:270)
        at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:359)
        at com.boydti.fawe.util.TaskManager.taskNow(TaskManager.java:168)
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
        at com.boydti.fawe.nukkit.core.NukkitWorldEdit.onCommand(NukkitWorldEdit.java:148)
        at com.boydti.fawe.nukkit.core.DynamicPluginCommand.execute(DynamicPluginCommand.java:27)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
11:28:03 [INFO] [DonateInfo] ServerCommandEvent is called!
11:28:03 [INFO] Please report this error: [See console]
11:28:03 [INFO] java.lang.reflect.InvocationTargetException: null
>       at cn.nukkit.Server.dispatchCommand(Server.java:633)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:70)
Caused by: java.lang.NullPointerException
        at com.boydti.fawe.jnbt.anvil.MCAQueue.filterWorld(MCAQueue.java:45)
        at com.boydti.fawe.command.AnvilCommands.replaceAll(AnvilCommands.java:64)
        ... 27 more

**Comment by boy0001** [comment]
Uh, disable the experimental anvil mode.

**Comment by boy0001** [comment]
Is the world in anvil format?

**Comment by NycuRO** [comment]
Yes. @boy0001
