### ISSUE TITLE
BukkitChunk_1_8 - NPE

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#362]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/tomobogupi
http://hastebin.com/bugezixava
http://hastebin.com/ayixurajem
```
>ver
[13:38:52 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
>fawe version
[13:40:56 INFO]: (FAWE) Version Date: Jan 3, 2017 12:00:00 AM
[13:40:56 INFO]: (FAWE) Version Commit: 57d41ae
[13:40:56 INFO]: (FAWE) Version Build: #406
>wg version
[13:39:06 INFO]: WorldGuard 6.2.1-SNAPSHOT;1695-6e56763
[13:39:06 INFO]: http://www.sk89q.com
>we version
[13:39:29 INFO]: WorldEdit version (unknown)
[13:39:29 INFO]: https://github.com/sk89q/worldedit/
[13:39:29 INFO]: ----------- Platforms -----------
[13:39:29 INFO]: * Bukkit-Official (6.1.6-SNAPSHOT;3654-9c32ba3)
```

**Description of the problem:**
```
[20:15:40 INFO]: Player issued server command: //brush sphere 20%35:15,20%95:15,20%159:15,20%173,20%49 5
[20:15:44 WARN]: java.lang.NullPointerException
[20:15:44 WARN]:        at com.boydti.fawe.bukkit.v1_8.BukkitChunk_1_8.call(BukkitChunk_1_8.java:113)
[20:15:44 WARN]:        at com.boydti.fawe.bukkit.v1_8.BukkitChunk_1_8.call(BukkitChunk_1_8.java:36)
[20:15:44 WARN]:        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[20:15:44 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[20:15:44 WARN]:        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
[20:15:44 WARN]:        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
[20:15:44 WARN]:        at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1434)
[20:15:44 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:15:44 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:15:44 WARN]:        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[20:15:44 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[20:15:44 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[20:15:44 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[20:15:44 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**How to replicate**:
Not sure.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/fawe debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of FAWE
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket

**Comment by L4BORG** [comment]
Just tested latest FAWE, the issue is no more. Not sure in which commit it got fixed tho.
