### ISSUE TITLE
Malformed json in //paste

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#376]
**Debug paste link**:
After using the command, nothing shows on the console... :X 

**Description of the problem:**
After use the //paste command, the error shows up in the console, but the task runs.

Error:
```
[17:58:50] [Server thread/INFO] [nucleus]: PotterCraft_ ran the command: //paste
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at com.google.gson.internal.Streams.parse(Streams.java:56)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:501)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:512)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at net.minecraft.util.text.ITextComponent$Serializer.func_150699_a(ITextComponent.java:260)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at net.minecraft.tileentity.TileEntitySign.func_145839_a(TileEntitySign.java:103)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at com.boydti.fawe.forge.v0.ForgeChunk_All.call(ForgeChunk_All.java:359)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at com.boydti.fawe.forge.v0.ForgeChunk_All.call(ForgeChunk_All.java:37)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1434)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [com.boydti.fawe.util.MainUtil:handleError:524]:    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:  at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:  at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:  at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:572)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:  at com.google.gson.stream.JsonReader.peek(JsonReader.java:414)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:  at com.google.gson.internal.Streams.parse(Streams.java:42)
[17:58:50] [ForkJoinPool-2-worker-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:  ... 19 more
```

**Checklist**:
- [] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

I'm also using Sponge (not bukkit/forge), I think that could help.

**Comment by boy0001** [comment]
Could be from an invalid sign. (Or one made in a different version of minecraft)

**Comment by Eufranio** [comment]
Yes, it is: `net.minecraft.tileentity.TileEntitySign`, but could you hide those errors or set the sign as blank?

**Comment by boy0001** [comment]
Hiding errors generally isn't a good as then there's no clue as to why something isn't working. I might get around to setting a blank sign + more informative error message.

Are you able to provide me with the schematic?

**Comment by Eufranio** [comment]
I unfortunately dont have the schematic anymore, but it was a copy of an old spawn (probably 1.7) that we had.

**Comment by boy0001** [comment]
Okay, if it happens again please attach it here. I'll leave the issue open.
