### ISSUE TITLE
VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#391]
@boy0001 FastAsyncWorldEdit breaks with the latest WorldEdit dev builds.

Related commit.
https://github.com/sk89q/worldedit/commit/66aa881b0c4e349f9cd59e5e2c35c20f10387979

FastAsyncWorldEdit dev 494 (460 on jenkins)
WorldEdit dev 3674

Removing FAWE, worldedit loads fine. Is FAWE referencing awt kernel classes somewhere still that worldedit no longer does?

```
[11:45:23] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v17.01.08-f6db2cf-494-9.26.17
[11:45:24] [Server thread/WARN]: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/sk89q/worldedit/command/RegionCommands.smooth(Lcom/sk89q/worldedit/entity/Player;Lcom/sk89q/worldedit/EditSession;Lcom/sk89q/worldedit/regions/Region;IZ)V @26: invokespecial
  Reason:
    Type 'com/sk89q/worldedit/math/convolution/GaussianKernel' (current frame, stack[2]) is not assignable to 'java/awt/image/Kernel'
  Current Frame:
    bci: @26
    flags: { }
    locals: { 'com/sk89q/worldedit/command/RegionCommands', 'com/sk89q/worldedit/entity/Player', 'com/sk89q/worldedit/EditSession', 'com/sk89q/worldedit/regions/Region', integer, integer, 'com/sk89q/worldedit/math/convolution/HeightMap' }
    stack: { uninitialized 13, uninitialized 13, 'com/sk89q/worldedit/math/convolution/GaussianKernel' }
  Bytecode:
    0x0000000: bb02 9759 2c2d 1505 b702 9a3a 06bb 029c
    0x0000010: 59bb 029e 5908 0fb7 02a1 b702 a43a 0719
    0x0000020: 0619 0715 04b6 02a8 3608 b201 432b 04bd
    0x0000030: 0004 5903 1508 b800 7753 b601 46b1     

[11:45:24] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.setupInjector(Fawe.java:368)
[11:45:24] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.setupInjector(FaweBukkit.java:113)
[11:45:24] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:72)
[11:45:24] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:63)
[11:45:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[11:45:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:45:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[11:45:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:377)
[11:45:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:327)
[11:45:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:209)
[11:45:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599)
[11:45:24] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
```
[11:45:27] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.7-SNAPSHOT;3674-9f24f84
[11:45:27] [Server thread/ERROR]: Error occurred while enabling WorldEdit v6.1.7-SNAPSHOT;3674-9f24f84 (Is it up to date?)
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/sk89q/worldedit/command/RegionCommands.smooth(Lcom/sk89q/worldedit/entity/Player;Lcom/sk89q/worldedit/EditSession;Lcom/sk89q/worldedit/regions/Region;IZ)V @26: invokespecial
  Reason:
    Type 'com/sk89q/worldedit/math/convolution/GaussianKernel' (current frame, stack[2]) is not assignable to 'java/awt/image/Kernel'
  Current Frame:
    bci: @26
    flags: { }
    locals: { 'com/sk89q/worldedit/command/RegionCommands', 'com/sk89q/worldedit/entity/Player', 'com/sk89q/worldedit/EditSession', 'com/sk89q/worldedit/regions/Region', integer, integer, 'com/sk89q/worldedit/math/convolution/HeightMap' }
    stack: { uninitialized 13, uninitialized 13, 'com/sk89q/worldedit/math/convolution/GaussianKernel' }
  Bytecode:
    0x0000000: bb02 9759 2c2d 1505 b702 9a3a 06bb 029c
    0x0000010: 59bb 029e 5908 0fb7 02a1 b702 a43a 0719
    0x0000020: 0619 0715 04b6 02a8 3608 b201 432b 04bd
    0x0000030: 0004 5903 1508 b800 7753 b601 46b1     

	at com.sk89q.worldedit.extension.platform.CommandManager.<init>(CommandManager.java:164) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.<init>(PlatformManager.java:95) ~[?:?]
	at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java:95) ~[?:?]
	at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java:91) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:100) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:377) [patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:327) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:433) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:394) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:332) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.2.jar:git-Paper-1026]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
[11:45:27] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v6.1.7-SNAPSHOT;3674-9f24f84
[11:45:27] [Server thread/ERROR]: Error occurred while disabling WorldEdit v6.1.7-SNAPSHOT;3674-9f24f84 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.WorldEdit
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onDisable(WorldEditPlugin.java:171) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:377) [patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:327) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:433) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:394) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:332) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.2.jar:git-Paper-1026]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
```

**Comment by boy0001** [comment]
>  Is FAWE referencing awt kernel classes somewhere still that worldedit no longer does?

It referenced WorldEdit's GuassianKernel and HeightMapFilter classes. Since they changed the class signature, it broke compatibility with FAWE.
