### ISSUE TITLE
Error using //undo

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#393]
**Debug paste link**:
No link, a error instead
```
[17:21:18] [Server thread/INFO] [nucleus]: PotterCraft_ ran the command: /fawe debugpaste
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]: java.lang.RuntimeException: Couldn't read response!
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]:    at com.boydti.fawe.util.HastebinUtility.upload(HastebinUtility.java:43)
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]:    at com.boydti.fawe.util.HastebinUtility.upload(HastebinUtility.java:60)
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]:    at com.boydti.fawe.command.Reload.execute(Reload.java:60)
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]:    at com.boydti.fawe.object.FaweCommand$2.run(FaweCommand.java:40)
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]:    at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:115)
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]:    at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:143)
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]:    at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:180)
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:21:19] [pool-4-thread-289/INFO] [STDERR]: [com.boydti.fawe.object.FawePlayer$1:run:127]:    at java.lang.Thread.run(Thread.java:745)
```

Then I use //undo, sometimes, I get this:

**Description of the problem:**
[17:18:55] [Server thread/INFO] [nucleus]: PotterCraft_ ran the command: //undo
> Exception in thread "Server Watchdog" Jan 11, 2017 5:18:55 PM com.sk89q.worldedit.extension.platform.CommandManager$2 run
SEVERE: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:244)
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
        at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:308)
        at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:115)
        at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:143)
        at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:184)
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:297)
        at com.sk89q.worldedit.extension.platform.CommandManager$3.run(CommandManager.java:373)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.boydti.fawe.object.change.MutableEntityChange.perform(MutableEntityChange.java:98)
        at com.boydti.fawe.object.change.MutableEntityChange.create(MutableEntityChange.java:89)
        at com.boydti.fawe.object.change.MutableEntityChange.undo(MutableEntityChange.java:33)
        at com.sk89q.worldedit.function.operation.ChangeSetExecutor.resume(ChangeSetExecutor.java:72)
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:67)
        at com.sk89q.worldedit.function.operation.Operations.completeSmart(Operations.java:75)
        at com.sk89q.worldedit.EditSession.undo(EditSession.java:1221)
        at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:531)
        at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:202)
        ... 15 more

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

Using Sponge WorldEdit, Sponge FastAsyncWorldEdit and Sponge 1.10.2

**Comment by boy0001** [comment]
Using old version, please update.

**Comment by Eufranio** [comment]
Consider that this bug was reported 1 month ago, and I was using latest.

**Comment by boy0001** [comment]
I can reopen if it's still an issue.
