### ISSUE TITLE
//undo leaves blocks behind

### ISSUE THREAD

**Issue by dukedase** [boy0001/FastAsyncWorldedit#397]
**Debug paste link**:
 https://hastebin.com/ogulazulof

**Description of the problem:**
When anyone uses //undo, some of the blocks do not become undone, and instead simply stay there.
Here's the error from the console: 
[08:09:47] [Server thread/INFO]: Peratus issued server command: //undo
[08:09:47] [Craft Scheduler Thread - 29/WARN]: java.io.EOFException
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.boydti.fawe.object.changeset.FaweStreamChangeSet$4.readX(FaweStreamChangeSet.java:198)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.boydti.fawe.object.changeset.FaweStreamChangeSet$5.read(FaweStreamChangeSet.java:373)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.boydti.fawe.object.changeset.FaweStreamChangeSet$5.hasNext(FaweStreamChangeSet.java:392)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.boydti.fawe.object.changeset.FaweStreamChangeSet$9.hasNext(FaweStreamChangeSet.java:600)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.function.operation.ChangeSetExecutor.resume(ChangeSetExecutor.java:71)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:67)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.function.operation.Operations.completeSmart(Operations.java:75)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.EditSession.undo(EditSession.java:1223)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:531)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:220)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:244)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:308)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:125)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:153)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:194)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:297)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at com.sk89q.worldedit.extension.platform.CommandManager$3.run(CommandManager.java:380)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[08:09:47] [Craft Scheduler Thread - 29/WARN]: at java.lang.Thread.run(Thread.java:745)

**How to replicate**:

Select a region, do //set 0, or //copy, etc, and then //undo

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

There is another post about this problem, however it's from October.  (https://github.com/boy0001/FastAsyncWorldedit/issues/326)

**Comment by Joannou1** [comment]
Also having this issue, but no errors however.
Sometimes it'll partially remove a room, eg:

![image](https://cloud.githubusercontent.com/assets/997747/22134979/1663adaa-de80-11e6-8ae6-6025bb4bbf8e.png)

Doing this via api by the way.
Pasting and undoing with 

editSessions.get(player.getUniqueId()).undo(editSessions.get(player.getUniqueId()));

**Comment by dukedase** [comment]
This was fixed in a newer version.
