### ISSUE TITLE
Crash server on Thermos: 1614.58 (Minecraft 1.7.10)

### ISSUE THREAD

**Issue by nikitik7** [boy0001/FastAsyncWorldedit#403]
# Bug report template 
**Debug paste link**: https://hastebin.com/qisobaroko

**Description of the problem:**
On Thermos: 1614.58 (Minecraft 1.7.10) with any version WE server crash after i use //set or any command.

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
The error in the attached log is from BlocksHub's prism logger. If you aren't using the latest version of Prism, update it. If you are @SBPrime will need to update BlocksHub.

If this error is not what  caused the crash, let me know.

**Comment by nikitik7** [comment]
[20:19:15] [Server thread/INFO]: test issued server command: //set 0
[20:19:16] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m ====== NO NATIVE WORLDEDIT ADAPTER ======[m
[20:19:16] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m Try updating WorldEdit: [m
[20:19:16] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m  - http://builds.enginehub.org/job/worldedit?branch=master[m
[20:19:16] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m See also: http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters[m
[20:19:16] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m =========================================[m
[20:19:16] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m ====== NO NATIVE WORLDEDIT ADAPTER ======[m
[20:19:16] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m Try updating WorldEdit: [m
[20:19:16] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m  - http://builds.enginehub.org/job/worldedit?branch=master[m
[20:19:16] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m See also: http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters[m
[20:19:16] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m =========================================[m
[20:19:20] [Server thread/INFO]: test issued server command: /wea
[20:19:23] [Server thread/INFO]: test issued server command: /set 0
[20:19:25] [Server thread/INFO]: test issued server command: //set 0
[20:19:25] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m ====== NO NATIVE WORLDEDIT ADAPTER ======[m
[20:19:25] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m Try updating WorldEdit: [m
[20:19:25] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m  - http://builds.enginehub.org/job/worldedit?branch=master[m
[20:19:25] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m See also: http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters[m
[20:19:25] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m =========================================[m
[20:19:25] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m ====== NO NATIVE WORLDEDIT ADAPTER ======[m
[20:19:25] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m Try updating WorldEdit: [m
[20:19:25] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m  - http://builds.enginehub.org/job/worldedit?branch=master[m
[20:19:25] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m See also: http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters[m
[20:19:25] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m =========================================[m
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: java.lang.NullPointerException
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitChunk_1_7.call(BukkitChunk_1_7.java:175)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitChunk_1_7.call(BukkitChunk_1_7.java:37)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-1/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: java.lang.NullPointerException
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitChunk_1_7.call(BukkitChunk_1_7.java:175)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitChunk_1_7.call(BukkitChunk_1_7.java:37)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[20:19:25] [ForkJoinPool-2-worker-2/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: java.lang.NoSuchFieldException: d
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at java.lang.Class.getDeclaredField(Unknown Source)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitQueue17.sendChunk(BukkitQueue17.java:364)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitQueue17.sendChunk(BukkitQueue17.java:338)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.example.NMSRelighter.sendChunks(NMSRelighter.java:230)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:212)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue$1.run(NMSMappedFaweQueue.java:45)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.util.TaskManager.taskNow(TaskManager.java:168)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.util.TaskManager.taskNowAsync(TaskManager.java:194)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue.runTasks(NMSMappedFaweQueue.java:42)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.size(MappedFaweQueue.java:253)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FaweQueue.isEmpty(FaweQueue.java:443)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FaweQueue.flush(FaweQueue.java:470)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FaweQueue.flush(FaweQueue.java:450)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1314)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:359)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:125)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:153)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:194)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:297)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$3.run(CommandManager.java:380)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at java.lang.Thread.run(Unknown Source)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: java.lang.NoSuchFieldException: d
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at java.lang.Class.getDeclaredField(Unknown Source)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitQueue17.sendChunk(BukkitQueue17.java:364)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.bukkit.v1_7.BukkitQueue17.sendChunk(BukkitQueue17.java:338)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.example.NMSRelighter.sendChunks(NMSRelighter.java:230)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:212)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue$1.run(NMSMappedFaweQueue.java:45)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.util.TaskManager.taskNow(TaskManager.java:168)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.util.TaskManager.taskNowAsync(TaskManager.java:194)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue.runTasks(NMSMappedFaweQueue.java:42)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.size(MappedFaweQueue.java:253)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FaweQueue.isEmpty(FaweQueue.java:443)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FaweQueue.flush(FaweQueue.java:470)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FaweQueue.flush(FaweQueue.java:450)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1314)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:359)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:125)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:153)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:194)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:297)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$3.run(CommandManager.java:380)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:19:25] [Craft Scheduler Thread - 2/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by boy0001** [comment]
@nikitik7 
Oh, for Thermos you need to be using the forge FAWE, not bukkit.
