### ISSUE TITLE
FAWE can't set blocks above 128 in Nukkit

### ISSUE THREAD

**Issue by MrPowerGamerBR** [boy0001/FastAsyncWorldedit#412]
**Debug paste link**:
https://hastebin.com/radapusewi

**Description of the problem:**
You can't set blocks above 128 (and yes, MCPE/MCW10 and Nukkit already supports worlds bigger than 128)

**How to replicate**:

Try doing anything above 128 blocks.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by MrPowerGamerBR** [comment]
It seems the 128 value is hard coded in FAWE, will send a pull request ASAP fixing this issue

**Comment by MrPowerGamerBR** [comment]
(Well, I will submit a pull request when FAWE compiles... if I don't submit a pull request, then you can fix the issue yourself... because damn, downloading the dependencies is taking a while...)

Just change "128" to "256" in the needed methods inside FAWE's Nukkit code

**Comment by MrPowerGamerBR** [comment]
I tried fixing the issue but...
```
> java.lang.ArrayIndexOutOfBoundsException: 15
        at com.boydti.fawe.example.NMSMappedFaweQueue.end(NMSMappedFaweQueue.java:85)
        at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:176)
        at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:217)
        at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:119)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:791)
        at cn.nukkit.Server.start(Server.java:770)
        at cn.nukkit.Server.<init>(Server.java:455)
        at cn.nukkit.Nukkit.main(Nukkit.java:64)
```

**Comment by MrPowerGamerBR** [comment]
Fixed, before (left), after (right).

Will submit a pull request ASAP
![http://i.imgur.com/K6RHE1S.png](http://i.imgur.com/K6RHE1S.png)

**Comment by boy0001** [comment]
> because damn, downloading the dependencies is taking a while...

In the settings.gradle you can comment out all the modules except `core` and `nukkit`. It's probably all the forge/sponge dependencies taking ages.
