### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by seema84** [boy0001/FastAsyncWorldedit#432]
[09:42:16 INFO]: Player issued server command: //brush blendball
[09:42:17 INFO]: (FAWE) Using adapter: com.boydti.fawe.bukkit.v1_11.FaweAdapter_1_11@51e71958
[09:42:17 INFO]: (FAWE) =========================================
[09:42:29 WARN]: java.lang.ArrayIndexOutOfBoundsException: -1
[09:42:29 WARN]:        at com.boydti.fawe.bukkit.v1_11.BukkitQueue_1_11.getCachedSection(BukkitQueue_1_11.jav
a:184)
[09:42:29 WARN]:        at com.boydti.fawe.bukkit.v1_11.BukkitQueue_1_11.getCachedSection(BukkitQueue_1_11.jav
a:71)
[09:42:29 WARN]:        at com.boydti.fawe.example.MappedFaweQueue.getCombinedId4Data(MappedFaweQueue.java:594
)
[09:42:29 WARN]:        at com.boydti.fawe.object.FaweQueue.getCombinedId4Data(FaweQueue.java:392)
[09:42:29 WARN]:        at com.boydti.fawe.object.extent.FastWorldEditExtent.getLazyBlock(FastWorldEditExtent.
java:102)
[09:42:29 WARN]:        at com.sk89q.worldedit.EditSession.getLazyBlock(EditSession.java:874)
[09:42:29 WARN]:        at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:878)
[09:42:29 WARN]:        at com.boydti.fawe.object.brush.BlendBall.build(BlendBall.java:37)
[09:42:29 WARN]:        at com.sk89q.worldedit.command.tool.BrushTool.actPrimary(BrushTool.java:218)
[09:42:29 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager$7.run(PlatformManager.java:5
39)
[09:42:29 WARN]:        at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:125)
[09:42:29 WARN]:        at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:153)
[09:42:29 WARN]:        at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:190)
[09:42:29 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[09:42:29 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52
)
[09:42:29 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[09:42:29 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[09:42:29 WARN]:        at java.lang.Thread.run(Unknown Source)
[09:42:29 WARN]: java.lang.ArrayIndexOutOfBoundsException: -1
[09:42:29 WARN]:        at com.boydti.fawe.bukkit.v1_11.BukkitQueue_1_11.getCachedSection(BukkitQueue_1_11.jav
a:184)
[09:42:29 WARN]:        at com.boydti.fawe.bukkit.v1_11.BukkitQueue_1_11.getCachedSection(BukkitQueue_1_11.jav
a:71)
[09:42:29 WARN]:        at com.boydti.fawe.example.MappedFaweQueue.getCombinedId4Data(MappedFaweQueue.java:594
)
[09:42:29 WARN]:        at com.boydti.fawe.object.FaweQueue.getCombinedId4Data(FaweQueue.java:392)
[09:42:29 WARN]:        at com.boydti.fawe.object.extent.FastWorldEditExtent.getLazyBlock(FastWorldEditExtent.
java:102)
[09:42:29 WARN]:        at com.sk89q.worldedit.EditSession.getLazyBlock(EditSession.java:874)
[09:42:29 WARN]:        at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:878)
[09:42:29 WARN]:        at com.boydti.fawe.object.brush.BlendBall.build(BlendBall.java:37)
[09:42:29 WARN]:        at com.sk89q.worldedit.command.tool.BrushTool.actPrimary(BrushTool.java:218)
[09:42:29 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager$7.run(PlatformManager.java:5
39)
[09:42:29 WARN]:        at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:125)
[09:42:29 WARN]:        at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:153)
[09:42:29 WARN]:        at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:190)
[09:42:29 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[09:42:29 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52
)
[09:42:29 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[09:42:29 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[09:42:29 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by boy0001** [comment]
Fixed.
