### ISSUE TITLE
Could not dispatch event

### ISSUE THREAD

**Issue by TomberWolf** [boy0001/FastAsyncWorldedit#483]
We have some issues with Sponge for MC 1.10.2 as soon as we type a command.
Reported on WorldEdit, too.

```
    > //pos1
    > Mar 27, 2017 3:03:55 AM com.sk89q.worldedit.util.eventbus.EventBus dispatch
    SEVERE: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@1d6bf2
    02 to handler EventHandler{priority=NORMAL}
    java.lang.reflect.InvocationTargetException
            at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75)
            at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
            at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
            at com.sk89q.worldedit.sponge.SpongePlatform$1.process(SpongePlatform.java:131)
            at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:3
    36)
            at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:2
    95)
            at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
            at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423)
            at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388)
            at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
            at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
            at java.lang.Thread.run(Unknown Source)
    Caused by: java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)

            at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
            ... 11 more
    Caused by: java.lang.NullPointerException
            at com.boydti.fawe.object.FawePlayer.wrap(FawePlayer.java:90)
            at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:4
    35)
            ... 17 more
```

**Comment by boy0001** [comment]
Latest FAWE is for sponge 1.11, you'll need to find an older version. 

If you are using SpongeForge, I recommend you use FAWE-Forge and WorldEdit-Forge for 1.10.
