### ISSUE TITLE
NullPointerException on undo.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#508]
FAWE dev v17.04.15-b9854d3-638-12.3.3
WorldEdit dev 3682
Paper dev 1082 (Spigot 1.11.2)

```
[20:48:11] [Craft Scheduler Thread - 1058/INFO]: WorldEdit: player (in "world"): /sphere glass 3 - Position: (803.0, 70.0, -4342.0)
[20:48:20] [Craft Scheduler Thread - 1058/INFO]: WorldEdit: player (in "world"): /undo
[20:48:20] [Craft Scheduler Thread - 1058/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.NullPointerException
	at com.boydti.fawe.object.change.MutableEntityChange.perform(MutableEntityChange.java:98) ~[FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.boydti.fawe.object.change.MutableEntityChange.create(MutableEntityChange.java:89) ~[FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.boydti.fawe.object.change.MutableEntityChange.undo(MutableEntityChange.java:33) ~[FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.sk89q.worldedit.function.operation.ChangeSetExecutor.resume(ChangeSetExecutor.java:72) ~[FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:67) ~[FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.sk89q.worldedit.EditSession.undo(EditSession.java:1222) ~[FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:535) ~[FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:220) ~[FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:244) ~[FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:127) ~[FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:378) [FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:451) [FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:140) [FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:168) [FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:209) [FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:448) [FastAsyncWorldEdit-bukkit-17.04.15-b9854d3-638-12.3.3.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.11.2.jar:git-Paper-1082]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1082]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1082]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by mibby** [comment]
I'll re-open if I happen to see the error again. Just updated to v647 so I'll let you know. Thanks for the fix!

**Comment by mibby** [comment]
Oops, closed wrong ticket.

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket
