### ISSUE TITLE
Error executing //br splatter command

### ISSUE THREAD

**Issue by RikoDEV** [boy0001/FastAsyncWorldedit#522]
When player use this command (latest WE & FAWE):
[19:39:38] [Server thread/INFO]: Pegza issued server command: //br splatter sandstone 3

I get this error in console:
```
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: java.lang.UnsupportedOperationException: LocalVectorSet can only contain vectors from y elem:[0,255]
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.boydti.fawe.object.collection.LocalBlockVectorSet.add(LocalBlockVectorSet.java:196)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.boydti.fawe.object.collection.BlockVectorSet.add(BlockVectorSet.java:137)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.boydti.fawe.object.collection.BlockVectorSet.add(BlockVectorSet.java:126)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.sk89q.worldedit.function.visitor.BreadthFirstSearch.visit(BreadthFirstSearch.java:106)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.boydti.fawe.object.brush.ScatterBrush.build(ScatterBrush.java:61)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.sk89q.worldedit.command.tool.BrushTool.act(BrushTool.java:341)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.sk89q.worldedit.command.tool.BrushTool.actPrimary(BrushTool.java:356)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformManager$7.run(PlatformManager.java:542)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:140)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:168)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:211)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[19:40:12] [Craft Scheduler Thread - 4271/WARN]: 	at java.lang.Thread.run(Thread.java:745

```

**Comment by boy0001** [comment]
They probably clicked outside the world (e.g. sky)

**Comment by dordsor21** [comment]
can confirm they clicked outside the world. The error shouldn't be output to console though

**Comment by boy0001** [comment]
Has been fixed
