### ISSUE TITLE
No platform was found supporting USER_CMDS

### ISSUE THREAD

**Issue by Eufranio** [boy0001/FastAsyncWorldedit#550]
**Debug paste link**:
It's giving me a stacktrace every time I run:
```
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]: java.io.IOException: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at java.security.AccessController.doPrivileged(Native Method)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.boydti.fawe.util.HastebinUtility.upload(HastebinUtility.java:32)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.boydti.fawe.util.HastebinUtility.upload(HastebinUtility.java:62)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.boydti.fawe.util.HastebinUtility.debugPaste(HastebinUtility.java:66)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.sk89q.worldedit.command.WorldEditCommands.debugpaste(WorldEditCommands.java:153)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at java.lang.reflect.Method.invoke(Method.java:498)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:244)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java
:380)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:456)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:140)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:168)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:215)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:453)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:187)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>  [19:19:46] [pool-2-thread-13/INFO]: [STDERR]:     at java.lang.Thread.run(Thread.java:748)
>  [19:19:46] [pool-2-thread-13/INFO]: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents
```

This error is printed when the server is stopping:
```
>  [19:16:19] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Disconnect$Impl to Plugin{id=fastasyncworldedit, name= FastAsyncWorldEdit, 
version=development, description=fawe, url=https://github.com/boy0001/FastAsyncWorldedit, authors=[Empire92], source=/home/container/mods/FastAsyncWorldEdit-s
ponge-17.05.16-b870081-696-13.0.0.jar}
com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting USER_COMMANDS
    at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:186) ~[PlatformManager.class:?]
    at com.boydti.fawe.sponge.SpongePlayer.toWorldEditPlayer(SpongePlayer.java:77) ~[SpongePlayer.class:?]
    at com.boydti.fawe.object.FawePlayer.getPlayer(FawePlayer.java:360) ~[FawePlayer.class:?]
    at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:382) ~[FawePlayer.class:?]
    at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:453) ~[FawePlayer.class:?]
    at com.boydti.fawe.sponge.SpongeMain.onQuit(SpongeMain.java:59) ~[SpongeMain.class:?]
    at org.spongepowered.common.event.listener.DisconnectListener_SpongeMain_onQuit6.handle(Unknown Source) ~[?:?]
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2282-6.1.0-BETA-2343]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2343]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2343]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2343]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2343]
    at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) [SpongeImpl.class:1.11.2-2282-6.1.0-BETA-2343]
    at net.minecraft.network.NetHandlerPlayServer.redirect$onDisconnectHandler$zgo000(NetHandlerPlayServer.java:2290) [mi.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:793) [mi.class:?]
    at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:451) [er.class:?]
    at net.minecraft.network.NetHandlerPlayServer$2.run(NetHandlerPlayServer.java:275) [mi$2.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
    at net.minecraft.server.MinecraftServer.redirect$onCall$zhj000(MinecraftServer.java:3937) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1363) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1375) [MinecraftServer.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147360_c(NetHandlerPlayServer.java:271) [mi.class:?]
    at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:1047) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:389) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:535) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

## Using:
    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-806a22a
    SpongeForge: 1.11.2-2282-6.1.0-BETA-2343
    Minecraft Forge: 13.20.0.2298
    FastAsyncWorldEdit-sponge-17.05.16-b870081-696-13.0.0

**Checklist**:
- [ ] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket
