### ISSUE TITLE
CommandException: Invalid block 'Looks

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#558]
WorldEdit dev 3684
FAWE dev 705 - (FastAsyncWorldEdit-bukkit-17.05.29-a607d85-699-13.0.8.jar) http://ci.athion.net/job/FastAsyncWorldEdit/705/
Paper dev 1104 (Spigot 1.11.2)

Player accidentally typed two slashes when replying to a user instead of one, exception occurred.
```
[14:15:16] [Server thread/INFO]: player issued server command: //r Looks like he's gone right now?
[14:15:16] [Craft Scheduler Thread - 495/WARN]: com.sk89q.minecraft.util.commands.CommandException: Invalid block 'Looks'. See: //masks
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.internal.command.WorldEditExceptionConverter.convert(WorldEditExceptionConverter.java:152)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.util.command.parametric.ExceptionConverterHelper.convert(ExceptionConverterHelper.java:73)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:389)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:456)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:140)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:168)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:215)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:453)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: Caused by: com.sk89q.worldedit.extension.input.NoMatchException: Invalid block 'Looks'. See: //masks
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.extension.factory.DefaultMaskParser.parseFromInput(DefaultMaskParser.java:124)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.extension.factory.DefaultMaskParser.parseFromInput(DefaultMaskParser.java:31)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:57)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.internal.command.WorldEditBinding.getMask(WorldEditBinding.java:242)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:221)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:380)
[14:15:16] [Craft Scheduler Thread - 495/WARN]: 	... 11 more
```

**Comment by dordsor21** [comment]
still an issue?
