### ISSUE TITLE
CommandException - Can't bind tool to Wooden axe: Already used for the wand

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#559]
WorldEdit dev 3684
FAWE dev 705 - (FastAsyncWorldEdit-bukkit-17.05.29-a607d85-699-13.0.8.jar) http://ci.athion.net/job/FastAsyncWorldEdit/705/
Paper dev 1104 (Spigot 1.11.2)

```
[13:26:45] [Server thread/INFO]: player issued server command: //brush sphere 0 10
[13:26:45] [Craft Scheduler Thread - 429/INFO]: WorldEdit: player (in "world"): sphere 0 10
[13:26:45] [Craft Scheduler Thread - 429/WARN]: com.sk89q.minecraft.util.commands.CommandException: Can't bind tool to Wooden axe: Already used for the wand
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at com.sk89q.worldedit.internal.command.WorldEditExceptionConverter.convert(WorldEditExceptionConverter.java:142)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at com.sk89q.worldedit.util.command.parametric.ExceptionConverterHelper.convert(ExceptionConverterHelper.java:73)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:389)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:456)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:140)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:168)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:215)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:453)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[13:26:45] [Craft Scheduler Thread - 429/WARN]: 	at java.lang.Thread.run(Thread.java:7
```

**Comment by boy0001** [comment]
Someone tried to bind a brush to the worldedit wand. It should be printing the error to the player instead of console.

**Comment by mibby** [comment]
Well it outputted to console, so perhaps the logic needs to be inverted. :P

**Comment by dordsor21** [comment]
still an issue?
