### ISSUE TITLE
ServerInternalException: Attempted to place a tile entity when a person copied something to their clipboard.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#561]
WorldEdit dev 3684
FAWE dev 705 - (FastAsyncWorldEdit-bukkit-17.05.29-a607d85-699-13.0.8.jar) http://ci.athion.net/job/FastAsyncWorldEdit/705/
Paper dev 1104 (Spigot 1.11.2)
FAWE config - http://paste.ubuntu.com/24720387/

Error.
http://paste.ubuntu.com/24720440/

**Comment by mibby** [comment]
I also have an arena that loads a schematic every time it ends. When tping to the area after the schematic loads, the tile entity exception occurs. Noticed it attempts to place it -7k blocks underground?

```
[00:33:35] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_11_R1.TileEntitySign@478796c6) at -7722,-7722,-7722 (AIR) where there was no entity tile!
Chunk coordinates: -7728,2144
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Chunk.a(Chunk.java:782)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Chunk.a(Chunk.java:755)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:423)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:855)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
[00:33:35] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:33:35] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_11_R1.TileEntitySign@7c975cc8) at -7722,-7722,-7722 (AIR) where there was no entity tile!
Chunk coordinates: -7728,2144
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Chunk.a(Chunk.java:782)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Chunk.a(Chunk.java:755)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:423)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:855)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
[00:33:35] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:33:35] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_11_R1.TileEntitySign@54864bac) at -7722,-7722,-7722 (AIR) where there was no entity tile!
Chunk coordinates: -7728,2160
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Chunk.a(Chunk.java:782)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Chunk.a(Chunk.java:755)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:423)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[00:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:855)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
[00:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
[00:33:35] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mibby** [comment]
This seems to go away when downgrading to dev 694. See https://github.com/boy0001/FastAsyncWorldedit/issues/557#issuecomment-305956505

**Comment by boy0001** [comment]
Should be fixed

**Comment by Tiippex** [comment]
No it isn't :/
Or maybe it is back.
`[19:14:17 WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_12_R1.TileEntityChest@b654d63) at 516,87,-485 (AIR) where there was no entity tile!
[19:14:17 WARN]: Chunk coordinates: 512,-496
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:785)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:758)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:461)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:859)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[19:14:17 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:14:17 WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_12_R1.TileEntityChest@5885aa27) at 452,57,-621 (AIR) where there was no entity tile!
[19:14:17 WARN]: Chunk coordinates: 448,-624
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:785)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:758)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:461)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:859)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[19:14:17 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:14:17 WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_12_R1.TileEntityChest@777e9643) at 561,87,-492 (AIR) where there was no entity tile!
[19:14:17 WARN]: Chunk coordinates: 560,-496
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:785)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:758)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:461)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:859)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[19:14:17 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:14:17 WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_12_R1.TileEntityChest@2cd1ff38) at 561,87,-489 (AIR) where there was no entity tile!
[19:14:17 WARN]: Chunk coordinates: 560,-496
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:785)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:758)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:461)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[19:14:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:36)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:859)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[19:14:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[19:14:17 WARN]:        at java.lang.Thread.run(Thread.java:748)
`
