### ISSUE TITLE
method missing 1.12

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#562]
https://hastebin.com/ahupahucoq.md

**Comment by mibby** [comment]
Pasting here in case link goes down.
```
[23:00:03] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v17.05.30-1722daa-706-13.0.9
[23:00:03] [Server thread/INFO]: (FAWE) Running 1.12 registry dumper!
[23:00:03] [Server thread/WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_12_R1.Block.s(Lnet/minecraft/server/v1_12_R1/IBlockData;)Z
[23:00:03] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v1_12.NMSRegistryDumper.getMaterial(NMSRegistryDumper.java:242)
[23:00:03] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v1_12.NMSRegistryDumper.getProperties(NMSRegistryDumper.java:67)
[23:00:03] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v1_12.NMSRegistryDumper.run(NMSRegistryDumper.java:53)
[23:00:03] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:75)
[23:00:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[23:00:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[23:00:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[23:00:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379)
[23:00:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329)
[23:00:03] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:210)
[23:00:03] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612)
[23:00:03] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by SioWolf** [comment]
Having the same issue.

**Comment by Crypnotic** [comment]
The issues seems to be that `Block#s(IBlockData)` was remapped to `Block#r(IBlockData)`. I would fork an update myself, but the craftbukkit dependency included is outdated and I cannot update it properly.

**Comment by dordsor21** [comment]
@Crypnotic craftbukkit dependencies are odd. You need to run CraftBukkit it version 1.12 on your system and simply use the dependency
`		<dependency>
			<groupId>org.bukkit</groupId>
			<artifactId>craftbukkit</artifactId>
			<version>1.12-pre6-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>`

as craftbukkit 1.12 is not a thing yet I don't think

**Comment by Crypnotic** [comment]
@dordsor21 I'm not sure you understand what I was getting at, or maybe I suck at explaining. Nevertheless, I shall try to elaborate. 
The Craftbukkit jar that FAWE-bukkit builds against has a method mapped as `Block#s(IBlockData)`. 
The Spigot-1.12-pre6 server that servers that support 1.12 are most likely running has remapped that method to `Block#r(BlockData)`.
I was stating that I would attempt to update the mapping myself, but since the craftbukkit jar is a remote repo, I simply can't change it. So for that reason, I can't even compile it.

**Comment by dordsor21** [comment]
Are you talking about forking CraftBukkit? And the CI BuildTools is run using `java -jar BuildTools.jar --dev` so is the latest version.

**Comment by mibby** [comment]
Paper dev 1106 (Spigot 1.12)
WorldEdit dev 3688
FAWE dev 709

```
[21:28:54] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v17.06.06-6554370-709-13.0.12
[21:28:55] [Server thread/INFO]: (FAWE) Running 1.12 registry dumper!
[21:28:55] [Server thread/WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_12_R1.Block.s(Lnet/minecraft/server/v1_12_R1/IBlockData;)Z
[21:28:55] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v1_12.NMSRegistryDumper.getMaterial(NMSRegistryDumper.java:242)
[21:28:55] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v1_12.NMSRegistryDumper.getProperties(NMSRegistryDumper.java:67)
[21:28:55] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v1_12.NMSRegistryDumper.run(NMSRegistryDumper.java:53)
[21:28:55] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:75)
[21:28:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:28:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[21:28:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[21:28:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379)
[21:28:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329)
[21:28:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:210)
[21:28:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612)
[21:28:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by boy0001** [comment]
Was fixed.
