### ISSUE TITLE
User-mapped section open error

### ISSUE THREAD

**Issue by MrPowerGamerBR** [boy0001/FastAsyncWorldedit#582]
# Bug report template 

**Debug paste link**:

https://hastebin.com/ixegenuyep

**Description of the problem:**
If I try to use "//copy", it says "Bypass region with /wea" but, if I use "/wea" and try to copy, an exception is thrown.

This does NOT happen if I use "/wea" and then "//copy" (without using "//copy" before)

```
[15:51:48] [Server thread/INFO]: MrPowerGamerBR issued server command: //copy
[15:51:48] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m Using adapter: com.boydti.fawe.bukkit.v1_12.FaweAdapter_1_12@7d4d1025[m
[15:51:48] [Craft Scheduler Thread - 2/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m =========================================[m
[15:51:49] [Craft Scheduler Thread - 2/WARN]: com.boydti.fawe.object.exception.FaweException: No allowed region (bypass with /wea, or disable `region-restrictions` in config.yml)
[15:51:50] [Server thread/INFO]: MrPowerGamerBR issued server command: /wea
[15:51:53] [Server thread/INFO]: MrPowerGamerBR issued server command: //copy
[15:51:53] [Craft Scheduler Thread - 2/WARN]: java.io.IOException: A operação solicitada não pode ser executada em um arquivo com uma seção mapeada pelo usuário aberta
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at java.io.RandomAccessFile.setLength(Native Method)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:145)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:64)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.<init>(BlockArrayClipboard.java:88)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:154)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(Unknown Source)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:244)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:380)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:456)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:140)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:168)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:215)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:453)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:51:53] [Craft Scheduler Thread - 2/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

(Yes, the error message is kinda different in the stacktrace but that's because it is a Windows error, so it is on my computer language but, after searching on Google a little bit it seems the error in english is "User-mapped section open error")

**How to replicate**:

* Try using "//copy" with the "region-restrictions" option disabled
* Use "/wea"
* Try using "//copy" again

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Basically it can't open the file because something else has it open. In this case it wasn't closed properly by FAWE before you used `/wea`, so it won't work again until it's garbage collected. 

I'll fix it, in the meantime you can disable clipboard on disk.
