### ISSUE TITLE
//set or //paste causes errors | Forge for 1.7.10, worldedit + FAWE

### ISSUE THREAD

**Issue by Johnny-Ich** [boy0001/FastAsyncWorldedit#589]
**Debug paste link**: https://hastebin.com/sifexibomu

**Description of the problem:** FAWE / worldedit does not work properly. Even //set 0 causes errors.

I marked some terrain an typed //set 0. This was the output on Server Console:
```
[00:47:21] [Dynmap Render Thread/INFO] [Dynmap]: [Dynmap] Loading default resource pack
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassNotFoundException: org.sqlite.JDBC
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Class.forName0(Native Method)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Class.forName(Class.java:264)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.boydti.fawe.database.RollbackDatabase.openConnection(RollbackDatabase.java:285)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.boydti.fawe.database.RollbackDatabase.<init>(RollbackDatabase.java:54)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.boydti.fawe.database.DBHandler.getDatabase(DBHandler.java:20)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.boydti.fawe.logging.rollback.RollbackOptimizedHistory.close(RollbackOptimizedHistory.java:87)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.boydti.fawe.object.changeset.FaweChangeSet$1.run(FaweChangeSet.java:87)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Thread.run(Thread.java:748)
[00:47:46] [pool-3-thread-339/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException

```

**How to replicate**: Mark with the wand-Item some terrain and type //set 0 or //paste a schematic

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
In the config, change it to `database: false`. Or install sqlite driver on forge.

**Comment by Johnny-Ich** [comment]
Okay, thank you for your information.
I changed it in the config.yml to `use-database: false` and now no errors occures. 
Bit if i select a range an type `//set 0` nothing happens.
If i type `//set grass` nothing happens.
It only says `"Operation queued (2)"`

But if i type `//set water` the blocks in the range changes to water.
The command `//set cobble` works too.

I would like to thank you for your help. :) 

https://hastebin.com/ajefodegih

**Comment by dordsor21** [comment]
re-try those commands, it's highly likely you had a WE command executing, and it was luck that the other two commands worked. Original issue fixed anyway.
