### ISSUE TITLE
Another async chunk thingy error, caused by long distance teleports

### ISSUE THREAD

**Issue by Miclebrick** [boy0001/FastAsyncWorldedit#606]
https://hastebin.com/nilequtevo

```
[00:30:50 ERROR]: Could not pass event PlayerTeleportEvent to FastAsyncWorldEdit v17.06.20-841dccb-727-13.3.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1129]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.jar:git-Paper-1129]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1129]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.jar:git-Paper-1129]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.jar:git-Paper-1129]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:578) ~[patched_1.12.jar:git-Paper-1129]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:303) ~[patched_1.12.jar:git-Paper-1129]
        at net.cosmicconquest.starships.starship.Starship.moveAsync(Starship.java:385) ~[?:?]
        at net.cosmicconquest.starships.starship.Starship.lambda$translate$5(Starship.java:284) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.jar:git-Paper-1129]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.jar:git-Paper-1129]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.jar:git-Paper-1129]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalStateException: Asynchronous Async Player Chunk Remove!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[patched_1.12.jar:git-Paper-1129]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.b(PlayerChunkMap.java:477) ~[patched_1.12.jar:git-Paper-1129]
        at net.minecraft.server.v1_12_R1.PlayerChunk.b(PlayerChunk.java:102) ~[patched_1.12.jar:git-Paper-1129]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.setViewDistance(PlayerChunkMap.java:446) ~[patched_1.12.jar:git-Paper-1129]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.setViewDistance(PlayerChunkMap.java:417) ~[patched_1.12.jar:git-Paper-1129]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.updateViewDistance(PlayerChunkMap.java:554) ~[patched_1.12.jar:git-Paper-1129]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setViewDistance(CraftPlayer.java:1590) ~[patched_1.12.jar:git-Paper-1129]
        at com.boydti.fawe.bukkit.RenderListener.setViewDistance(RenderListener.java:98) ~[?:?]
        at com.boydti.fawe.bukkit.RenderListener.onPlayerTeleport(RenderListener.java:108) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1129]
```

I get this error and a frozen client, seemingly when teleporting several chunks away every 2 seconds.

**Comment by boy0001** [comment]
`net.cosmicconquest.starships.starship.Starship` is teleporting you async, which is unsafe and it shouldn't be doing.
