### ISSUE TITLE
Some //set commands are only queued, but not executed.

### ISSUE THREAD

**Issue by Johnny-Ich** [boy0001/FastAsyncWorldedit#609]
Debugpaste:
https://hastebin.com/hexemosuge

**Description of the problem:**  if i select a range an type //set 0 nothing happens.
If i type //set grass nothing happens.
It only says "Operation queued (2)"

But if i type //set water the blocks in the range changes to water.
The command //set cobble works too.
Why?

**How to replicate**: Select a range an try to set different IDs like cobble, water, lava etc. pp.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Johnny-Ich** [comment]
Anything i can do to help debugging this issue?

**Comment by Johnny-Ich** [comment]
`[01:05:59] [Server thread/INFO] [ForgeEssentials]: Player "Johnny_Ich" used command "//set 0"
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.util.ConcurrentModificationException
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.HashMap$HashIterator.remove(HashMap.java:1451)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.boydti.fawe.forge.v1710.ForgeChunk_All.call(ForgeChunk_All.java:251)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.boydti.fawe.forge.v1710.ForgeChunk_All.call(ForgeChunk_All.java:33)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1434)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3185)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:182)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:199)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:164)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.boydti.fawe.forge.ForgeTaskMan$1.run(ForgeTaskMan.java:47)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.boydti.fawe.forge.ForgeTaskMan$3.run(ForgeTaskMan.java:131)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.boydti.fawe.forge.ForgeTaskMan.onServerTick(ForgeTaskMan.java:72)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.eventhandler.ASMEventHandler_16_ForgeTaskMan_onServerTick_ServerTickEvent.invoke(.dy
namic)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[01:05:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
`

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the error persists still, reopen the ticket.

**Comment by HighBridRed** [comment]
This problem still persists, I've run into this issue for the past day.
Only when you warp or leave to a different area does it update the effected chunks.
How would this be solved?

**Comment by AndrewDisco** [comment]
Seems like the issue persists up to this day. Any updates? Seems like the staff team is very slow on fixing stuff. It took you 1 whole year to reply then close an issue that was here with the "high priority" tag?

**Comment by NotMyFault** [comment]
Like outlined in various spots, this repository is no longer in use. Everything has been shifted to https://github.com/IntellectualSites/FastAsyncWorldEdit
