### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by wasder** [boy0001/FastAsyncWorldedit#617]
**Debug paste link**: https://hastebin.com/oroyakitar

**Description of the problem:**
Crash log: https://hastebin.com/obaqisozoq
Async lightning problem?
Maybe related to this https://github.com/boy0001/FastAsyncWorldedit/issues/611
**How to replicate**:
Lately my server randomly crashes a lot and I strongly believe because of FAWE. It's creative server with P2.

**Comment by wasder** [comment]
Another crash:
https://hastebin.com/uyisolizuv

**Comment by wasder** [comment]
And another: https://pastebin.com/g2jwtS6g
Line 552
```"Server thread" - Thread t@19
   java.lang.Thread.State: WAITING
        at java.lang.Object.wait(Native Method)
        - waiting on <4a9ea8aa> (a java.lang.Thread)
        at java.lang.Thread.join(Thread.java:1249)
        at java.lang.Thread.join(Thread.java:1323)
        at com.boydti.fawe.bukkit.v0.BukkitChunk_All.call(BukkitChunk_All.java:177)
        at com.boydti.fawe.example.WeakFaweQueueMap.next(WeakFaweQueueMap.java:174)
        - locked <dafdae5> (a com.boydti.fawe.example.WeakFaweQueueMap$1)
        at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:217)
        at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:140)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
        at java.lang.Thread.run(Thread.java:745)```

**Comment by dordsor21** [comment]
can you post your plugin list? You're the only person this is happening to.

**Comment by boy0001** [comment]
In the `config.yml` enable `fast-placement` (line 242)
