### ISSUE TITLE
InvalidPluginException: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#633]
FAWE dev 745
FAVS dev 745
WorldEdit 6.1.8-SNAPSHOT dev 3690
VoxelSniper VoxelSniper-5.171.0-SNAPSHOT

@boy0001 Dev 745 / commit https://github.com/boy0001/FastAsyncWorldedit/commit/03b4aaad3ca34bb6ffdf3dc62671f387dde9527a breaks VoxelSniper.

```
[07:16:04] [Server thread/ERROR]: Could not load 'plugins/VoxelSniper-5.171.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/worldedit/extension/input/InputParseException
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:303) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1145]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/extension/input/InputParseException
	at com.thevoxelbox.voxelsniper.VoxelSniperListener.<init>(VoxelSniperListener.java:48) ~[?:?]
	at com.thevoxelbox.voxelsniper.VoxelSniper.<init>(VoxelSniper.java:30) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.jar:git-Paper-1145]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.extension.input.InputParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.jar:git-Paper-1145]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at com.thevoxelbox.voxelsniper.VoxelSniperListener.<init>(VoxelSniperListener.java:48) ~[?:?]
	at com.thevoxelbox.voxelsniper.VoxelSniper.<init>(VoxelSniper.java:30) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.jar:git-Paper-1145]
	... 6 more
```
```
[07:16:06] [Server thread/INFO]: [FastAsyncVoxelSniper] Enabling FastAsyncVoxelSniper v17.07.09-03b4aaa-745-13.7.1
[07:16:06] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328)
[07:16:06] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.favs.Favs.onEnable(Favs.java:36)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329)
[07:16:06] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:224)
[07:16:06] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615)
[07:16:06] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[07:16:06] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:123)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60)
[07:16:06] [Server thread/WARN]: 	at com.thevoxelbox.voxelsniper.VoxelSniper.<init>(VoxelSniper.java:25)
[07:16:06] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[07:16:06] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[07:16:06] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:16:06] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[07:16:06] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127)
[07:16:06] [Server thread/WARN]: 	... 10 more
[07:16:06] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Initial initialization
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:126)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60)
[07:16:06] [Server thread/WARN]: 	at com.thevoxelbox.voxelsniper.VoxelSniper.<init>(VoxelSniper.java:25)
[07:16:06] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[07:16:06] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[07:16:06] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:16:06] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[07:16:06] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251)
[07:16:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:303)
[07:16:06] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223)
[07:16:06] [Server thread/WARN]: 	... 2 more
[07:16:06] [Server thread/INFO]: (FAWE) ====== INSTALL VOXELSNIPER ======
[07:16:06] [Server thread/INFO]: (FAWE) FAVS requires VoxelSniper to function correctly
[07:16:06] [Server thread/INFO]: (FAWE) Info: https://github.com/boy0001/FastAsyncWorldedit/releases/
[07:16:06] [Server thread/INFO]: (FAWE) ===============================
```

**Comment by mibby** [comment]
I think I see what happened. FAVS re-downloaded a VoxelSniper.jar hardcoded by specific name, ignoring the 'VoxelSniper-5.171.0-SNAPSHOT.jar' already in the plugins folder. I take it a new custom version of VoxelSniper is needed for the new changes?
