### ISSUE TITLE
Failed to initialize with WorldEdit 7.0 - NoClassDefFoundError SignBlock & SkullBlock

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#634]
FAWE dev 745
WorldEdit 7.0 dev 3694

Commit https://github.com/boy0001/FastAsyncWorldedit/commit/03b4aaad3ca34bb6ffdf3dc62671f387dde9527a didn't fix issue https://github.com/boy0001/FastAsyncWorldedit/issues/632 fully.

```
[07:23:32] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v17.07.09-03b4aaa-745-13.7.1
[07:23:33] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/blocks/SignBlock
[07:23:33] [Server thread/WARN]: 	at com.sk89q.worldedit.extension.factory.BlockFactory.<init>(BlockFactory.java:48)
[07:23:33] [Server thread/WARN]: 	at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java:97)
[07:23:33] [Server thread/WARN]: 	at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java:88)
[07:23:33] [Server thread/WARN]: 	at com.sk89q.worldedit.world.registry.BundledBlockData.loadFromResource(BundledBlockData.java:86)
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.FaweCache.<clinit>(FaweCache.java:202)
[07:23:33] [Server thread/WARN]: 	at com.sk89q.worldedit.EditSession.<clinit>(EditSession.java:201)
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.setupInjector(Fawe.java:455)
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.setupInjector(FaweBukkit.java:134)
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:81)
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:52)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329)
[07:23:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:224)
[07:23:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615)
[07:23:33] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[07:23:33] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.blocks.SignBlock
[07:23:33] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[07:23:33] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[07:23:33] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[07:23:33] [Server thread/WARN]: 	... 18 more
[07:23:33] [Server thread/INFO]: (FAWE) ====== FAWE FAILED TO INITIALIZE ======
[07:23:33] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/blocks/SignBlock
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.setupInjector(Fawe.java:553)
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.setupInjector(FaweBukkit.java:134)
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:81)
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:52)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329)
[07:23:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:224)
[07:23:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615)
[07:23:33] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[07:23:33] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.blocks.SignBlock
[07:23:33] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[07:23:33] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[07:23:33] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[07:23:33] [Server thread/WARN]: 	... 12 more
[07:23:33] [Server thread/INFO]: (FAWE) =======================================
[07:23:33] [Server thread/INFO]: (FAWE) Things to check: 
[07:23:33] [Server thread/INFO]: (FAWE)  - Using the latest version of WorldEdit/FAWE
[07:23:33] [Server thread/INFO]: (FAWE)  - AsyncWorldEdit/WorldEditRegions isn't installed
[07:23:33] [Server thread/INFO]: (FAWE)  - Any other errors in the startup log
[07:23:33] [Server thread/INFO]: (FAWE) Contact Empire92 if you need assistance:
[07:23:33] [Server thread/INFO]: (FAWE)  - Send me a PM or ask on IRC
[07:23:33] [Server thread/INFO]: (FAWE)  - http://webchat.esper.net/?nick=hannels=IntellectualCrafters
[07:23:33] [Server thread/INFO]: (FAWE) =======================================
[07:23:33] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/blocks/SkullBlock
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:82)
[07:23:33] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:52)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329)
[07:23:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:224)
[07:23:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615)
[07:23:33] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[07:23:33] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.blocks.SkullBlock
[07:23:33] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[07:23:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[07:23:33] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[07:23:33] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[07:23:33] [Server thread/WARN]: 	... 10 more
```

```
[07:23:36] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.0.0-SNAPSHOT;3694-4a5d962
[07:23:36] [Server thread/ERROR]: Error occurred while enabling WorldEdit v7.0.0-SNAPSHOT;3694-4a5d962 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.WorldEdit
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:100) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1145]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[07:23:36] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v7.0.0-SNAPSHOT;3694-4a5d962
[07:23:36] [Server thread/ERROR]: Error occurred while disabling WorldEdit v7.0.0-SNAPSHOT;3694-4a5d962 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.WorldEdit
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onDisable(WorldEditPlugin.java:171) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1145]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
```
[07:23:36] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.2.2-SNAPSHOT;1708-3a8e3e8
[07:23:36] [Server thread/ERROR]: Error occurred while enabling WorldGuard v6.2.2-SNAPSHOT;1708-3a8e3e8 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/SimpleInjector
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:173) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1145]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.sk89q.minecraft.util.commands.SimpleInjector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.jar:git-Paper-1145]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 12 more
[07:23:36] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v6.2.2-SNAPSHOT;1708-3a8e3e8
[07:23:36] [Server thread/INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[07:23:36] [Server thread/ERROR]: Error occurred while disabling WorldGuard v6.2.2-SNAPSHOT;1708-3a8e3e8 (Is it up to date?)
java.lang.NullPointerException: null
	at com.sk89q.worldguard.bukkit.RegionContainer.unload(RegionContainer.java:138) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:287) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1145]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by hYdos** [comment]
yea got the same problem

**Comment by N0tMyFaultOG** [comment]
If the issue persists still, reply to the ticket
