### ISSUE TITLE
Memory Leak (?)

### ISSUE THREAD

**Issue by Maxetto** [boy0001/FastAsyncWorldedit#667]
# Bug report

**Debug paste link**:

https://hastebin.com/wisudifeti

**Description of the problem:**

Since about 24 of July I'm experiencing continuos crashes due to the kernel killing the java instances.
Now, I did not do anything to my machine since 1 month, and the only plugin that is auto-updating is yours.

My host is pointing the fault at me, but it's about a year that I didn't experience any issue as I'm also using fixed RAM from the startup script.

So, my only thought is that an update of yours have broken RAM management of my machine. Also, today I got quite spammed from those errors:
```
[17:01:03] [Craft Scheduler Thread - 576/INFO]: WorldEdit: StevenUniverse (in "Creative_64"): /set air - Region: (271.0, 70.0, 3400.0) - (275.0, 75.0, 3404.0)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: java.io.IOException: Compression error: cannot create header: Allocation error : not enough memory
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.github.luben.zstd.ZstdOutputStream.<init>(ZstdOutputStream.java:52)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.util.MainUtil.getCompressedOS(MainUtil.java:330)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.util.MainUtil.getCompressedOS(MainUtil.java:248)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.object.changeset.FaweStreamChangeSet.getCompressedOS(FaweStreamChangeSet.java:247)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.object.changeset.DiskStorageHistory.getBlockOS(DiskStorageHistory.java:258)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.object.changeset.FaweStreamChangeSet.add(FaweStreamChangeSet.java:326)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.logging.rollback.RollbackOptimizedHistory.add(RollbackOptimizedHistory.java:98)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.logging.LoggingChangeSet.add(LoggingChangeSet.java:68)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.object.HistoryExtent.setBlock(HistoryExtent.java:81)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.object.extent.ProcessedWEExtent.setBlock(ProcessedWEExtent.java:101)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.object.extent.ProcessedWEExtent.setBlock(ProcessedWEExtent.java:74)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:143)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.object.extent.FaweRegionExtent.setBlock(FaweRegionExtent.java:64)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.blocks.BaseBlock.apply(BaseBlock.java:452)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:58)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.function.visitor.RegionVisitor.apply(RegionVisitor.java:187)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:107)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:68)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1668)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1702)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.command.RegionCommands.set(RegionCommands.java:337)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:244)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:381)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:456)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:208)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:236)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:283)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:453)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:01:03] [Craft Scheduler Thread - 576/WARN]: 	at java.lang.Thread.run(Thread.java:748)
... and many more...
```

**How to replicate**:

No idea. Just do things...

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Try disabling blockshub

**Comment by Maxetto** [comment]
It's a Public Creative server with WorldEdit, I'd like to keep logging actions.

Is it ok if I disable BlocksHub and enable CoreProtect's WorldEdit integrated logger (even if it's not recommended)?

**Comment by boy0001** [comment]
Using CoreProtect's logger directly doesn't solve the issue (BlocksHub just forwards data to CP) and wouldn't be safe. 

CP cannot handle large edits without there being a huge backlog, which'll use a lot of memory. 
This has always been an issue, though I don't know why you would only experience it now. 

Anywho, FAWE already logs all edits. You can use `//inspect` and `//rollback` for a bit as you determine whether disabling BH helps.
