### ISSUE TITLE
Saving and loading a valid brush pastes error in chat

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#674]
**Debug paste link**:
https://hastebin.com/olocajodot

**Description of the problem:**
I was trying to make a brush which removes snow under certain conditions. The brush itself is working. But once saved it cant be loaded. 
Here's the error and also the commands that were used. 
https://hastebin.com/iqisozejus.java

**How to replicate**:
See commands in the last hastebin. 

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Panossa** [comment]
Bug (re?)appeared in build #791 again. (newest available build)

See here:
```
[20:13:08] [Server thread/INFO]: Hufflepug issued server command: /loadbrush desertpath
[20:13:08] [Craft Scheduler Thread - 339/INFO]: WorldEdit: Hufflepug (in "ethyria_survival"): loadbrush desertpath
[20:13:08] [Craft Scheduler Thread - 339/WARN]: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at com.sk89q.worldedit.command.tool.BrushTool.fromString(BrushTool.java:100)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at com.sk89q.worldedit.command.BrushOptionsCommands.loadBrush(BrushOptionsCommands.java:119)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:245)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:380)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:456)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:208)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:236)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:283)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:453)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[20:13:08] [Craft Scheduler Thread - 339/WARN]: 	at java.lang.Thread.run(Thread.java:748)```

**Comment by Panossa** [comment]
Can this issue be reopened or do I need to write another one?
