### ISSUE TITLE
FAWE Error

### ISSUE THREAD

**Issue by FrankHeijden** [boy0001/FastAsyncWorldedit#687]
# Bug report

**Debug paste link**:

https://hastebin.com/haqawikira
**Description of the problem:**

```
10.08 00:06:40 [Server] INFO FrankHeijden issued server command: //fill dirt 50 50
10.08 00:06:40 [Server] ERROR [WorldEdit] An unexpected error occurred while handling a FAWE command
10.08 00:06:40 [Server] INFO java.lang.StackOverflowError: null
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:22) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
10.08 00:06:40 [Server] INFO at com.boydti.fawe.object.extent.ResettableExtent.init(ResettableExtent.java:23) ~[?:?]
```
**How to replicate**:

command 
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
You also need to use `/wea`
