### ISSUE TITLE
FAWE Tabcompleter error | False suggestions

### ISSUE THREAD

**Issue by PT400C** [boy0001/FastAsyncWorldedit#690]
# Bug report

**Debug paste link**:

https://hastebin.com/azojazemaw

**Description of the problem:**

Error in the console if using `//undo 1(Vaild undo number) k(or any other character) TAB`
The error is:
`[WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandSuggestionEvent@234bddf6 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[WorldEdit-JCEdit.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [WorldEdit-JCEdit.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [WorldEdit-JCEdit.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onTabComplete(WorldEditPlugin.java:261) [WorldEdit-JCEdit.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.tabComplete(DynamicPluginCommand.java:84) [WorldEdit-JCEdit.jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:134) [patched_1.9.4.jar:git-Paper-773]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:234) [patched_1.9.4.jar:git-Paper-773]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:182) [patched_1.9.4.jar:git-Paper-773]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.tabCompleteCommand(CraftServer.java:1675) [patched_1.9.4.jar:git-Paper-773]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.tabComplete(CraftServer.java:1642) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.MinecraftServer.tabCompleteCommand(MinecraftServer.java:1163) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:2187) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.PacketPlayInTabComplete.a(SourceFile:52) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.PacketPlayInTabComplete.a(SourceFile:11) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-773]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-773]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[WorldEdit-JCEdit.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[WorldEdit-JCEdit.jar:?]
        ... 22 more
Caused by: java.lang.RuntimeException: Invalid suggestion context
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.getSuggestions(ParametricCallable.java:364) ~[FastAsyncWorldEdit-bukkit-17.07.22-8150b71-757-13.7.15.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:166) ~[FastAsyncWorldEdit-bukkit-17.07.22-8150b71-757-13.7.15.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandSuggestion(CommandManager.java:471) ~[FastAsyncWorldEdit-bukkit-17.07.22-8150b71-757-13.7.15.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[WorldEdit-JCEdit.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[WorldEdit-JCEdit.jar:?]
        ... 22 more`

**How to replicate**:

Really easy as I said at the description.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Seeing this too
