### ISSUE TITLE
FAWE lastest with spigot 1.8.8 error

### ISSUE THREAD

**Issue by Kiwis2451** [boy0001/FastAsyncWorldedit#699]
pls help me
```
[FastAsyncWorldEdit] Task #6 for FastAsyncWorldEdit v17.08.18-81ffd52-820-15.2.7 generated an exception
java.lang.NullPointerException
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.UnsafeQualifiedBooleanFieldAccessorImpl.set(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Field.set(Unknown Source) ~[?:1.8.0_144]
	at com.boydti.fawe.bukkit.FaweBukkit$2.lambda$run$0(FaweBukkit.java:214) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_144]
	at com.boydti.fawe.bukkit.FaweBukkit$2.run(FaweBukkit.java:199) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by boy0001** [comment]
Can you please follow the issue template and include a `/fawe debugpaste`. 

Also, it's a problem with metrics, the issue isn't critical, though it would be good to resolve.

**Comment by Kiwis2451** [comment]
https://hastebin.com/efekemanuj.php 
here you are

**Comment by dordsor21** [comment]
@Kiwis2451
