### ISSUE TITLE
No platform was found supporting USER_COMMANDS

### ISSUE THREAD

**Issue by IhToN** [boy0001/FastAsyncWorldedit#713]
# Bug report

```
[20:55:19 INFO]: [WetSponge -> Error] Error while loading a plugin!
[20:55:19 WARN]: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting USER_COMMANDS
[20:55:19 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:190)
[20:55:19 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager.getServerInterface(PlatformManager.java:332)
[20:55:19 WARN]:        at com.sk89q.worldedit.WorldEdit.getServer(WorldEdit.java:810)
[20:55:19 WARN]:        at com.boydti.fawe.FaweAPI.getWorld(FaweAPI.java:199)
[20:55:19 WARN]:        at com.degoos.eggwars.util.ArenaUtils.pasteSchematic(ArenaUtils.java:55)
[20:55:19 WARN]:        at com.degoos.eggwars.object.Arena.startMatch(Arena.java:589)
[20:55:19 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[20:55:19 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[20:55:19 WARN]:        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
[20:55:19 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[20:55:19 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[20:55:19 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[20:55:19 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[20:55:19 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[20:55:19 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[20:55:19 WARN]:        at com.degoos.eggwars.manager.ArenaManager.startMatches(ArenaManager.java:109)
[20:55:19 WARN]:        at com.degoos.eggwars.manager.MatchManager.load(MatchManager.java:27)
[20:55:19 WARN]:        at com.degoos.eggwars.loader.ManagerLoader.addManager(ManagerLoader.java:42)
[20:55:19 WARN]:        at com.degoos.eggwars.loader.ManagerLoader.loadDefManagers(ManagerLoader.java:31)
[20:55:19 WARN]:        at com.degoos.eggwars.loader.ManagerLoader.load(ManagerLoader.java:17)
[20:55:19 WARN]:        at com.degoos.eggwars.EggWars.onEnable(EggWars.java:25)
[20:55:19 WARN]:        at com.degoos.wetsponge.plugin.WSPlugin.setEnabled(WSPlugin.java:97)
[20:55:19 WARN]:        at com.degoos.wetsponge.plugin.WSPluginManager.loadPlugins(WSPluginManager.java:79)
[20:55:19 WARN]:        at com.degoos.wetsponge.WetSponge.loadCommon(WetSponge.java:57)
[20:55:19 WARN]:        at com.degoos.wetsponge.SpigotWetSponge.onEnable(SpigotWetSponge.java:49)
[20:55:19 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:55:19 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[20:55:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[20:55:19 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380)
[20:55:19 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329)
[20:55:19 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[20:55:19 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[20:55:19 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[20:55:19 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[20:55:19 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[20:55:19 WARN]:        at java.lang.Thread.run(Unknown Source)
```

FAWE DebugPaste - https://hastebin.com/iwefitaziv

**Description**:
I'm trying to paste a loaded schematic saved before on a custom plugin and this is the error happening.
Has been tested using Sponge and Spigot and the error occurs in both cases.

**How to replicate**:
Code to paste and save schematic used:

```
public static void pasteSchematic (Arena arena, WSPlayer player) {

		File file = new File(ManagerLoader.getManager(FileManager.class).getSchemsFolder(), arena.getName() + ".schematic");

		if (!file.exists() || file.isDirectory()) {
			LanguagesAPI.sendMessage(player != null ? player : WetSponge.getServer().getConsole(), "command.setup.error.schemDoesntExist", EggWars.getInstance(), "<ARENA>",
			                         arena.getName());
			return;
		}

		World world = FaweAPI.getWorld(arena.getName());

		EditSession editSession;
		if (player != null) editSession = new EditSessionBuilder(world).player(FaweAPI.wrapPlayer(player.getUniqueId())).fastmode(true).build();
		else editSession = new EditSessionBuilder(world).fastmode(true).build();

		try {
			CuboidClipboard schemClip = SchematicFormat.getFormat(file).load(file);
			double          ypos      = arena.getCenterY();
			if (ypos < 0) ypos = Math.floor(schemClip.getHeight() / 2);
			schemClip.paste(editSession, new Vector(arena.getCenterX(), ypos, arena.getCenterZ()), false, false);
		} catch (MaxChangedBlocksException | DataException | IOException e) {
			LanguagesAPI.sendMessage(player != null ? player : WetSponge.getServer().getConsole(), "command.setup.error.schemWrongFormat", EggWars.getInstance(), "<ARENA>",
			                         arena.getName());
		}
		editSession.flushQueue();
	}


	public static boolean saveSchematic (Arena arena, WSPlayer player) {

		File   file  = new File(ManagerLoader.getManager(FileManager.class).getSchemsFolder(), arena.getName() + ".schematic");
		World  world = FaweAPI.getWorld(arena.getName());
		Vector bot   = new Vector(arena.getCenterX() + arena.getRadius(), 0, arena.getCenterZ() + arena.getRadius());
		Vector top   = new Vector(arena.getCenterX() - arena.getRadius(), 255, arena.getCenterZ() - arena.getRadius());

		CuboidRegion region = new CuboidRegion(world, bot, top);
		Schematic    schem  = new Schematic(region);
		try {
			schem.save(file, ClipboardFormat.SCHEMATIC);
		} catch (IOException e) {
			LanguagesAPI.sendMessage(player != null ? player : WetSponge.getServer().getConsole(), "command.error.schemSaveError", EggWars.getInstance(), "<ARENA>",
			                         arena.getName());
			e.printStackTrace();
			return false;
		}
		return true;
	}
```

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue) - there is a duplicate with no answer
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
You need to wait until WorldEdit is enabled. 
Add `depend: [WorldEdit]` to the `plugin.yml`

**Comment by IhToN** [comment]
It's weird, the plugin currently Depends on WorldEdit, and it's being loaded after it. But the error persists.

**Comment by boy0001** [comment]
You should see a message when WorldEdit is enabled:
> [WorldEdit] Enabling WorldEdit v6.1.9-SNAPSHOT;3706-d6aa1ad

**Comment by IhToN** [comment]
Yes, the message appears and checking the run order, WorldEdit goes before my plugin but it's still happening.

I've trying delaying the plugin loading and it seems to work. It's not a beautiful solution but it works.

**Comment by boy0001** [comment]
@IhToN 
 If you want to send me the non functional version of your plugin, I can see if it's something I can fix on my end. mailto:jessepaleg@gmail.com

**Comment by IhToN** [comment]
Sorry for not responding. It seems that it was a bug in our WetSponge Plugin.

Thanks to your comment we could find where it was the problem :D
