### ISSUE TITLE
MyPet Premium link error

### ISSUE THREAD

**Issue by andris155** [boy0001/FastAsyncWorldedit#718]
# Bug report

**Debug paste link**:https://hastebin.com/zetaqeqasa

**Description of the problem:**

MyPet link error (MyPet Premium)
```
[05:01:10] [Server thread/INFO]: [MyPet] Enabling MyPet v2.3.6
[05:01:10] [Server thread/INFO]: [MyPet] mcMMO (1.5.08-SNAPSHOT) hook activated.
[05:01:10] [Server thread/INFO]: [MyPet] MobArena (0.98.1) (com.garbagemule.MobArena.MobArena) hook activated.
[05:01:10] [Server thread/INFO]: [MyPet] NoCheatPlus (3.15.2-SNAPSHOT-sMD5NET-b1113) hook activated.
[05:01:10] [Server thread/INFO]: [MyPet] PlotSquared (3.5.1-SNAPSHOT-b924809) hook activated.
[05:01:10] [Server thread/INFO]: [MyPet] ProtocolLib (4.3.0) hook activated.
[05:01:10] [Server thread/INFO]: [MyPet] PvPManager (3.7.5) hook activated.
[05:01:10] [Server thread/INFO]: [MyPet] SurvivalGames (Beta 1.9.5) (me.maker56.survivalgames.SurvivalGames) hook activated.
[05:01:10] [Server thread/INFO]: [MyPet] Vault (1.6.1) (Economy: Essentials Economy) hook activated.
[05:01:10] [Server thread/INFO]: [MyPet] WorldGuard (6.2.2-SNAPSHOT;1708-3a8e3e8) hook activated.
[05:01:10] [Server thread/INFO]: [MyPet] Compat mode for v1_12_R1 loaded.
[05:01:12] [Server thread/INFO]: [MyPet] Connect to SQLite database...
[05:01:12] [Server thread/INFO]: [MyPet] SQLite connection successful.
[05:01:12] [Server thread/INFO]: [MyPet] --- Loading WorldGroups ---------------------------
[05:01:12] [Server thread/INFO]: [MyPet]    added 'world' to 'default'
[05:01:12] [Server thread/INFO]: [MyPet]    added 'world_nether' to 'default'
[05:01:12] [Server thread/INFO]: [MyPet]    added 'world_the_end' to 'default'
[05:01:12] [Server thread/INFO]: [MyPet]    added 'plotworld' to 'default'
[05:01:12] [Server thread/INFO]: [MyPet]    added 'SurvivalGames' to 'default'
[05:01:12] [Server thread/INFO]: [MyPet]    added 'Spawn2' to 'default'
[05:01:12] [Server thread/INFO]: [MyPet]    added 'world2' to 'default'
[05:01:12] [Server thread/INFO]: [MyPet] -------------------------------------------------
[05:01:12] [Server thread/INFO]: [MyPet] Thank you for buying MyPet-Premium!
[05:01:12] [Server thread/INFO]: [MyPet] version 2.3.6-b511P ENABLED
[05:01:13] [Server thread/INFO]: Done (47.260s)! For help, type "help" or "?"
[05:01:13] [Server thread/INFO]: Timings Reset
[05:01:13] [Server thread/INFO]: (FAWE) Error linking metrics: de.Keyle.MyPet.MyPetPlugin$1@a5763bf
[05:01:13] [Server thread/WARN]: java.lang.NullPointerException
[05:01:13] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit$2.lambda$run$0(FaweBukkit.java:214)
[05:01:13] [Server thread/WARN]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[05:01:13] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit$2.run(FaweBukkit.java:199)
[05:01:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[05:01:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[05:01:13] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
[05:01:13] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:01:13] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[05:01:13] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[05:01:13] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**How to replicate**:

Start server.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by andris155** [comment]
Fix in the latest version.
