### ISSUE TITLE
Possibly major memory leak when using web interface schematic uploading

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#743]
used http://empcraft.com/fawe/index.php thrice on a reasonably-sized schematic (300x300).

Upon attempting to paste the third time the server crashed: https://hastebin.com/ijutudalef.sql

```[23:28:50] [Server thread/INFO]: dordsor21 issued server command: //schematic load url:SCHEMATIC_URL_THING#_REDACTED
[23:28:56] [Server thread/INFO]: dordsor21 issued server command: //paste
[23:28:59] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) ~[?:1.8.0_141]
	at java.lang.Thread.start(Thread.java:717) ~[?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378) ~[?:1.8.0_141]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:375) ~[patched_1.12.1.jar:git-Paper-1203]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) ~[patched_1.12.1.jar:git-Paper-1203]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) ~[patched_1.12.1.jar:git-Paper-1203]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[patched_1.12.1.jar:git-Paper-1203]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1203]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]```

**Comment by dordsor21** [comment]
seems to be fixed now.
