### ISSUE TITLE
Java 9 support for VoxelSniper.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#750]
Java 9
VoxelSniper-5.171
FastAsyncVoxelSniper v17.09.24-c3d12f1-908-16.6.5
Paper dev 1220 (Spigot 1.12.2)
```
[02:53:14] [Server thread/ERROR]: Could not load 'plugins/VoxelSniper-5.171.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:309) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1220]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1220]
	... 6 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:89) ~[patched_1.12.2.jar:git-Paper-1220]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1220]
	... 6 more
```
```
[02:53:15] [Server thread/INFO]: [FastAsyncVoxelSniper] Enabling FastAsyncVoxelSniper v17.09.24-c3d12f1-908-16.6.5
[02:53:15] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
[02:53:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[02:53:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328)
[02:53:15] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.favs.Favs.onEnable(Favs.java:48)
[02:53:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:53:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[02:53:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[02:53:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386)
[02:53:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335)
[02:53:15] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226)
[02:53:15] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[02:53:15] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)
[02:53:15] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
[02:53:15] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[02:53:15] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[02:53:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67)
[02:53:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127)
[02:53:15] [Server thread/WARN]: 	... 10 more
[02:53:15] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
[02:53:15] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
[02:53:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[02:53:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:89)
[02:53:15] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
[02:53:15] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
[02:53:15] [Server thread/WARN]: 	... 14 more
[02:53:15] [Server thread/INFO]: (FAWE) ====== INSTALL VOXELSNIPER ======
[02:53:15] [Server thread/INFO]: (FAWE) FAVS requires VoxelSniper to function correctly
[02:53:15] [Server thread/INFO]: (FAWE) Info: https://github.com/boy0001/FastAsyncWorldedit/releases/
[02:53:15] [Server thread/INFO]: (FAWE) ===============================
```

**Comment by boy0001** [comment]
Update VoxelSniper.
