### ISSUE TITLE
FAWE errors with low memory

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#751]
**Debug paste link**:
https://hastebin.com/dodekokixu

**Description of the problem:**
There is a problem in FAWE when the server almost runs out of RAM.
This appears if a player leaves the server:
```
[21:44:03] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to FastAsyncWorldEdit v17.09.24-c3d12f1-908-16.6.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[paper.jar:git-Paper-"9c79dd3"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper.jar:git-Paper-"9c79dd3"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper.jar:git-Paper-"9c79dd3"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [paper.jar:git-Paper-"9c79dd3"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [paper.jar:git-Paper-"9c79dd3"]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:423) [paper.jar:git-Paper-"9c79dd3"]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1105) [paper.jar:git-Paper-"9c79dd3"]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:290) [paper.jar:git-Paper-"9c79dd3"]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) [paper.jar:git-Paper-"9c79dd3"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940) [paper.jar:git-Paper-"9c79dd3"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [paper.jar:git-Paper-"9c79dd3"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [paper.jar:git-Paper-"9c79dd3"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paper.jar:git-Paper-"9c79dd3"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at com.sk89q.worldedit.session.SessionManager$SessionHolder.access$000(SessionManager.java:310) ~[?:?]
	at com.sk89q.worldedit.session.SessionManager.save(SessionManager.java:223) ~[?:?]
	at com.sk89q.worldedit.session.SessionManager.remove(SessionManager.java:278) ~[?:?]
	at com.sk89q.worldedit.WorldEdit.removeSession(WorldEdit.java:218) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:560) ~[?:?]
	at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:566) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[paper.jar:git-Paper-"9c79dd3"]
	... 13 more
```

**How to replicate**:
Actually no idea. It may be possible that the low RAM has **nothing to do** with the bug.

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
