### ISSUE TITLE
Error when saving schematic - Came in the newer versions

### ISSUE THREAD

**Issue by File14** [boy0001/FastAsyncWorldedit#754]
Hello,

 I can no longer save schematics in the latest update. This is the error I get when saving a schematic:

`[22:33:52 WARN]: java.util.zip.ZipException: Not in GZIP format
[22:33:52 WARN]:        at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
[22:33:52 WARN]:        at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[22:33:52 WARN]:        at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[22:33:52 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicWriter$1.write(SchematicWriter.java:225)
[22:33:52 WARN]:        at com.sk89q.jnbt.NBTOutputStream.writeLazyCompoundTag(NBTOutputStream.java:170)
[22:33:52 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicWriter.stream(SchematicWriter.java:143)
[22:33:52 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicWriter.write(SchematicWriter.java:118)
[22:33:52 WARN]:        at com.boydti.fawe.object.schematic.Schematic.save(Schematic.java:103)
[22:33:52 WARN]:        at com.boydti.fawe.object.schematic.Schematic.save(Schematic.java:89)
[22:33:52 WARN]:        at sv.file14.propractice.command.type.ArenaCommand.onCommand(ArenaCommand.java:208)
[22:33:52 WARN]:        at sv.file14.propractice.command.SimpleCommand.onCommand(SimpleCommand.java:30)
[22:33:52 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:33:52 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:33:52 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
[22:33:52 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392)
[22:33:52 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227)
[22:33:52 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:33:52 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:33:52 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:33:52 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:33:52 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[22:33:52 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[22:33:52 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[22:33:52 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[22:33:52 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[22:33:52 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[22:33:52 WARN]:        at java.lang.Thread.run(Unknown Source)`

Debugpaste: https://hastebin.com/icunokugev

I use this method:
`		new com.boydti.fawe.object.schematic.Schematic(new CuboidRegion(new BukkitWorld(player.getWorld()), min, max)).save(schematicFile, ClipboardFormat.SCHEMATIC);`

**Comment by boy0001** [comment]
Sorry, fixed.
