### ISSUE TITLE
IllegalAccessError: tried to access method com.sk89q.jnbt.CompoundTagBuilder.<init>(Ljava/util/Map;)V from class com.sk89q.jnbt.CompoundTag

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#771]
FAWE dev 928
WorldEdit dev 3709

```
[22:03:33] [Craft Scheduler Thread - 64/INFO]: WorldEdit: player (in "spawn"): /paste - Position: (-54.0, 141.0, -35.0)
[22:03:34] [Craft Scheduler Thread - 64/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.IllegalAccessError: tried to access method com.sk89q.jnbt.CompoundTagBuilder.<init>(Ljava/util/Map;)V from class com.sk89q.jnbt.CompoundTag
	at com.sk89q.jnbt.CompoundTag.createBuilder(CompoundTag.java:64) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.function.entity.ExtentEntityCopy.transformNbtData(ExtentEntityCopy.java:140) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.function.entity.ExtentEntityCopy.apply(ExtentEntityCopy.java:111) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.function.visitor.EntityVisitor.resume(EntityVisitor.java:70) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:68) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:322) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:68) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:402) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:245) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383) [FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468) [FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:226) [FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:254) [FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:301) [FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:465) [FastAsyncWorldEdit-bukkit-17.10.09-b2395f7-929-17.0.12.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1239]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1239]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1239]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by N0tMyFaultOG** [comment]
Update fawe & favs
If this is an issue still, comment below.
