### ISSUE TITLE
max values are being reset when setting them to higher values

### ISSUE THREAD

**Issue by eirikh1996** [boy0001/FastAsyncWorldedit#781]
# Bug report

**Debug paste link**:
https://hastebin.com/lusikoxobi

**Description of the problem:**
When trying to increase some of the max values in config to allow more changes, each time I startup or reload the server, these values are instead being reset to the default values.
[09:07:39] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set int field com.boydti.fawe.config.Settings$LIMITS.MAX_CHANGES to java.lang.Long
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Config.set(Config.java:75)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Config.load(Config.java:95)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Settings.reload(Settings.java:395)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.setupConfigs(Fawe.java:497)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.<init>(Fawe.java:296)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.set(Fawe.java:263)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:101)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:73)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
[09:07:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[09:07:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[09:07:39] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[09:07:39] [Server thread/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m Failed to set config option: limits.default.max-changes: 50000000000 | com.boydti.fawe.config.Settings$LIMITS@6d523ae7 | Settings.yml[m
[09:07:39] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set int field com.boydti.fawe.config.Settings$LIMITS.MAX_CHECKS to java.lang.Long
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Config.set(Config.java:75)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Config.load(Config.java:95)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Settings.reload(Settings.java:395)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.setupConfigs(Fawe.java:497)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.<init>(Fawe.java:296)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.set(Fawe.java:263)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:101)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:73)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
[09:07:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[09:07:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[09:07:39] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[09:07:39] [Server thread/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m Failed to set config option: limits.default.max-checks: 50000000000 | com.boydti.fawe.config.Settings$LIMITS@6d523ae7 | Settings.yml[m
[09:07:39] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set int field com.boydti.fawe.config.Settings$LIMITS.MAX_FAILS to java.lang.Long
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Config.set(Config.java:75)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Config.load(Config.java:95)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Settings.reload(Settings.java:395)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.setupConfigs(Fawe.java:497)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.<init>(Fawe.java:296)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.set(Fawe.java:263)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:101)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:73)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
[09:07:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[09:07:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[09:07:39] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[09:07:39] [Server thread/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m Failed to set config option: limits.default.max-fails: 50000000000 | com.boydti.fawe.config.Settings$LIMITS@6d523ae7 | Settings.yml[m
[09:07:39] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set int field com.boydti.fawe.config.Settings$LIMITS.MAX_ENTITIES to java.lang.Long
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Unknown Source)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Config.set(Config.java:75)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Config.load(Config.java:95)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.config.Settings.reload(Settings.java:395)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.setupConfigs(Fawe.java:497)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.<init>(Fawe.java:296)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.set(Fawe.java:263)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:101)
[09:07:39] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:73)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
[09:07:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
[09:07:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[09:07:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[09:07:39] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[09:07:39] [Server thread/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m Failed to set config option: limits.default.max-entities: 133700000000 | com.boydti.fawe.config.Settings$LIMITS@6d523ae7 | Settings.yml[m**How to replicate**:
set the max values to a value above the default values.
start the server.
watch as they are being reset to default values
 **Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
It's stored as a 32-bit integer, so the number you are entering is too large. Just use -1 to default to the maximum value.
