### ISSUE TITLE
Exception with DiskOptimizedClipboard

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#791]
FastAsyncWorldEdit dev 940
WorldEdit dev 3719
Paper dev 1253 (Spigot 1.12.2)

```
[10:54:23] [Server thread/WARN]: java.lang.Exception
[10:54:23] [Server thread/WARN]: 	at com.boydti.fawe.util.MainUtil.stacktrace(MainUtil.java:198)
[10:54:23] [Server thread/WARN]: 	at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.close(DiskOptimizedClipboard.java:287)
[10:54:23] [Server thread/WARN]: 	at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.close(BlockArrayClipboard.java:119)
[10:54:23] [Server thread/WARN]: 	at com.sk89q.worldedit.session.ClipboardHolder.close(ClipboardHolder.java:134)
[10:54:23] [Server thread/WARN]: 	at com.sk89q.worldedit.LocalSession.setClipboard(LocalSession.java:796)
[10:54:23] [Server thread/WARN]: 	at com.sk89q.worldedit.session.SessionManager.save(SessionManager.java:224)
[10:54:23] [Server thread/WARN]: 	at com.sk89q.worldedit.session.SessionManager.remove(SessionManager.java:278)
[10:54:23] [Server thread/WARN]: 	at com.sk89q.worldedit.WorldEdit.removeSession(WorldEdit.java:218)
[10:54:23] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:560)
[10:54:23] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:566)
[10:54:23] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor995.execute(Unknown Source)
[10:54:23] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[10:54:23] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[10:54:23] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:54:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[10:54:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[10:54:23] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:423)
[10:54:23] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1146)
[10:54:23] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:342)
[10:54:23] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184)
[10:54:23] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940)
[10:54:23] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[10:54:23] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[10:54:23] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[10:54:23] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:54:31] [Finalizer/WARN]: java.lang.Exception
[10:54:31] [Finalizer/WARN]: 	at com.boydti.fawe.util.MainUtil.stacktrace(MainUtil.java:198)
[10:54:31] [Finalizer/WARN]: 	at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.close(DiskOptimizedClipboard.java:287)
[10:54:31] [Finalizer/WARN]: 	at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.finalize(DiskOptimizedClipboard.java:282)
[10:54:31] [Finalizer/WARN]: 	at java.lang.System$2.invokeFinalize(System.java:1270)
[10:54:31] [Finalizer/WARN]: 	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
[10:54:31] [Finalizer/WARN]: 	at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
[10:54:31] [Finalizer/WARN]: 	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)
```

**Comment by boy0001** [comment]
Updating will resolve this, sorry.
