### ISSUE TITLE
corrupt chunk nukkit

### ISSUE THREAD

**Issue by PhanaticD** [boy0001/FastAsyncWorldedit#792]
saw this in my log server froze

```
13:41:26 [ERROR] Error while unloading a chunk: java.lang.RuntimeException: java.util.ConcurrentModificationException
13:41:26 [ALERT] java.lang.RuntimeException: java.util.ConcurrentModificationException
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:279)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2681)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2641)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2939)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2917)
        at cn.nukkit.level.Level.doTick(Level.java:769)
        at cn.nukkit.Server.checkTickUpdates(Server.java:927)
        at cn.nukkit.Server.tick(Server.java:1002)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:470)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.util.ConcurrentModificationException
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211)
        at java.util.TreeMap$KeyIterator.next(TreeMap.java:1265)
        at cn.nukkit.level.Level.getPendingBlockUpdates(Level.java:1302)
        at cn.nukkit.level.Level.getPendingBlockUpdates(Level.java:1291)
        at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:411)
        at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:143)
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:277)
        ... 11 more

13:41:28 [ALERT] java.lang.NullPointerException
        at java.util.TreeMap.rotateLeft(TreeMap.java:2224)
        at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2291)
        at java.util.TreeMap.put(TreeMap.java:582)
        at java.util.TreeSet.add(TreeSet.java:255)
        at cn.nukkit.level.Level.scheduleUpdate(Level.java:1269)
        at cn.nukkit.level.format.anvil.Chunk.<init>(Chunk.java:191)
        at cn.nukkit.level.format.anvil.Chunk.fromBinary(Chunk.java:257)
        at cn.nukkit.level.format.anvil.RegionLoader.unserializeChunk(RegionLoader.java:79)
        at cn.nukkit.level.format.anvil.RegionLoader.readChunk(RegionLoader.java:68)
        at cn.nukkit.level.format.anvil.Anvil.loadChunk(Anvil.java:239)
        at cn.nukkit.level.format.anvil.Anvil.getChunk(Anvil.java:317)
        at cn.nukkit.level.format.anvil.Anvil.getChunk(Anvil.java:26)
        at cn.nukkit.level.Level.loadChunk(Level.java:2576)
        at cn.nukkit.level.Level.getChunk(Level.java:2289)
        at com.boydti.fawe.nukkit.optimization.queue.NukkitChunk.getNewChunk(NukkitChunk.java:57)
        at com.boydti.fawe.nukkit.optimization.queue.NukkitChunk.getNewChunk(NukkitChunk.java:20)
        at com.boydti.fawe.example.CharFaweChunk.getChunk(CharFaweChunk.java:59)
        at com.boydti.fawe.nukkit.optimization.queue.NukkitChunk.start(NukkitChunk.java:67)
        at com.boydti.fawe.example.MappedFaweQueue.start(MappedFaweQueue.java:203)
        at com.boydti.fawe.example.WeakFaweQueueMap.next(WeakFaweQueueMap.java:173)
        at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:199)
        at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:164)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:283)
        at cn.nukkit.Server.tick(Server.java:999)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:470)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

13:41:28 [ERROR] Corrupted chunk detected
```

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
