### ISSUE TITLE
Shulker box bug

### ISSUE THREAD

**Issue by TerZer** [boy0001/FastAsyncWorldedit#793]
First of all Shulker box not saving items with copy pasting trough API. Second of all, shulker should be let to place in air, you can do that easily, but here comes the crash:

`[01:38:13] [Server thread/INFO]: Attempted to place a tile entity (net.minecraft.server.v1_12_R1.TileEntityShulkerBox@6c3164c2) at 41,154,58 (AIR) where there was no entity tile!
[01:38:13] [Server thread/INFO]: Chunk coordinates: 32,48
[01:38:13] [Server thread/WARN]: java.lang.Exception
[01:38:13] [Server thread/WARN]:     at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.getNewChunk(BukkitChunk_1_12.java:162)
[01:38:13] [Server thread/WARN]:     at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.getNewChunk(BukkitChunk_1_12.java:49)
[01:38:13] [Server thread/WARN]:     at com.boydti.fawe.example.CharFaweChunk.getChunk(CharFaweChunk.java:59)
[01:38:13] [Server thread/WARN]:     at com.boydti.fawe.bukkit.v1_12.BukkitChunk_1_12.start(BukkitChunk_1_12.java:208)
[01:38:13] [Server thread/WARN]:     at com.boydti.fawe.example.MappedFaweQueue.start(MappedFaweQueue.java:203)
[01:38:13] [Server thread/WARN]:     at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:137)
[01:38:13] [Server thread/WARN]:     at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:199)
[01:38:13] [Server thread/WARN]:     at com.boydti.fawe.bukkit.v1_12.BukkitQueue_1_12.next(BukkitQueue_1_12.java:426)
[01:38:13] [Server thread/WARN]:     at com.boydti.fawe.util.SetQueue.flush(SetQueue.java:272)
[01:38:13] [Server thread/WARN]:     at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1357)
[01:38:13] [Server thread/WARN]:     at lt.TerZer.DangausLegendos.Duomenys.Sala.replaceBlocks(Sala.java:243)
[01:38:13] [Server thread/WARN]:     at lt.TerZer.DangausLegendos.Mapping.Sorter$1.run(Sorter.java:77)`

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
