### ISSUE TITLE
FAWE not registering on 1.12.2

### ISSUE THREAD

**Issue by GabbyLorelai** [boy0001/FastAsyncWorldedit#798]
# Bug report

**Description of the problem:**
FAWE registers as being on the server, but throws constant errors.

**Checklist**:
- [] I included a `/fawe debugpaste` link ((didn't even work when I tried to))
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

https://gist.github.com/GabbyLorelai/be39c5c0605049d93d65d1a759d5add2

FAWE - FastAsyncWorldEdit-sponge111-17.11.13-12580b5-945-18.0.2.jar
SpongeForge - spongeforge-1.12.2-2529-7.0.0-BETA-2732.jar

**Comment by Mr-Krab** [comment]
[09:08:42] [Server thread/INFO] [nucleus]: Server выполнил команду: /sponge version
[09:08:42] [Server thread/INFO]: SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: 7.0.0-SNAPSHOT-963ff06
    SpongeForge: 1.12.2-2555-7.0.0-BETA-2774
    Minecraft Forge: 14.23.1.2555

[09:06:52] [Server thread/INFO] [nucleus]: Server выполнил команду: /fawe
> Exception in thread "Server Watchdog" Dec 15, 2017 9:06:52 AM com.sk89q.worldedit.util.eventbus.EventBus dispatch
SEVERE: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@709b6877 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75)
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
        at com.sk89q.worldedit.sponge.SpongePlatform$1.process(SpongePlatform.java:126)
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342)
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321)
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
        ... 11 more
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/entity/spawn/SpawnCause
        at com.sk89q.worldedit.sponge.SpongeWorld.<clinit>(SpongeWorld.java:257)
        at com.sk89q.worldedit.sponge.adapter.impl.Sponge_Dev_Impl.getWorld(Sponge_Dev_Impl.java:298)
        at com.sk89q.worldedit.sponge.SpongePlatform.getWorlds(SpongePlatform.java:87)
        at com.sk89q.worldedit.internal.ServerInterfaceAdapter.getWorlds(ServerInterfaceAdapter.java:77)
        at com.boydti.fawe.wrappers.FakePlayer.<init>(FakePlayer.java:61)
        at com.boydti.fawe.object.FawePlayer.wrap(FawePlayer.java:112)
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:461)
        ... 17 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.event.cause.entity.spawn.SpawnCause
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 24 more
Caused by: java.lang.NullPointerException

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
