### ISSUE TITLE
Plugin Not Loading

### ISSUE THREAD

**Issue by PantherMan594** [boy0001/FastAsyncWorldedit#8]
Hi,
The server shuts down immediately after loading the plugin, with the following error:
```
[00:31:11 INFO]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v1.2.1
[00:31:11 INFO]: [WorldEdit] Loading WorldEdit v6.1.1-SNAPSHOT;3386-025591e6
[00:31:11 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.2.1
[00:31:11 WARN]: java.lang.NullPointerException
[00:31:11 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.getQueue(FaweBukkit.java:137)
[00:31:11 WARN]:        at com.boydti.fawe.Fawe.<init>(Fawe.java:110)
[00:31:11 WARN]:        at com.boydti.fawe.Fawe.set(Fawe.java:76)
[00:31:11 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.onEnable(FaweBukkit.java:57)
[00:31:11 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[00:31:11 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[00:31:11 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[00:31:11 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:355)
[00:31:11 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:315)
[00:31:11 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:206)
[00:31:11 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:564)
[00:31:11 WARN]:        at java.lang.Thread.run(Thread.java:745)
```
Using version 3.3.0 on Spigot 1.9. Running with only FastAsyncWorldEdit and WorldEdit.

**Comment by boy0001** [comment]
https://www.spigotmc.org/resources/free-fast-async-worldedit-%CE%B2.13932/download?version=72711
