### ISSUE TITLE
BStats not being stopped on Bukkit plugin disable

### ISSUE THREAD

**Issue by aikar** [boy0001/FastAsyncWorldedit#800]
When using /reload, Bstats will trigger [10:13:02 WARN]: Exception in thread "Timer-4" org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[10:13:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:413)
[10:13:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:130)
[10:13:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:113)
[10:13:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:96)
[10:13:02 WARN]:        at com.boydti.fawe.bukkit.util.BukkitTaskMan.task(BukkitTaskMan.java:41)
[10:13:02 WARN]:        at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:405)
[10:13:02 WARN]:        at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:284)
[10:13:02 WARN]:        at com.boydti.fawe.util.metrics.BStats.submitData(BStats.java:246)
[10:13:02 WARN]:        at com.boydti.fawe.util.metrics.BStats.access$200(BStats.java:37)
[10:13:02 WARN]:        at com.boydti.fawe.util.metrics.BStats$1.run(BStats.java:181)
[10:13:02 WARN]:        at java.util.TimerThread.mainLoop(Timer.java:555)
[10:13:02 WARN]:        at java.util.TimerThread.run(Timer.java:505)

When the plugin is disabled, BStats needs to be stopped. i do not see an onDisable in BukkitMain.

**Comment by Combustible** [comment]
I get this same log message on my Spigot 1.12.2 servers as well with the latest FAWE/WorldEdit versions.

**Comment by ryandw11** [comment]
I am also having errors with this. My log: https://hastebin.com/gitaquluvu.md

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.

**Comment by aikar** [comment]
@N0tMyFaultOG Please reopen, issue is still present.

**Comment by aikar** [comment]
Well specifically "[19:53:20 ERROR]: Nag author: 'Empire92' of 'WorldEdit' about the following: This plugin is not properly shutting down its async tasks when it is being reloaded.  This may cause conflicts with the newly loaded version of the plugin" which I'm fairly sure is same issue.
