### ISSUE TITLE
Update Broke FAWE

### ISSUE THREAD

**Issue by leefromvt** [boy0001/FastAsyncWorldedit#834]
after restarting from update i receive a fatal error when running any FAWE world edit command
https://i.gyazo.com/562ed1ae9cfad6de0f9ad7a870083bdb.png

**Comment by leefromvt** [comment]
This error is from the command /thru
https://i.gyazo.com/6f504c6038f6cace315ce909dca2f47d.png

**Comment by Acornmc** [comment]
I assume //pos1 still works? I also assume that //copy and //up also don't work? 
There's a fix on the discord. Read #FAWE. The download link for the new version is pinned. https://discord.gg/X5DCaNq

**Comment by rayyates** [comment]
After yesterdays update, I'm getting errors on all my servers and FAWE is broken.  Here is the console output.

[20:16:37 INFO]: Kiqkinas issued server command: //move 20 up
[20:16:37 INFO]: ====== NO NMS BLOCK PLACER FOUND ======
[20:16:37 INFO]: FAWE couldn't find a fast block placer
[20:16:37 INFO]: Bukkit version: git-Spigot-549c1fa-8c37e2e (MC: 1.12.2)
[20:16:37 INFO]: NMS label: BukkitMain
[20:16:37 INFO]: Fallback placer: class com.boydti.fawe.bukkit.v0.BukkitQueue_All
[20:16:37 INFO]: =======================================
[20:16:37 INFO]: Download the version of FAWE for your platform
[20:16:37 INFO]:  - http://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target
[20:16:37 INFO]: =======================================
[20:16:37 WARN]: java.lang.NoClassDefFoundError: org/bukkit/World$ChunkLoadCallback
[20:16:37 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.getVersion(FaweBukkit.java:620)
[20:16:37 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.getQueue(FaweBukkit.java:651)
[20:16:37 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.getNewQueue(FaweBukkit.java:435)
[20:16:37 WARN]:        at com.boydti.fawe.util.SetQueue.getNewQueue(SetQueue.java:248)
[20:16:37 WARN]:        at com.boydti.fawe.object.FawePlayer.getFaweQueue(FawePlayer.java:368)
[20:16:37 WARN]:        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:273)
[20:16:37 WARN]:        at com.boydti.fawe.util.EditSessionBuilder.build(EditSessionBuilder.java:192)
[20:16:37 WARN]:        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1300)
[20:16:37 WARN]:        at com.sk89q.worldedit.internal.command.WorldEditBinding.getEditSession(WorldEditBinding.java:104)
[20:16:37 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:16:37 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:16:37 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:16:37 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[20:16:37 WARN]:        at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167)
[20:16:37 WARN]:        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:222)
[20:16:37 WARN]:        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[20:16:37 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383)
[20:16:37 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468)
[20:16:37 WARN]:        at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232)
[20:16:37 WARN]:        at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260)
[20:16:37 WARN]:        at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307)
[20:16:37 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:465)
[20:16:37 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:16:37 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:16:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:16:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:16:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:16:37 WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.World$ChunkLoadCallback
[20:16:37 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[20:16:37 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[20:16:37 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[20:16:37 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[20:16:37 WARN]:        ... 27 more
[20:16:37 INFO]: =======================================
[20:16:37 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.ClassNotFoundException: org.bukkit.World$ChunkLoadCallback
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at com.boydti.fawe.bukkit.FaweBukkit.getNewQueue(FaweBukkit.java:463) ~[FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.boydti.fawe.util.SetQueue.getNewQueue(SetQueue.java:248) ~[FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.boydti.fawe.object.FawePlayer.getFaweQueue(FawePlayer.java:368) ~[FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:273) ~[FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.boydti.fawe.util.EditSessionBuilder.build(EditSessionBuilder.java:192) ~[FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1300) ~[FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.sk89q.worldedit.internal.command.WorldEditBinding.getEditSession(WorldEditBinding.java:104) ~[FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[worldedit-bukkit-6.1.8-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:222) ~[FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383) [FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468) [FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232) [FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260) [FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307) [FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:465) [FastAsyncWorldEdit-bukkit-17.06.28-5d7f0b1-737-13.4.2.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[20:16:38 INFO]: No NMS placer found, see console!
[20:16:38 INFO]: (FAWE) No NMS placer found, see console!

**Comment by Panossa** [comment]
Guys, just download the new FAWE version that got released today. ^^'
