### ISSUE TITLE
Issue executing /butcher

### ISSUE THREAD

**Issue by Fargus5** [boy0001/FastAsyncWorldedit#840]
[17:39:31] [Server thread/INFO]: Fargus5 issued server command: /butcher
[17:39:31] [Craft Scheduler Thread - 72/INFO]: ====== NO NMS BLOCK PLACER FOUND ======
[17:39:31] [Craft Scheduler Thread - 72/INFO]: FAWE couldn't find a fast block placer
[17:39:31] [Craft Scheduler Thread - 72/INFO]: Bukkit version: git-Spigot-8cbfc85-202da97 (MC: 1.12)
[17:39:31] [Craft Scheduler Thread - 72/INFO]: NMS label: BukkitMain
[17:39:31] [Craft Scheduler Thread - 72/INFO]: Fallback placer: class com.boydti.fawe.bukkit.v0.BukkitQueue_All
[17:39:31] [Craft Scheduler Thread - 72/INFO]: =======================================
[17:39:31] [Craft Scheduler Thread - 72/INFO]: Download the version of FAWE for your platform
[17:39:31] [Craft Scheduler Thread - 72/INFO]:  - http://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target
[17:39:31] [Craft Scheduler Thread - 72/INFO]: =======================================
[17:39:31] [Craft Scheduler Thread - 72/WARN]: java.lang.NoClassDefFoundError: org/bukkit/World$ChunkLoadCallback
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.getVersion(FaweBukkit.java:620)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.getQueue(FaweBukkit.java:651)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.getNewQueue(FaweBukkit.java:435)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.util.SetQueue.getNewQueue(SetQueue.java:248)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.object.FawePlayer.getFaweQueue(FawePlayer.java:368)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.sk89q.worldedit.EditSession.<init>(EditSession.java:273)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.util.EditSessionBuilder.build(EditSessionBuilder.java:192)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1300)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.sk89q.worldedit.command.UtilityCommands.butcher(UtilityCommands.java:460)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:245)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:465)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.World$ChunkLoadCallback
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	... 26 more
[17:39:31] [Craft Scheduler Thread - 72/INFO]: =======================================
[17:39:31] [Craft Scheduler Thread - 72/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.ClassNotFoundException: org.bukkit.World$ChunkLoadCallback
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
	at com.boydti.fawe.bukkit.FaweBukkit.getNewQueue(FaweBukkit.java:463) ~[FastAsyncWorldEdit.jar:?]
	at com.boydti.fawe.util.SetQueue.getNewQueue(SetQueue.java:248) ~[FastAsyncWorldEdit.jar:?]
	at com.boydti.fawe.object.FawePlayer.getFaweQueue(FawePlayer.java:368) ~[FastAsyncWorldEdit.jar:?]

**Comment by Fargus5** [comment]
] [DEBUG] Auth information found for user fargus5
[17:37:00] [Server thread/INFO]: CONSOLE issued server command: /heal Fargus5
[17:37:00] [Server thread/INFO]: Fargus5 e' stato curato.
[17:37:05] [Server thread/INFO]: [CityWorld][PasteProvider] Problem loading PhatLoots, could not find it
[17:37:05] [Server thread/INFO]: [CityWorld][PasteProvider] Found WorldEdit v6.1.7-SNAPSHOT;3677-000c238, enabling its schematics
[17:37:05] [Server thread/INFO]: [CityWorld][WorldEdit] Loaded 0 schematic(s) for world esiliato
[17:37:08] [Server thread/INFO]: (FAWE) [FAWE `tick-limiter`] Detected and cancelled physics  lag source at Location{world=CraftWorld{name=esiliato},x=-278.0,y=14.0,z=-270.0,pitch=0.0,yaw=0.0}
[17:37:33] [Server thread/INFO]: (FAWE) [FAWE `tick-limiter`] Detected and cancelled physics  lag source at Location{world=CraftWorld{name=esiliato},x=28.0,y=10.0,z=-531.0,pitch=0.0,yaw=0.0}
[17:38:11] [Server thread/INFO]: (FAWE) [FAWE `tick-limiter`] Detected and cancelled physics  lag source at Location{world=CraftWorld{name=esiliato},x=411.0,y=13.0,z=-385.0,pitch=0.0,yaw=0.0}
[17:38:44] [Server thread/INFO]: (FAWE) [FAWE `tick-limiter`] Detected and cancelled physics  lag source at Location{world=CraftWorld{name=esiliato},x=584.0,y=38.0,z=12.0,pitch=0.0,yaw=0.0}
[17:39:07] [Server thread/INFO]: (FAWE) [FAWE `tick-limiter`] Detected and cancelled physics  lag source at Location{world=CraftWorld{name=esiliato},x=851.0,y=73.0,z=93.0,pitch=0.0,yaw=0.0}
[17:39:12] [Server thread/INFO]: Fargus5 issued server command: /v
[17:39:20] [Server thread/INFO]: Fargus5 issued server command: /spawnmob zombie 5
[17:39:23] [Server thread/INFO]: Fargus5 issued server command: /v
[17:39:31] [Server thread/INFO]: Fargus5 issued server command: /butcher
[17:39:31] [Craft Scheduler Thread - 72/INFO]: ====== NO NMS BLOCK PLACER FOUND ======
[17:39:31] [Craft Scheduler Thread - 72/INFO]: FAWE couldn't find a fast block placer
[17:39:31] [Craft Scheduler Thread - 72/INFO]: Bukkit version: git-Spigot-8cbfc85-202da97 (MC: 1.12)
[17:39:31] [Craft Scheduler Thread - 72/INFO]: NMS label: BukkitMain
[17:39:31] [Craft Scheduler Thread - 72/INFO]: Fallback placer: class com.boydti.fawe.bukkit.v0.BukkitQueue_All
[17:39:31] [Craft Scheduler Thread - 72/INFO]: =======================================
[17:39:31] [Craft Scheduler Thread - 72/INFO]: Download the version of FAWE for your platform
[17:39:31] [Craft Scheduler Thread - 72/INFO]:  - http://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target
[17:39:31] [Craft Scheduler Thread - 72/INFO]: =======================================
[17:39:31] [Craft Scheduler Thread - 72/WARN]: java.lang.NoClassDefFoundError: org/bukkit/World$ChunkLoadCallback
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.getVersion(FaweBukkit.java:620)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.getQueue(FaweBukkit.java:651)
[17:39:31] [Craft Scheduler Thread - 72/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.get

**Comment by Wynnevir** [comment]
Exact problem I posted 10 min ago. I hope it gets a fix :( Does it throw that error for your copy and paste commands too?

**Comment by dordsor21** [comment]
Should be fixed in latest build.

**Comment by Fargus5** [comment]
Where we can find the link for the download of the latest build?
