### ISSUE TITLE
Stream Ended Prematurely error on /u

### ISSUE THREAD

**Issue by zeronerve** [boy0001/FastAsyncWorldedit#842]
**Debug paste link**:

links.config_yml: https://hastebin.com/tomucoheri
links.messages_yml: https://hastebin.com/ahifuyacuk
links.commands_yml: https://hastebin.com/merefiraho
links.latest_log: https://hastebin.com/afufeginax

# Server Information
server.platform: bukkit
server.plugins: 
 - FastAsyncWorldEdit: 17.12.26-994856b-952-18.0.9
 - PermissionsEx: 1.23.4
 - ProtocolSupport: 4.29-dev
 - FastAsyncVoxelSniper: 17.12.26-994856b-952-18.0.9
 - WorldEdit: 6.1.7;dd00bb1
 - PlotSquared: 17.12.09-59557cf-1945
 - Multiverse-Core: 2.5-b719
 - WorldGuard: 6.2.1;84bc322
 - Multiverse-NetherPortals: 2.4-b530
 - Multiverse-Portals: 2.5.0-b751
 - VoxelSniper: 5.171.0-SNAPSHOT
server.version: git-Paper-1286 (MC: 1.12.2) / 1.12.2-R0.1-SNAPSHOT

# YAY! Now, let's see what we can find in your JVM
memory.free: 2453788048
memory.max: 3665821696
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_151'
os.arch: 'amd64'
os.name: 'Linux'
os.version: '4.9.68-x86_64-linode89'

# Okay :D Great. You are now ready to create your bug report!
# You can do so at https://github.com/boy0001/FastAsyncWorldedit/issues

**Description of the problem:**
Getting the following error when I use /u to undo...
[19:40:02] [Server thread/WARN]: java.io.EOFException: Stream ended prematurely
[19:40:02] [Server thread/WARN]: 	at net.jpountz.lz4.LZ4BlockInputStream.readFully(LZ4BlockInputStream.java:207)
[19:40:02] [Server thread/WARN]: 	at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:137)
[19:40:02] [Server thread/WARN]: 	at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:104)
[19:40:02] [Server thread/WARN]: 	at net.jpountz.lz4.LZ4BlockInputStream.readFully(LZ4BlockInputStream.java:205)
[19:40:02] [Server thread/WARN]: 	at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:137)
[19:40:02] [Server thread/WARN]: 	at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:104)
[19:40:02] [Server thread/WARN]: 	at net.jpountz.lz4.LZ4BlockInputStream.readFully(LZ4BlockInputStream.java:205)
[19:40:02] [Server thread/WARN]: 	at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:137)
[19:40:02] [Server thread/WARN]: 	at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:89)
[19:40:02] [Server thread/WARN]: 	at java.io.FilterInputStream.read(FilterInputStream.java:83)
[19:40:02] [Server thread/WARN]: 	at com.boydti.fawe.object.changeset.FaweStreamChangeSet.readHeader(FaweStreamChangeSet.java:238)
[19:40:02] [Server thread/WARN]: 	at com.boydti.fawe.object.changeset.DiskStorageHistory.getBlockIS(DiskStorageHistory.java:328)
[19:40:02] [Server thread/WARN]: 	at com.boydti.fawe.object.changeset.FaweStreamChangeSet.getBlockIterator(FaweStreamChangeSet.java:408)
[19:40:02] [Server thread/WARN]: 	at com.boydti.fawe.object.changeset.FaweStreamChangeSet.getIterator(FaweStreamChangeSet.java:685)
[19:40:02] [Server thread/WARN]: 	at com.boydti.fawe.object.changeset.FaweStreamChangeSet.getIterator(FaweStreamChangeSet.java:522)
[19:40:02] [Server thread/WARN]: 	at com.sk89q.worldedit.function.operation.ChangeSetExecutor.<init>(ChangeSetExecutor.java:59)
[19:40:02] [Server thread/WARN]: 	at com.sk89q.worldedit.function.operation.ChangeSetExecutor.create(ChangeSetExecutor.java:90)
[19:40:02] [Server thread/WARN]: 	at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1308)
[19:40:02] [Server thread/WARN]: 	at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:528)
[19:40:02] [Server thread/WARN]: 	at com.thevoxelbox.voxelsniper.Sniper$3.run(Sniper.java:468)
[19:40:02] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232)
[19:40:02] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260)
[19:40:02] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307)
[19:40:02] [Server thread/WARN]: 	at com.thevoxelbox.voxelsniper.Sniper.undo(Sniper.java:463)
[19:40:02] [Server thread/WARN]: 	at com.thevoxelbox.voxelsniper.command.VoxelUndoCommand.onCommand(VoxelUndoCommand.java:27)
[19:40:02] [Server thread/WARN]: 	at com.thevoxelbox.voxelsniper.VoxelSniperListener.onCommand(VoxelSniperListener.java:76)
[19:40:02] [Server thread/WARN]: 	at com.thevoxelbox.voxelsniper.VoxelSniper.onCommand(VoxelSniper.java:138)
[19:40:02] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:40:02] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[19:40:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:674)
[19:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
[19:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
[19:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[19:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[19:40:02] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:40:02] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[19:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[19:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[19:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[19:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[19:40:02] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**How to replicate**:
use /u

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by zeronerve** [comment]
What I've discovered is that if I try to undo more than the actions I've taken in each session, it throws the error. For instance, if I join, then place 3 blocks, and try /u 4 or /u four times, it throws the error and chats "nothing to undo". It seems like something was amiss in the block placement log - if there is such a thing! The problem may have resolved itself due to the number of edits, but I wanted you guys to know.

**Comment by N0tMyFaultOG** [comment]
Update fawe & favs
If this is an issue still, comment below.
