### ISSUE TITLE
fawe/favs issue

### ISSUE THREAD

**Issue by N0tMyFaultOG** [boy0001/FastAsyncWorldedit#844]
# Bug report

**Debug paste link**:
https://hastebin.com/okazowexip

**Description of the problem:**
By selecting a brush for favs, you have to click with the default items everytime twice, it seems like a confirmation(?) before it brushes the actually stuff. Also I'm not able to undo that stuff, neither with /u, nor with /undo or //undo.
An abstract from the console goes below:

[18:59:30 WARN]: java.lang.IncompatibleClassChangeError: Found interface com.boydti.fawe.object.FaweQueue, but class was expected
[18:59:30 WARN]: at com.thevoxelbox.voxelsniper.Sniper.snipeOnCurrentThread(Sniper.java:381)
[18:59:30 WARN]: at com.thevoxelbox.voxelsniper.Sniper$1$1.run(Sniper.java:151)
[18:59:30 WARN]: at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232)
[18:59:30 WARN]: at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260)
[18:59:30 WARN]: at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307)
[18:59:30 WARN]: at com.thevoxelbox.voxelsniper.Sniper$1.run(Sniper.java:148)
[18:59:30 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[18:59:30 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[18:59:30 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:59:30 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:59:30 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:59:30 WARN]: at java.lang.Thread.run(Thread.java:748)

**How to replicate**:
The issue affects fawe and/or favs.
Take the default vs items (arrow and gunpowder) and set it up, for example /b b, /b 5 and /v 7
You have to click with the items everytime twice, it seems like a confirmation(?) before it brushes the actually stuff.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Try updating FAVS:
http://empcraft.com/fawe/latest.php?favs

**Comment by N0tMyFaultOG** [comment]
Updating FAVS fixed it, well half of it. It doesn't throw out errors anymore, but I'm still not able to undo Voxel's actions, it just says this in console but doesn't do anything ingame. Also /undo and //undo doesn't affect Voxel.

[12:23:59 INFO]: NotMyFault issued server command: /u
[12:23:59 INFO]: [VoxelSniper] Player "NotMyFault" used /u

**Debug paste link:**
https://hastebin.com/wayorituzo
