### ISSUE TITLE
Exception in thread "Timer-5"

### ISSUE THREAD

**Issue by TwanLuttik** [boy0001/FastAsyncWorldedit#860]
i get his error every 15 - 30 minuts 

Spigot Version:
CraftBukkit version git-Spigot-549c1fa-45c8386 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

CONSOLE:
`
> [13:57:51 WARN]: Exception in thread "Timer-5"
> [13:57:51 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
> [13:57:51 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403)
> [13:57:51 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:126)
> [13:57:51 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:109)
> [13:57:51 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:92)
> [13:57:51 WARN]: at com.boydti.fawe.bukkit.util.BukkitTaskMan.task(BukkitTaskMan.java:41)
> [13:57:51 WARN]: at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:405)
> [13:57:51 WARN]: at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:284)
> [13:57:51 WARN]: at com.boydti.fawe.util.metrics.BStats.submitData(BStats.java:246)
> [13:57:51 WARN]: at com.boydti.fawe.util.metrics.BStats.access$200(BStats.java:37)
> [13:57:51 WARN]: at com.boydti.fawe.util.metrics.BStats$1.run(BStats.java:181)
> [13:57:51 WARN]: at java.util.TimerThread.mainLoop(Timer.java:555)
> [13:57:51 WARN]: at java.util.TimerThread.run(Timer.java:505)
`

**Comment by aikar** [comment]
@boy0001 you can fix this by making TaskManager check that the plugin is still enabled (maintain ref to the plugin, dont re look it up)

also
[19:09:01 ERROR]: Nag author: 'Empire92' of 'FastAsyncWorldEdit' about the following: This plugin is not properly shutting down its async tasks when it is being reloaded.  This may cause conflicts with the newly loaded version of the plugin

need to solve that.
