### ISSUE TITLE
Error on SpongeForge for MC 1.12.2

### ISSUE THREAD

**Issue by FallenVFX** [boy0001/FastAsyncWorldedit#867]
# Bug report

**Debug paste link**:
Well this command didn't do anything, no debug came up but no "this command doesn't exist" either. that's with the forge version of it.

with the sponge version:
```
Jan 09, 2018 6:24:26 PM com.sk89q.worldedit.util.eventbus.EventBus dispatch
SEVERE: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@40ca7f9 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75)
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
        at com.sk89q.worldedit.sponge.SpongePlatform$1.process(SpongePlatform.java:130)
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342)
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:322)
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
        ... 11 more
Caused by: java.lang.NullPointerException
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:462)
        ... 17 more
```

**Description of the problem:**
 the plugin doesn't work no matter what I try, world edit works, add this and nothing works. 

**How to replicate**:
try to use this plugin on spongeforge for MC 1.12.2 

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by rouing** [comment]
I too have the same issue.

**Comment by boy0001** [comment]
@rouing 
Update: empcraft.com/fawe/latest.php?sponge112
