### ISSUE TITLE
error with //regen (nukkit)

### ISSUE THREAD

**Issue by PhanaticD** [boy0001/FastAsyncWorldedit#869]
the following occurred when doing a large area

```02:27:32 [CRITICAL] Exception while async task 0 invoking onCompletion
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
        at cn.nukkit.level.Level.setChunk(Level.java:2365)
        at cn.nukkit.level.Level.generateChunkCallback(Level.java:2330)
        at cn.nukkit.level.generator.task.GenerationTask.onCompletion(GenerationTask.java:76)
        at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:83)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:301)
        at cn.nukkit.Server.tick(Server.java:1012)
        at cn.nukkit.Server.tickProcessor(Server.java:807)
        at cn.nukkit.Server.start(Server.java:786)
        at cn.nukkit.Server.<init>(Server.java:473)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)
```

the inside of the plot regenerated after i ran the command a few times, the road area on the outside of the plot did not regenerate even when selecting just a small portion of the road: https://gyazo.com/07fbc982a74575e78a5ae6f766134623

**Comment by PhanaticD** [comment]
I am not sure if this is nukkit or FAWE fault

**Comment by PhanaticD** [comment]
also does not appear to properly regenerate plotsquared roads: https://gyazo.com/07fbc982a74575e78a5ae6f766134623

**Comment by boy0001** [comment]
Okay, so it is a Nukkit bug.
