### ISSUE TITLE
NPE with end crystal

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#88]
Spigot 1.9.2
FAWE 3.4.3

Placed a block of obsidian and an end crystal on top.
Tried to mark it with the wand and got this NPE:

```
[14:23:32 WARN]: java.lang.NullPointerException
[14:23:32 WARN]:        at com.boydti.fawe.config.BBC.format(BBC.java:191)
[14:23:32 WARN]:        at com.boydti.fawe.config.BBC.send(BBC.java:299)
[14:23:32 WARN]:        at com.sk89q.worldedit.regions.selector.CuboidRegionSelector.explainSecondarySelection(CuboidRegionSelector.java:174)
[14:23:32 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager.handleBlockInteract(PlatformManager.java:393)
[14:23:32 WARN]:        at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
[14:23:32 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:23:32 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[14:23:32 WARN]:        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[14:23:32 WARN]:        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[14:23:32 WARN]:        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
[14:23:32 WARN]:        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
[14:23:32 WARN]:        at com.sk89q.worldedit.WorldEdit.handleBlockRightClick(WorldEdit.java:690)
[14:23:32 WARN]:        at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:163)
[14:23:32 WARN]:        at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
[14:23:32 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:23:32 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[14:23:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[14:23:32 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:23:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[14:23:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[14:23:32 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231)
[14:23:32 WARN]:        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482)
[14:23:32 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888)
[14:23:32 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55)
[14:23:32 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11)
[14:23:32 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[14:23:32 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:23:32 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:23:32 WARN]:        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[14:23:32 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[14:23:32 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[14:23:32 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[14:23:32 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[14:23:32 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by boy0001** [comment]
Translation issue, fixed.
