### ISSUE TITLE
java.lang.ClassCastException: com.boydti.fawe.wrappers.PlayerWrapper$9 cannot be cast to java.util.function.Supplier

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#881]
FAWE dev 968 commit https://github.com/boy0001/FastAsyncWorldedit/commit/446dc9c5687068543f9195285328f3f95bbb387b
FAVS dev 968 commit https://github.com/boy0001/FastAsyncWorldedit/commit/446dc9c5687068543f9195285328f3f95bbb387b
WorldEdit dev 3730
VoxelSniper v5.172.0-SNAPSHOT
Paper dev 1304 (Spigot 1.12.2)

@boy0001 Player tried to use a compass to teleport (worldedit /thru | /jumpto).

```
[22:31:16] [Server thread/WARN]: java.lang.ClassCastException: com.boydti.fawe.wrappers.PlayerWrapper$9 cannot be cast to java.util.function.Supplier
[22:31:16] [Server thread/WARN]: 	at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:388)
[22:31:16] [Server thread/WARN]: 	at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:285)
[22:31:16] [Server thread/WARN]: 	at com.boydti.fawe.wrappers.PlayerWrapper.getSolidBlockTrace(PlayerWrapper.java:249)
[22:31:16] [Server thread/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:476)
[22:31:16] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
[22:31:16] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:31:16] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:31:16] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[22:31:16] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[22:31:16] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
[22:31:16] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
[22:31:16] [Server thread/WARN]: 	at com.sk89q.worldedit.WorldEdit.handleArmSwing(WorldEdit.java:665)
[22:31:16] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:146)
[22:31:16] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor253.execute(Unknown Source)
[22:31:16] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[22:31:16] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[22:31:16] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:31:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[22:31:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[22:31:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236)
[22:31:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:203)
[22:31:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199)
[22:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1510)
[22:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:24)
[22:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:5)
[22:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[22:31:16] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:31:16] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[22:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[22:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[22:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[22:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[22:31:16] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mibby** [comment]
https://github.com/boy0001/FastAsyncWorldedit/commit/2448b2fe22768f0bd925a47904d8febd4d5b40f4 seems to fix the issue.
