### ISSUE TITLE
[WorldEdit] An unexpected error occurred while handling a FAWE command

### ISSUE THREAD

**Issue by Rivenze** [boy0001/FastAsyncWorldedit#882]
# Bug report

**Debug paste link**:
https://hastebin.com/finojozoko

**Description of the problem:**
When I type /asc or /desc, this comes up:
java.lang.ClassCastException: com.boydti.fawe.wrappers.PlayerWrapper$4 cannot be cast to java.util.function.Supplier
        at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:388) ~[FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:285) ~[FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at com.boydti.fawe.wrappers.PlayerWrapper.ascendLevel(PlayerWrapper.java:118) ~[FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at com.sk89q.worldedit.command.NavigationCommands.ascend(NavigationCommands.java:85) ~[FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:245) ~[FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383) [FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468) [FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232) [FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260) [FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307) [FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:465) [FastAsyncWorldEdit-bukkit-17.10.16-7a4b7be-936-17.0.19.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**How to replicate**:

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Update the plugin. Duplicate: https://github.com/boy0001/FastAsyncWorldedit/issues/881
