### ISSUE TITLE
//fill: minY <= maxY required

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#883]
**Debug paste link**:
https://hastebin.com/ulamokurav

**Description of the problem:**
//fill is broken

```
[02:25:18] [Craft Scheduler Thread - 884/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.IllegalArgumentException: minY <= maxY required
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[spigot-skygrid.jar:git-TacoSpigot-bdc5adac]
	at com.sk89q.worldedit.function.mask.BoundedHeightMask.<init>(BoundedHeightMask.java:44) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.EditSession.fillXZ(EditSession.java:1568) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.EditSession.fillDirection(EditSession.java:1516) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.command.UtilityCommands.fill(UtilityCommands.java:196) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:245) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:465) [FastAsyncWorldEdit-bukkit18.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:67) [spigot-skygrid.jar:git-TacoSpigot-bdc5adac]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [spigot-skygrid.jar:git-TacoSpigot-bdc5adac]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**How to replicate**:
Use //fill

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of FAWE
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Were you standing above or below the world?

**Comment by L4BORG** [comment]
Neither...

![](http://shrani.si/f/1S/13M/QyLfJD7/untitled.png)

**Comment by NorbiPeti** [comment]
We're having the same problem on *some* worlds. It works in our main world and spawn world, while it doesn't work in a flat world or a backup of the main world... So it's probably not based on the world type, also not related to WorldGuard settings, terrain height or player position.

**Comment by weronicamc** [comment]
I have same issue. Can you help me please? @boy0001 

`[14:53:24 INFO]: WorldEdit: WeronicaMC (in "survival"): /fill water 20 - Position: (895, 65, 1080)
[14:53:24 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.IllegalArgumentException: minY <= maxY required
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot.jar:git-Spigot-99c2a37-3819f8d]
        at com.sk89q.worldedit.function.mask.BoundedHeightMask.<init>(BoundedHeightMask.java:44) ~[worldedit-bukkit-6.1.7.2.jar:?]
        at com.sk89q.worldedit.EditSession.fillXZ(EditSession.java:1486) ~[FastAsyncWorldEdit-bukkit-18.06.10-9144d37-1142-20.1.12.jar:?]
        at com.sk89q.worldedit.EditSession.fillDirection(EditSession.java:1434) ~[FastAsyncWorldEdit-bukkit-18.06.10-9144d37-1142-20.1.12.jar:?]
        at com.sk89q.worldedit.command.UtilityCommands.fill(UtilityCommands.java:173) ~[FastAsyncWorldEdit-bukkit-18.06.10-9144d37-1142-20.1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:247) ~[FastAsyncWorldEdit-bukkit-18.06.10-9144d37-1142-20.1.12.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[FastAsyncWorldEdit-bukkit-18.06.10-9144d37-1142-20.1.12.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383) ~[FastAsyncWorldEdit-bukkit-18.06.10-9144d37-1142-20.1.12.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468) ~[FastAsyncWorldEdit-bukkit-18.06.10-9144d37-1142-20.1.12.jar:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:302) ~[FastAsyncWorldEdit-bukkit-18.06.10-9144d37-1142-20.1.12.jar:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit-18.06.10-9144d37-1142-20.1.12.jar:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit-18.06.10-9144d37-1142-20.1.12.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-99c2a37-3819f8d]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-99c2a37-3819f8d]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

**Comment by L4BORG** [comment]
The issue is still present with latest FAWE:

```
[16:11:16 INFO]: Player issued server command: //fill barrier 3 3
[16:11:16 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.IllegalArgumentException: minY <= maxY required
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[spigot-skygrid.jar:git-TacoSpigot-unknown]
        at com.sk89q.worldedit.function.mask.BoundedHeightMask.<init>(BoundedHeightMask.java:44) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.EditSession.fillXZ(EditSession.java:1491) ~[FastAsyncWorldEdit-bukkit18.jar:?]
        at com.sk89q.worldedit.EditSession.fillDirection(EditSession.java:1439) ~[FastAsyncWorldEdit-bukkit18.jar:?]
        at com.sk89q.worldedit.command.UtilityCommands.fill(UtilityCommands.java:242) ~[FastAsyncWorldEdit-bukkit18.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[FastAsyncWorldEdit-bukkit18.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-bukkit18.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:413) ~[FastAsyncWorldEdit-bukkit18.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:436) ~[FastAsyncWorldEdit-bukkit18.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:417) ~[FastAsyncWorldEdit-bukkit18.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:535) ~[FastAsyncWorldEdit-bukkit18.jar:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:335) ~[FastAsyncWorldEdit-bukkit18.jar:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit18.jar:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit18.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:67) [spigot-skygrid.jar:git-TacoSpigot-unknown]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [spigot-skygrid.jar:git-TacoSpigot-unknown]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

however it seems like it would only occur in worlds generated by Cleanroomgenerator? If this helps?

**Comment by L4BORG** [comment]
Yes, the same issue wouldn't occur on the same server but in different world that was not generated by Cleanroomgenerator.

**Comment by L4BORG** [comment]
@boy0001 I'm able to replicate like this (for example with Cleanroomgenerator) every time, but I'm not sure what's the issue.

**Comment by perpterds** [comment]
can also confirm, had same problem (i'm not privy to general server setup so i can't help there), but was able to bypass the problem with /wea

**Comment by JunTVDE** [comment]
Still present in latest 1.12.2 release, but probably ignored because not supported anymore?

**Comment by L4BORG** [comment]
Another thing to add here, sometimes error would show up instead of "no perms error" and in that case running /wea would fix the issue. So I think it could be faulty permission/wea check.
