### ISSUE TITLE
//overlay causes Asynchronous entity world add

### ISSUE THREAD

**Issue by theJ3H** [boy0001/FastAsyncWorldedit#885]
# Bug report

**Debug paste link**:
https://hastebin.com/safagaqero

**Description of the problem:**
The command //overlay causes an IllegalStateException due to asynchronous entity world add. This only happens when the selected area is quite large, smaller areas work fine. I think this might have something to do with chunks being loaded.

```
[18:03:11] [Craft Scheduler Thread - 4/INFO]: WorldEdit: J3H (in "jump"): /overlay stone - Region: (82.0, 3.0, -1210.0) - (208.0, 51.0, -925.0)
[18:03:11] [Craft Scheduler Thread - 4/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.IllegalStateException: Asynchronous entity world add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at net.minecraft.server.v1_8_R3.World.b(World.java:2633) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:820) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getLazyBlock(BukkitWorld.java:516) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.boydti.fawe.wrappers.WorldWrapper.getLazyBlock(WorldWrapper.java:326) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.extent.Extent.getLazyBlock(Extent.java:66) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.extent.Extent.getNearestSurfaceTerrainBlock(Extent.java:133) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.extent.Extent.getNearestSurfaceTerrainBlock(Extent.java:125) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getNearestSurfaceTerrainBlock(AbstractDelegateExtent.java:202) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.boydti.fawe.object.function.SurfaceRegionFunction.apply(SurfaceRegionFunction.java:30) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.function.visitor.FlatRegionVisitor.resume(FlatRegionVisitor.java:84) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:68) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.EditSession.overlayCuboidBlocks(EditSession.java:1984) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.command.RegionCommands.overlay(RegionCommands.java:361) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:245) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383) [FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468) [FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232) [FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260) [FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307) [FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:465) [FastAsyncWorldEdit-bukkit-17.11.13-12580b5-945-18.0.2.jar:?]
```

**How to replicate**:
Select a large area and use the overlay command.

**Comment by theJ3H** [comment]
This is still an issue for me.

Same issue as before, overlay isn't working on large areas.

https://hastebin.com/cuyejufala
