### ISSUE TITLE
Move Stack & Cut problems

### ISSUE THREAD

**Issue by Waffles2112** [boy0001/FastAsyncWorldedit#888]
Bug report

https://hastebin.com/ewurilefuz

[18:49:19 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.ClassCastException: com.boydti.fawe.wrappers.WorldWrapper$8 cannot be cast to java.util.function.Supplier
        at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:388) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:285) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.boydti.fawe.wrappers.WorldWrapper.getEntities(WorldWrapper.java:295) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:163) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.boydti.fawe.object.extent.FastWorldEditExtent.getEntities(FastWorldEditExtent.java:137) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:163) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.boydti.fawe.object.extent.ProcessedWEExtent.getEntities(ProcessedWEExtent.java:59) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getEntities(AbstractDelegateExtent.java:163) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.EditSession.getEntities(EditSession.java:1361) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:313) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:68) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.EditSession.stackCuboidRegion(EditSession.java:2039) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.command.RegionCommands.stack(RegionCommands.java:619) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:245) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383) [FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468) [FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232) [FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260) [FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307) [FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:465) [FastAsyncWorldEdit-bukkit-17.07.17-8c6e24a-751-13.7.9.jar:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.11.2.jar:git-Paper-1101]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1101]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

This occurs when //stack, //move, //cut, and commands similar are used, and the action the command is supposed to perform does not occur.

How to replicate:
//stack, //move, or //cut any selected area

**Comment by boy0001** [comment]
Update FAWE.
