### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#904]
FAWE dev 992
WorldEdit dev 3730
Paper dev 1318 (Spigot 1.12.2)

Error is caused when having a comma at the end of the command when listing items?
```
[15:40:40] [Server thread/INFO]: player issued server command: //set stone,3,3:1,
[15:40:40] [Craft Scheduler Thread - 504/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.12.2.jar:git-Paper-1318]
	at com.sk89q.worldedit.function.pattern.RandomPattern.add(RandomPattern.java:46) ~[FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at com.sk89q.worldedit.extension.factory.HashTagPatternParser.parseFromInput(HashTagPatternParser.java:130) ~[FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at com.sk89q.worldedit.extension.factory.HashTagPatternParser.parseFromInput(HashTagPatternParser.java:27) ~[FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:57) ~[worldedit-bukkit-6.1.9-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.internal.command.WorldEditBinding.getPattern(WorldEditBinding.java:215) ~[FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[worldedit-bukkit-6.1.9-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:222) ~[FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383) [FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468) [FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232) [FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260) [FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307) [FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:465) [FastAsyncWorldEdit-bukkit-18.01.25-7136fb4-992-18.4.7.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1318]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1318]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by Miclebrick** [comment]
Your list looks weird, it shouldn't be "//set stone,3,3:1," - rather, it should be "//set stone,3,3:1" (with no extra comma at the end)
