### ISSUE TITLE
NPE when players are kicked while stopping server

### ISSUE THREAD

**Issue by PatoTheBest** [boy0001/FastAsyncWorldedit#907]
Hello!

We've encountered a NPE while stopping the server. What happens is that one of the plugins kicks the players out of the server when stopping, but FAWE doesn't like this for some reason. Using version FastAsyncWorldEdit: 18.02.02-ec5e45f-995-18.4.10

```
java.lang.NullPointerException
        at com.sk89q.worldedit.session.SessionManager$SessionHolder.access$000(SessionManager.java:310)
        at com.sk89q.worldedit.session.SessionManager.save(SessionManager.java:223)
        at com.sk89q.worldedit.session.SessionManager.remove(SessionManager.java:278)
        at com.sk89q.worldedit.WorldEdit.removeSession(WorldEdit.java:218)
        at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:579)
        at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:586)
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor311.execute(Unknown:-1)
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
        at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:429)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1147)
        at net.minecraft.server.v1_12_R1.PlayerConnection.disconnect(PlayerConnection.java:271)
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:338)
        at net.megaplanet.commons.bukkit.AbstractJavaPlugin.lambda$onDisable$4(AbstractJavaPlugin.java:133)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at net.megaplanet.commons.bukkit.AbstractJavaPlugin.onDisable(AbstractJavaPlugin.java:133)
        at net.megaplanet.network.bukkit.MegaBukkit.onDisable(MegaBukkit.java:39)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:425)
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:418)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:355)
        at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:701)
        at java.lang.Thread.run(Thread.java:748)
```

Thanks!

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
