### ISSUE TITLE
NoSuchMethodError - WorldEdit

### ISSUE THREAD

**Issue by spannerman79** [boy0001/FastAsyncWorldedit#918]
# Bug report

**Debug paste link**:

N/A
**Description of the problem:**

```
> [09:30:13 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v18.02.11-df12aa4-1009-19.1.4
> [09:30:14 INFO]: (FAWE) ====== FAWE FAILED TO INITIALIZE ======
> [09:30:14 WARN]: java.lang.NoSuchMethodError: com.sk89q.worldedit.EditSession.inject()Ljava/lang/Class;
> [09:30:14 WARN]: at com.boydti.fawe.Fawe.setupInjector(Fawe.java:440)
> [09:30:14 WARN]: at com.boydti.fawe.bukkit.FaweBukkit.setupInjector(FaweBukkit.java:221)
> [09:30:14 WARN]: at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:96)
> [09:30:14 WARN]: at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:73)
> [09:30:14 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
> [09:30:14 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
> [09:30:14 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
> [09:30:14 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
> [09:30:14 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
> [09:30:14 WARN]: at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462)
> [09:30:14 WARN]: at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137)
> [09:30:14 WARN]: at net.minecraft.world.World.<init>(World.java:360)
> [09:30:14 WARN]: at net.minecraft.world.WorldServer.<init>(WorldServer.java:158)
> [09:30:14 WARN]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367)
> [09:30:14 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
> [09:30:14 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
> [09:30:14 WARN]: at java.lang.Thread.run(Thread.java:748)
```
**How to replicate**:

Obtain everything that is outlined in https://github.com/boy0001/FastAsyncWorldedit/releases for 1.7.10 Cauldron/Thermos. Including the correctly listed build of worldedit etc via wayback

```
> [09:33:39 INFO]: WorldEdit version (unknown)
> [09:33:39 INFO]: https://github.com/sk89q/worldedit/
> [09:33:39 INFO]: ----------- Platforms -----------
> [09:33:39 INFO]: * Forge-Official (6.1.2-SNAPSHOT)
> [09:33:39 INFO]: * Bukkit-Official (6.1.4-SNAPSHOT;3572-d0cf497)
> [09:33:39 INFO]: ----------- Capabilities -----------
> [09:33:39 INFO]: GAME_HOOKS: Bukkit-Official
> [09:33:39 INFO]: CONFIGURATION: Bukkit-Official
> [09:33:39 INFO]: USER_COMMANDS: Bukkit-Official
> [09:33:39 INFO]: PERMISSIONS: Bukkit-Official
> [09:33:39 INFO]: WORLDEDIT_CUI: Forge-Official
> [09:33:39 INFO]: WORLD_EDITING: Forge-Official
```

Similar to Issue https://github.com/boy0001/FastAsyncWorldedit/issues/71

**Comment by boy0001** [comment]
You need to be using the forge FAWE, not the bukkit one.
