### ISSUE TITLE
Async block remove error.

### ISSUE THREAD

**Issue by Nayrisian** [boy0001/FastAsyncWorldedit#92]
http://puu.sh/oCFbK/198db45591.png

`Exception in thread "Thread-86"
java.lang.IllegalStateException: Asynchronous block remove!
       at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
       at net.minecraft.server.v1_9_R1.Block.remove(Block.java:282)
       at net.minecraft.server.v1_9_R1.Chunk.a(Chunk.java:468)
       at net.minecraft.server.v1_9_R1.World.setTypeAndData(World.java:365)
       at org.bukkit.craftbukkit.v1_9_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:142)
       at org.bukkit.craftbukkit.v1_9_R1.block.CraftBlock.setTypeId(CraftBlock.java:132)
       at com.boydti.fawe.bukkit.v0.BukkitQueue_0$1.run(BukkitQueue_0.java:139)
       at java.lang.Thread.run(Unknown Source)`

This happens when trying to do a region operation such as //set <block>

For me, this is reproducible across a public server I maintain and a private server I use for just testing with default settings so I know there are not conflicts with particular plugins.

Latest build of Spigot.
Latest build of FastAsyncWorldEdit.
Latest build of Vault (On Bukkit.org)
Latest build of WorldEdit. (6.1.1-SNAPSHOT)
Latest build of WorldGuard (6.1.2-SNAPSHOT)

A side-note, re-logging into the server allows me to see a section of the operation I tried to perform.

**Comment by boy0001** [comment]
It looks like you aren't using the 1.9 version of FAWE? Check console for any errors / debug messages.

**Comment by Nayrisian** [comment]
Ah, yeah, sorry about that, 1.8.8 is on top of the 1.9 and I downloaded the wrong one, sorry about that.
