### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by sKye27** [boy0001/FastAsyncWorldedit#924]
when the server starts this error appears
```
[17:39:01 WARN]: [FastAsyncWorldEdit] Task #9 for FastAsyncWorldEdit v18.02.15-7141cc4-1012-19.1.7 generated an exception
java.lang.OutOfMemoryError: Java heap space
at java.util.HashMap.resize(HashMap.java:704) ~[?:1.8.0_151]
at java.util.HashMap.putVal(HashMap.java:663) ~[?:1.8.0_151]
at java.util.HashMap.put(HashMap.java:612) ~[?:1.8.0_151]
at java.util.HashSet.add(HashSet.java:220) ~[?:1.8.0_151]
at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.createRegisteredListeners(PerWorldPluginLoader.java:62) ~[?:?]
at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:527) ~[server.jar:git-Spigot-db6de12-18fbb24]
at com.boydti.fawe.bukkit.v0.ChunkListener.<init>(ChunkListener.java:50) ~[?:?]
at com.boydti.fawe.bukkit.v0.ChunkListener_8.<init>(ChunkListener_8.java:5) ~[?:?]
at com.boydti.fawe.bukkit.FaweBukkit$1.run(FaweBukkit.java:144) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by SirYwell** [comment]
How much RAM can your server use?

**Comment by sKye27** [comment]
1 gb

**Comment by SirYwell** [comment]
Can you use more RAM? Otherwise, how much plugins do you have installed? Probably you need to reduce it...

**Comment by sKye27** [comment]
ok i will try

**Comment by SirYwell** [comment]
Did it worked for you?

**Comment by sKye27** [comment]
no i tryed with 4gb and also now work and i have only 20 plugins

**Comment by SirYwell** [comment]
Then please use /fawe debugpaste and put the link in here

**Comment by sKye27** [comment]
https://hastebin.com/imunuceqef

**Comment by boy0001** [comment]
I'd suggest trying without PerWorldPlugins
