### ISSUE TITLE
Many problem with WorldEdit and FAWE

### ISSUE THREAD

**Issue by DevilishDante** [boy0001/FastAsyncWorldedit#928]
hello i have this problem
```
[18:16:01 INFO]: DevilishDante issued server command: //copy
[18:16:01 INFO]: (FAWE) Running 1.12 registry dumper!
[18:16:02 INFO]: (FAWE) Using adapter: com.boydti.fawe.bukkit.v1_12.FaweAdapter_1_12@48d28ca3
[18:16:02 INFO]: (FAWE) =========================================
[18:16:14 INFO]: DevilishDante issued server command: //copy
[18:16:14 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.NoSuchMethodError: com.sk89q.minecraft.util.commands.CommandContext.split(Ljava/lang/String;)[Ljava/lang/String;
at com.sk89q.worldedit.util.command.parametric.StringArgumentStack.‹init›(StringArgumentStack.java:61) ~[worldedit-bukkit-6.1.7.3.jar:?]
at com.sk89q.worldedit.util.command.parametric.ParametricCallable.getScopedContext(ParametricCallable.java:414) ~[FastAsyncWorldEdit-bukkit-18.02.15-7141cc4-1012-19.1.7.jar:?]
at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:219) ~[FastAsyncWorldEdit-bukkit-18.02.15-7141cc4-1012-19.1.7.jar:?]
at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[FastAsyncWorldEdit-bukkit-18.02.15-7141cc4-1012-19.1.7.jar:?]
at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:383) [FastAsyncWorldEdit-bukkit-18.02.15-7141cc4-1012-19.1.7.jar:?]
at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:468) [FastAsyncWorldEdit-bukkit-18.02.15-7141cc4-1012-19.1.7.jar:?]
at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232) [FastAsyncWorldEdit-bukkit-18.02.15-7141cc4-1012-19.1.7.jar:?]
at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260) [FastAsyncWorldEdit-bukkit-18.02.15-7141cc4-1012-19.1.7.jar:?]
at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307) [FastAsyncWorldEdit-bukkit-18.02.15-7141cc4-1012-19.1.7.jar:?]
at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:465) [FastAsyncWorldEdit-bukkit-18.02.15-7141cc4-1012-19.1.7.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-596221b-b1b9ab0]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-596221b-b1b9ab0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45-internal]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45-internal]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
```

When i try //copy //paste or many other command with worldedit i have this error
https://hastebin.com/zoqilasegi <-- here a debug link 

in game i have:
There was an error handling a FAWE command: [see console]
java.lang.NoSuchMethodError:
com.sk89q.minecraft.util.commands.CommandContext.split(Ljava/lang/String;)[Ljava/lang/String;

thanks

**Comment by boy0001** [comment]
It's an issue with the plugin failing to load properly. Try deleting WorldEdit and letting FAWE download it automatically.

**Comment by DevilishDante** [comment]
@boy0001 ok y try this :o

**Comment by xion87** [comment]
same here
https://hastebin.com/iyegurowam.scala

**Comment by N0tMyFaultOG** [comment]
Update fawe
If the issue persists still, reply to the ticket
