### ISSUE TITLE
ClassCastException at //regen

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#93]
FAWE 3.4.3
Spigot 1.8.8

```
[10:56:55] [Server thread/INFO]: Olaf issued server command: //regen
[10:56:55] [Craft Scheduler Thread - 212/INFO]: §cPotentially inefficient WorldEdit extent: PrismWorldEditLogger
[10:56:55] [Craft Scheduler Thread - 212/INFO]: §8 - §7For area restrictions, it is recommended to use the FaweAPI
[10:56:55] [Craft Scheduler Thread - 212/INFO]: §8 - §7To allow this plugin add it to the FAWE `allowed-plugins` list
[10:56:55] [Craft Scheduler Thread - 212/INFO]: §cPotentially inefficient WorldEdit extent: PrismWorldEditLogger
[10:56:55] [Craft Scheduler Thread - 212/INFO]: §8 - §7For area restrictions, it is recommended to use the FaweAPI
[10:56:55] [Craft Scheduler Thread - 212/INFO]: §8 - §7To allow this plugin add it to the FAWE `allowed-plugins` list
[10:56:55] [Craft Scheduler Thread - 212/INFO]: §cPotentially inefficient WorldEdit extent: PrismWorldEditLogger
[10:56:55] [Craft Scheduler Thread - 212/INFO]: §8 - §7For area restrictions, it is recommended to use the FaweAPI
[10:56:55] [Craft Scheduler Thread - 212/INFO]: §8 - §7To allow this plugin add it to the FAWE `allowed-plugins` list
[10:56:55] [Server thread/WARN]: [FastAsyncWorldEdit] Task #247518 for FastAsyncWorldEdit v3.4.3 generated an exception
java.lang.ClassCastException: [Lnet.minecraft.server.v1_8_R3.ChunkSection; cannot be cast to [C
        at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.getCombinedId4Data(BukkitQueue18R3.java:30) ~[?:?]
        at com.boydti.fawe.example.MappedFaweQueue.getCombinedId4Data(MappedFaweQueue.java:281) ~[?:?]
        at com.boydti.fawe.wrappers.WorldWrapper$6.run(WorldWrapper.java:283) ~[?:?]
        at com.boydti.fawe.wrappers.WorldWrapper$6.run(WorldWrapper.java:237) ~[?:?]
        at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
        at com.boydti.fawe.util.TaskManager$1.run(TaskManager.java:122) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
[10:57:27] [Server thread/INFO]: Olaf issued server command: /wea
[10:57:29] [Server thread/INFO]: Olaf issued server command: //expand vert
[10:57:31] [Server thread/INFO]: Olaf issued server command: //regen
[10:57:31] [Server thread/WARN]: [FastAsyncWorldEdit] Task #248354 for FastAsyncWorldEdit v3.4.3 generated an exception
java.lang.ClassCastException: [Lnet.minecraft.server.v1_8_R3.ChunkSection; cannot be cast to [C
        at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.getCombinedId4Data(BukkitQueue18R3.java:30) ~[?:?]
        at com.boydti.fawe.example.MappedFaweQueue.getCombinedId4Data(MappedFaweQueue.java:281) ~[?:?]
        at com.boydti.fawe.wrappers.WorldWrapper$6.run(WorldWrapper.java:283) ~[?:?]
        at com.boydti.fawe.wrappers.WorldWrapper$6.run(WorldWrapper.java:237) ~[?:?]
        at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
        at com.boydti.fawe.util.TaskManager$1.run(TaskManager.java:122) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by EvilOlaf** [comment]
Another one on //set
```
[14:26:50] [Craft Scheduler Thread - 386/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.ClassCastException: [Lnet.minecraft.server.v1_8_R3.ChunkSection; cannot be cast to [C
        at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.getCombinedId4Data(BukkitQueue18R3.java:30) ~[FastAsyncWorldEdit-bukkit343.jar:?]
        at com.boydti.fawe.example.MappedFaweQueue.getCombinedId4Data(MappedFaweQueue.java:281) ~[FastAsyncWorldEdit-bukkit343.jar:?]
        at com.boydti.fawe.util.FaweQueue.getCombinedId4DataDebug(FaweQueue.java:95) ~[FastAsyncWorldEdit-bukkit343.jar:?]
        at com.boydti.fawe.object.HistoryExtent.setBlock(HistoryExtent.java:57) ~[FastAsyncWorldEdit-bukkit343.jar:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-3482.jar:?]
        at com.boydti.fawe.object.extent.SafeExtentWrapper.setBlock(SafeExtentWrapper.java:24) ~[FastAsyncWorldEdit-bukkit343.jar:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:754) ~[FastAsyncWorldEdit-bukkit343.jar:?]
        at com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:53) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-3482.jar:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:58) ~[FastAsyncWorldEdit-bukkit343.jar:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:69) ~[FastAsyncWorldEdit-bukkit343.jar:?]
        at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:167) ~[FastAsyncWorldEdit-bukkit343.jar:?]
        at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:64) ~[FastAsyncWorldEdit-bukkit343.jar:?]
        at com.sk89q.worldedit.util.command.composition.LegacyCommandAdapter.call(LegacyCommandAdapter.java:52) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-3482.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-3482.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:253) [FastAsyncWorldEdit-bukkit343.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by boy0001** [comment]
Duplicate
