### ISSUE TITLE
InvocationTargetException on //cut

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#94]
FAWE 3.4.3
Spigot 1.8.8
WE 3482

```
[14:26:24] [Server thread/INFO]: Olaf issued server command: //Cut
[14:26:24] [Craft Scheduler Thread - 384/INFO]: §cPotentially inefficient WorldEdit extent: PrismWorldEditLogger
[14:26:24] [Craft Scheduler Thread - 384/INFO]: §8 - §7For area restrictions, it is recommended to use the FaweAPI
[14:26:24] [Craft Scheduler Thread - 384/INFO]: §8 - §7To allow this plugin add it to the FAWE `allowed-plugins` list
[14:26:24] [Craft Scheduler Thread - 384/INFO]: §cPotentially inefficient WorldEdit extent: PrismWorldEditLogger
[14:26:24] [Craft Scheduler Thread - 384/INFO]: §8 - §7For area restrictions, it is recommended to use the FaweAPI
[14:26:24] [Craft Scheduler Thread - 384/INFO]: §8 - §7To allow this plugin add it to the FAWE `allowed-plugins` list
[14:26:24] [Craft Scheduler Thread - 384/INFO]: §cPotentially inefficient WorldEdit extent: PrismWorldEditLogger
[14:26:24] [Craft Scheduler Thread - 384/INFO]: §8 - §7For area restrictions, it is recommended to use the FaweAPI
[14:26:24] [Craft Scheduler Thread - 384/INFO]: §8 - §7To allow this plugin add it to the FAWE `allowed-plugins` list
[14:26:24] [Craft Scheduler Thread - 384/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-3482.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-3482.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:253) [FastAsyncWorldEdit-bukkit343.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.ClassCastException: [Lnet.minecraft.server.v1_8_R3.ChunkSection; cannot be cast to [C
        at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.getCombinedId4Data(BukkitQueue18R3.java:30) ~[?:?]
        at com.boydti.fawe.example.MappedFaweQueue.getCombinedId4Data(MappedFaweQueue.java:281) ~[?:?]
        at com.boydti.fawe.util.FaweQueue.getCombinedId4DataDebug(FaweQueue.java:95) ~[?:?]
        at com.sk89q.worldedit.EditSession.getLazyBlock(EditSession.java:606) ~[?:?]
        at com.sk89q.worldedit.EditSession.getLazyBlock(EditSession.java:599) ~[?:?]
        at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:621) ~[?:?]
        at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:66) ~[?:?]
        at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[?:?]
        at com.sk89q.worldedit.function.CombinedRegionFunction.apply(CombinedRegionFunction.java:84) ~[?:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:58) ~[?:?]
        at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89) ~[?:?]
        at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:69) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:56) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.cut(ClipboardCommands.java:200) ~[?:?]
        ... 12 more
```

**Comment by boy0001** [comment]
Try the dev build
http://ci.athion.net/job/FastAsyncWorldEdit/
