### ISSUE TITLE
Issue with conversion of vanilla map from a server

### ISSUE THREAD

**Issue by thesigae** [boy0001/FastAsyncWorldedit#941]
# Bug report on conversion

Hello,
I am trying to run your program to convert this map that we have running on a fragnet server. It is just a simple vanilla server.
Here is the link to the map.
https://drive.google.com/open?id=1UQDogtI4GdpS21U3qv5rhGsJw4yxChs1 

**Description of the problem:**
Downloading levedb.jar and mappings (~4MB), please wait...
Starting converter...
java.lang.NoClassDefFoundError: org/iq80/leveldb/impl/Iq80DBFactory
	at com.boydti.fawe.nukkit.core.converter.MCAFile2LevelDB.<init>(MCAFile2LevelDB.java:109)
	at com.boydti.fawe.nukkit.core.converter.MapConverter.get(MapConverter.java:21)
	at com.boydti.fawe.nukkit.core.converter.ConverterFrame$7.run(ConverterFrame.java:458)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.iq80.leveldb.impl.Iq80DBFactory
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more
ﾧ8(ﾧ4ﾧlFAWEﾧ8)ﾧrﾧ7 [ERROR] Conversion failed, you will have to do it manually (Nukkit server + anvil2leveldb command)

**How to replicate**:
Just start the conversion process. 

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
