### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by AntoLuMeju99** [boy0001/FastAsyncWorldedit#943]
Hi i'm getting this error with spam in my console:

[18:42:43 ERROR]: stopTiming called async for anti-xray - obfuscate
[18:42:43 WARN]: java.lang.Throwable
[18:42:43 WARN]: at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[18:42:43 WARN]: at org.spigotmc.AntiXray.obfuscateSync(AntiXray.java:103)
[18:42:43 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayOutMapChunk.(PacketPlayOutMapChunk.java:22)
[18:42:43 WARN]: at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.sendChunk(BukkitQueue18R3.java:508)
[18:42:43 WARN]: at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.sendChunk(BukkitQueue18R3.java:461)
[18:42:43 WARN]: at com.boydti.fawe.example.NMSRelighter$1.run(NMSRelighter.java:325)
[18:42:43 WARN]: at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[18:42:43 WARN]: at com.boydti.fawe.example.NMSRelighter.sendChunks(NMSRelighter.java:331)
[18:42:43 WARN]: at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:297)
[18:42:43 WARN]: at com.boydti.fawe.example.NMSMappedFaweQueue$1.run(NMSMappedFaweQueue.java:47)
[18:42:43 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[18:42:43 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:42:43 WARN]: at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[18:42:43 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:42:43 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:42:43 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by boy0001** [comment]
It's an incompatibility with the anti-xray. Either disable anti-xray, or set `async: false` on line 43 of the FAWE `config.yml`
