### ISSUE TITLE
AntiXray

### ISSUE THREAD

**Issue by yooniks** [boy0001/FastAsyncWorldedit#945]
Hi guys, I have error in my server's logs and it's caused by fawe, how can I fix that?
```
[13:56:41] [Craft Scheduler Thread - 155/WARN]: java.lang.Throwable
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at org.spigotmc.AntiXray.obfuscateSync(AntiXray.java:103)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayOutMapChunk.<init>(PacketPlayOutMapChunk.java:22)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.sendChunk(BukkitQueue18R3.java:508)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.sendChunk(BukkitQueue18R3.java:461)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.example.NMSRelighter$1.run(NMSRelighter.java:325)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.example.NMSRelighter.sendChunks(NMSRelighter.java:331)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:297)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue$1.run(NMSMappedFaweQueue.java:47)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:56:41] [Craft Scheduler Thread - 155/ERROR]: stopTiming called async for anti-xray - obfuscate
[13:56:41] [Craft Scheduler Thread - 155/WARN]: java.lang.Throwable
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at org.spigotmc.AntiXray.obfuscateSync(AntiXray.java:103)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayOutMapChunk.<init>(PacketPlayOutMapChunk.java:22)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.sendChunk(BukkitQueue18R3.java:508)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.sendChunk(BukkitQueue18R3.java:461)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.example.NMSRelighter$1.run(NMSRelighter.java:325)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.example.NMSRelighter.sendChunks(NMSRelighter.java:331)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:297)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at com.boydti.fawe.example.NMSMappedFaweQueue$1.run(NMSMappedFaweQueue.java:47)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:56:41] [Craft Scheduler Thread - 155/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
https://hastebin.com/itiginaper.md

**Comment by boy0001** [comment]
#943

It's an incompatibility with the anti-xray. Either disable anti-xray, or set `async: false` on line 43 of the FAWE `config.yml`
