### ISSUE TITLE
Servercrash on undo

### ISSUE THREAD

**Issue by tr7zw** [boy0001/FastAsyncWorldedit#95]
After undoing a building the server crashed with this error. (Looks like damage values on Air blocks)
`[22:53:06 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_9_R1.ReportedException: Ticking block entity
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:803) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-f631379]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.IllegalArgumentException: Cannot get property BlockStateInteger{name=power, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockStateList{block=minecraft:air, properties=[]}
        at net.minecraft.server.v1_9_R1.BlockStateList$BlockData.get(SourceFile:165) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.BlockDaylightDetector.c(BlockDaylightDetector.java:47) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.TileEntityLightDetector.c(SourceFile:16) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1486) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:629) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) ~[spigot.jar:git-Spigot-5a40365-f631379]
        ... 4 more
[22:53:06 ERROR]:       Cause of unexpected exception was
java.lang.IllegalArgumentException: Cannot get property BlockStateInteger{name=power, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockStateList{block=minecraft:air, properties=[]}
        at net.minecraft.server.v1_9_R1.BlockStateList$BlockData.get(SourceFile:165) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.BlockDaylightDetector.c(BlockDaylightDetector.java:47) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.TileEntityLightDetector.c(SourceFile:16) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1486) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:629) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) ~[spigot.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-f631379]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]`

**Comment by boy0001** [comment]
Update spigot.
