### ISSUE TITLE
WE dont work))

### ISSUE THREAD

**Issue by NITDroid1995** [boy0001/FastAsyncWorldedit#968]
# Bug report
[23:29:38 WARN]: java.lang.NoSuchFieldException: d
[23:29:38 WARN]:        at java.lang.Class.getDeclaredField(Class.java:2070)
[23:29:38 WARN]:        at com.boydti.fawe.bukkit.v1_7.BukkitQueue17$2.run(BukkitQueue17.java:497)
[23:29:38 WARN]:        at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[23:29:38 WARN]:        at com.boydti.fawe.object.RunnableVal.runAndGet(RunnableVal.java:22)
[23:29:38 WARN]:        at com.boydti.fawe.object.RunnableVal.get(RunnableVal.java:30)
[23:29:38 WARN]:        at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:400)
[23:29:38 WARN]:        at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[23:29:38 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[23:29:38 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[23:29:38 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
[23:29:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[23:29:38 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[23:29:38 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[23:29:38 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Debug paste link**:
https://hastebin.com/afifaqoxab

**Description of the problem:**
all comands from WE dont work)

**How to replicate**:
using anyone command from WE

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by NITDroid1995** [comment]
After today update WE didnt work

**Comment by NITDroid1995** [comment]
its continue
[01:42:26 WARN]: java.lang.NoSuchFieldException: d
[01:42:26 WARN]:        at java.lang.Class.getDeclaredField(Class.java:2070)
[01:42:26 WARN]:        at com.boydti.fawe.bukkit.v1_7.BukkitQueue17$2.run(BukkitQueue17.java:497)
[01:42:26 WARN]:        at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[01:42:26 WARN]:        at com.boydti.fawe.object.RunnableVal.runAndGet(RunnableVal.java:22)
[01:42:26 WARN]:        at com.boydti.fawe.object.RunnableVal.get(RunnableVal.java:30)
[01:42:26 WARN]:        at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:400)
[01:42:26 WARN]:        at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[01:42:26 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[01:42:26 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[01:42:26 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
[01:42:26 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[01:42:26 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[01:42:26 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[01:42:26 WARN]:        at java.lang.Thread.run(Thread.java:748)
 Please help)))

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.
